// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/garmin_contacts.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       []*Contact             `protobuf:"bytes,1,rep,name=contact" json:"contact,omitempty"`
	Self          *Contact               `protobuf:"bytes,2,opt,name=self" json:"self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_garmin_garmin_contacts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_garmin_contacts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_garmin_garmin_contacts_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetContact() []*Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

func (x *Response) GetSelf() *Contact {
	if x != nil {
		return x.Self
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"` // "SELF" on self
	FullName      *string                `protobuf:"bytes,2,opt,name=fullName" json:"fullName,omitempty"`
	FirstName     *string                `protobuf:"bytes,3,opt,name=firstName" json:"firstName,omitempty"`
	LastName      *string                `protobuf:"bytes,4,opt,name=lastName" json:"lastName,omitempty"`
	Phone         []*Phone               `protobuf:"bytes,5,rep,name=phone" json:"phone,omitempty"`
	Unk7          *string                `protobuf:"bytes,7,opt,name=unk7" json:"unk7,omitempty"`     // ""
	Unk8          *uint32                `protobuf:"varint,8,opt,name=unk8" json:"unk8,omitempty"`    // 0
	Unk9          *uint32                `protobuf:"varint,9,opt,name=unk9" json:"unk9,omitempty"`    // 0
	Unk10         *uint32                `protobuf:"varint,10,opt,name=unk10" json:"unk10,omitempty"` // 0
	UpdateTime    *uint64                `protobuf:"varint,11,opt,name=updateTime" json:"updateTime,omitempty"`
	Unk12         *uint32                `protobuf:"varint,12,opt,name=unk12" json:"unk12,omitempty"` // 0
	Unk21         *uint32                `protobuf:"varint,21,opt,name=unk21" json:"unk21,omitempty"` // 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_garmin_garmin_contacts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_garmin_contacts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_garmin_garmin_contacts_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Contact) GetFullName() string {
	if x != nil && x.FullName != nil {
		return *x.FullName
	}
	return ""
}

func (x *Contact) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *Contact) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *Contact) GetPhone() []*Phone {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *Contact) GetUnk7() string {
	if x != nil && x.Unk7 != nil {
		return *x.Unk7
	}
	return ""
}

func (x *Contact) GetUnk8() uint32 {
	if x != nil && x.Unk8 != nil {
		return *x.Unk8
	}
	return 0
}

func (x *Contact) GetUnk9() uint32 {
	if x != nil && x.Unk9 != nil {
		return *x.Unk9
	}
	return 0
}

func (x *Contact) GetUnk10() uint32 {
	if x != nil && x.Unk10 != nil {
		return *x.Unk10
	}
	return 0
}

func (x *Contact) GetUpdateTime() uint64 {
	if x != nil && x.UpdateTime != nil {
		return *x.UpdateTime
	}
	return 0
}

func (x *Contact) GetUnk12() uint32 {
	if x != nil && x.Unk12 != nil {
		return *x.Unk12
	}
	return 0
}

func (x *Contact) GetUnk21() uint32 {
	if x != nil && x.Unk21 != nil {
		return *x.Unk21
	}
	return 0
}

type Phone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        *string                `protobuf:"bytes,1,opt,name=number" json:"number,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"`    // 1
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"`    // 1
	Unk4          *uint32                `protobuf:"varint,4,opt,name=unk4" json:"unk4,omitempty"`    // 0
	Unk5          *uint32                `protobuf:"varint,5,opt,name=unk5" json:"unk5,omitempty"`    // random number
	Unk6          *uint32                `protobuf:"varint,6,opt,name=unk6" json:"unk6,omitempty"`    // 0
	Unk7          *uint32                `protobuf:"varint,7,opt,name=unk7" json:"unk7,omitempty"`    // 0
	Unk8          *string                `protobuf:"bytes,8,opt,name=unk8" json:"unk8,omitempty"`     // ""
	Unk9          *uint32                `protobuf:"varint,9,opt,name=unk9" json:"unk9,omitempty"`    // 1
	Id            *string                `protobuf:"bytes,10,opt,name=id" json:"id,omitempty"`        // uuid
	Unk11         *uint32                `protobuf:"varint,11,opt,name=unk11" json:"unk11,omitempty"` // 1
	Unk12         []*Unk12               `protobuf:"bytes,12,rep,name=unk12" json:"unk12,omitempty"`  // 1/5, 2/5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Phone) Reset() {
	*x = Phone{}
	mi := &file_garmin_garmin_contacts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phone) ProtoMessage() {}

func (x *Phone) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_garmin_contacts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phone.ProtoReflect.Descriptor instead.
func (*Phone) Descriptor() ([]byte, []int) {
	return file_garmin_garmin_contacts_proto_rawDescGZIP(), []int{2}
}

func (x *Phone) GetNumber() string {
	if x != nil && x.Number != nil {
		return *x.Number
	}
	return ""
}

func (x *Phone) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *Phone) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *Phone) GetUnk4() uint32 {
	if x != nil && x.Unk4 != nil {
		return *x.Unk4
	}
	return 0
}

func (x *Phone) GetUnk5() uint32 {
	if x != nil && x.Unk5 != nil {
		return *x.Unk5
	}
	return 0
}

func (x *Phone) GetUnk6() uint32 {
	if x != nil && x.Unk6 != nil {
		return *x.Unk6
	}
	return 0
}

func (x *Phone) GetUnk7() uint32 {
	if x != nil && x.Unk7 != nil {
		return *x.Unk7
	}
	return 0
}

func (x *Phone) GetUnk8() string {
	if x != nil && x.Unk8 != nil {
		return *x.Unk8
	}
	return ""
}

func (x *Phone) GetUnk9() uint32 {
	if x != nil && x.Unk9 != nil {
		return *x.Unk9
	}
	return 0
}

func (x *Phone) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Phone) GetUnk11() uint32 {
	if x != nil && x.Unk11 != nil {
		return *x.Unk11
	}
	return 0
}

func (x *Phone) GetUnk12() []*Unk12 {
	if x != nil {
		return x.Unk12
	}
	return nil
}

type Unk12 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 1/2
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unk12) Reset() {
	*x = Unk12{}
	mi := &file_garmin_garmin_contacts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unk12) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unk12) ProtoMessage() {}

func (x *Unk12) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_garmin_contacts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unk12.ProtoReflect.Descriptor instead.
func (*Unk12) Descriptor() ([]byte, []int) {
	return file_garmin_garmin_contacts_proto_rawDescGZIP(), []int{3}
}

func (x *Unk12) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

func (x *Unk12) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

var File_garmin_garmin_contacts_proto protoreflect.FileDescriptor

const file_garmin_garmin_contacts_proto_rawDesc = "" +
	"\n" +
	"\x1cgarmin/garmin_contacts.proto\x12\x06garmin\"Z\n" +
	"\bResponse\x12)\n" +
	"\acontact\x18\x01 \x03(\v2\x0f.garmin.ContactR\acontact\x12#\n" +
	"\x04self\x18\x02 \x01(\v2\x0f.garmin.ContactR\x04self\"\xb2\x02\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfullName\x18\x02 \x01(\tR\bfullName\x12\x1c\n" +
	"\tfirstName\x18\x03 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x04 \x01(\tR\blastName\x12#\n" +
	"\x05phone\x18\x05 \x03(\v2\r.garmin.PhoneR\x05phone\x12\x12\n" +
	"\x04unk7\x18\a \x01(\tR\x04unk7\x12\x12\n" +
	"\x04unk8\x18\b \x01(\rR\x04unk8\x12\x12\n" +
	"\x04unk9\x18\t \x01(\rR\x04unk9\x12\x14\n" +
	"\x05unk10\x18\n" +
	" \x01(\rR\x05unk10\x12\x1e\n" +
	"\n" +
	"updateTime\x18\v \x01(\x04R\n" +
	"updateTime\x12\x14\n" +
	"\x05unk12\x18\f \x01(\rR\x05unk12\x12\x14\n" +
	"\x05unk21\x18\x15 \x01(\rR\x05unk21\"\x8a\x02\n" +
	"\x05Phone\x12\x16\n" +
	"\x06number\x18\x01 \x01(\tR\x06number\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12\x12\n" +
	"\x04unk4\x18\x04 \x01(\rR\x04unk4\x12\x12\n" +
	"\x04unk5\x18\x05 \x01(\rR\x04unk5\x12\x12\n" +
	"\x04unk6\x18\x06 \x01(\rR\x04unk6\x12\x12\n" +
	"\x04unk7\x18\a \x01(\rR\x04unk7\x12\x12\n" +
	"\x04unk8\x18\b \x01(\tR\x04unk8\x12\x12\n" +
	"\x04unk9\x18\t \x01(\rR\x04unk9\x12\x0e\n" +
	"\x02id\x18\n" +
	" \x01(\tR\x02id\x12\x14\n" +
	"\x05unk11\x18\v \x01(\rR\x05unk11\x12#\n" +
	"\x05unk12\x18\f \x03(\v2\r.garmin.Unk12R\x05unk12\"/\n" +
	"\x05Unk12\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2Bi\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminB\x0eGarminContactsZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_garmin_contacts_proto_rawDescOnce sync.Once
	file_garmin_garmin_contacts_proto_rawDescData []byte
)

func file_garmin_garmin_contacts_proto_rawDescGZIP() []byte {
	file_garmin_garmin_contacts_proto_rawDescOnce.Do(func() {
		file_garmin_garmin_contacts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_garmin_contacts_proto_rawDesc), len(file_garmin_garmin_contacts_proto_rawDesc)))
	})
	return file_garmin_garmin_contacts_proto_rawDescData
}

var file_garmin_garmin_contacts_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_garmin_garmin_contacts_proto_goTypes = []any{
	(*Response)(nil), // 0: garmin.Response
	(*Contact)(nil),  // 1: garmin.Contact
	(*Phone)(nil),    // 2: garmin.Phone
	(*Unk12)(nil),    // 3: garmin.Unk12
}
var file_garmin_garmin_contacts_proto_depIdxs = []int32{
	1, // 0: garmin.Response.contact:type_name -> garmin.Contact
	1, // 1: garmin.Response.self:type_name -> garmin.Contact
	2, // 2: garmin.Contact.phone:type_name -> garmin.Phone
	3, // 3: garmin.Phone.unk12:type_name -> garmin.Unk12
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_garmin_garmin_contacts_proto_init() }
func file_garmin_garmin_contacts_proto_init() {
	if File_garmin_garmin_contacts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_garmin_contacts_proto_rawDesc), len(file_garmin_garmin_contacts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_garmin_contacts_proto_goTypes,
		DependencyIndexes: file_garmin_garmin_contacts_proto_depIdxs,
		MessageInfos:      file_garmin_garmin_contacts_proto_msgTypes,
	}.Build()
	File_garmin_garmin_contacts_proto = out.File
	file_garmin_garmin_contacts_proto_goTypes = nil
	file_garmin_garmin_contacts_proto_depIdxs = nil
}
