// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_device_status.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeviceStatusService_ResponseStatus int32

const (
	DeviceStatusService_UNKNOWN_RESPONSE_STATUS DeviceStatusService_ResponseStatus = 0
	DeviceStatusService_OK                      DeviceStatusService_ResponseStatus = 1
	DeviceStatusService_NO_REMOTE_DEVICE        DeviceStatusService_ResponseStatus = 2
)

// Enum value maps for DeviceStatusService_ResponseStatus.
var (
	DeviceStatusService_ResponseStatus_name = map[int32]string{
		0: "UNKNOWN_RESPONSE_STATUS",
		1: "OK",
		2: "NO_REMOTE_DEVICE",
	}
	DeviceStatusService_ResponseStatus_value = map[string]int32{
		"UNKNOWN_RESPONSE_STATUS": 0,
		"OK":                      1,
		"NO_REMOTE_DEVICE":        2,
	}
)

func (x DeviceStatusService_ResponseStatus) Enum() *DeviceStatusService_ResponseStatus {
	p := new(DeviceStatusService_ResponseStatus)
	*p = x
	return p
}

func (x DeviceStatusService_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatusService_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_device_status_proto_enumTypes[0].Descriptor()
}

func (DeviceStatusService_ResponseStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_device_status_proto_enumTypes[0]
}

func (x DeviceStatusService_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceStatusService_ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceStatusService_ResponseStatus(num)
	return nil
}

// Deprecated: Use DeviceStatusService_ResponseStatus.Descriptor instead.
func (DeviceStatusService_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 0}
}

type DeviceStatusService_ActivityStatusResponse_ActivityStatus int32

const (
	DeviceStatusService_ActivityStatusResponse_OFF     DeviceStatusService_ActivityStatusResponse_ActivityStatus = 0
	DeviceStatusService_ActivityStatusResponse_STOPPED DeviceStatusService_ActivityStatusResponse_ActivityStatus = 1
	DeviceStatusService_ActivityStatusResponse_PAUSED  DeviceStatusService_ActivityStatusResponse_ActivityStatus = 2
	DeviceStatusService_ActivityStatusResponse_ON      DeviceStatusService_ActivityStatusResponse_ActivityStatus = 3
)

// Enum value maps for DeviceStatusService_ActivityStatusResponse_ActivityStatus.
var (
	DeviceStatusService_ActivityStatusResponse_ActivityStatus_name = map[int32]string{
		0: "OFF",
		1: "STOPPED",
		2: "PAUSED",
		3: "ON",
	}
	DeviceStatusService_ActivityStatusResponse_ActivityStatus_value = map[string]int32{
		"OFF":     0,
		"STOPPED": 1,
		"PAUSED":  2,
		"ON":      3,
	}
)

func (x DeviceStatusService_ActivityStatusResponse_ActivityStatus) Enum() *DeviceStatusService_ActivityStatusResponse_ActivityStatus {
	p := new(DeviceStatusService_ActivityStatusResponse_ActivityStatus)
	*p = x
	return p
}

func (x DeviceStatusService_ActivityStatusResponse_ActivityStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DeviceStatusService_ActivityStatusResponse_ActivityStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_device_status_proto_enumTypes[1].Descriptor()
}

func (DeviceStatusService_ActivityStatusResponse_ActivityStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_device_status_proto_enumTypes[1]
}

func (x DeviceStatusService_ActivityStatusResponse_ActivityStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DeviceStatusService_ActivityStatusResponse_ActivityStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DeviceStatusService_ActivityStatusResponse_ActivityStatus(num)
	return nil
}

// Deprecated: Use DeviceStatusService_ActivityStatusResponse_ActivityStatus.Descriptor instead.
func (DeviceStatusService_ActivityStatusResponse_ActivityStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 4, 0}
}

type DeviceStatusService struct {
	state                                        protoimpl.MessageState                                            `protogen:"open.v1"`
	RemoteDeviceBatteryStatusChangedNotification *DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification `protobuf:"bytes,1,opt,name=remote_device_battery_status_changed_notification,json=remoteDeviceBatteryStatusChangedNotification" json:"remote_device_battery_status_changed_notification,omitempty"`
	RemoteDeviceBatteryStatusRequest             *DeviceStatusService_RemoteDeviceBatteryStatusRequest             `protobuf:"bytes,2,opt,name=remote_device_battery_status_request,json=remoteDeviceBatteryStatusRequest" json:"remote_device_battery_status_request,omitempty"`
	RemoteDeviceBatteryStatusResponse            *DeviceStatusService_RemoteDeviceBatteryStatusResponse            `protobuf:"bytes,3,opt,name=remote_device_battery_status_response,json=remoteDeviceBatteryStatusResponse" json:"remote_device_battery_status_response,omitempty"`
	ActivityStatusRequest                        *DeviceStatusService_ActivityStatusRequest                        `protobuf:"bytes,4,opt,name=activity_status_request,json=activityStatusRequest" json:"activity_status_request,omitempty"`
	ActivityStatusResponse                       *DeviceStatusService_ActivityStatusResponse                       `protobuf:"bytes,5,opt,name=activity_status_response,json=activityStatusResponse" json:"activity_status_response,omitempty"`
	unknownFields                                protoimpl.UnknownFields
	sizeCache                                    protoimpl.SizeCache
}

func (x *DeviceStatusService) Reset() {
	*x = DeviceStatusService{}
	mi := &file_garmin_gdi_device_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusService) ProtoMessage() {}

func (x *DeviceStatusService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_device_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusService.ProtoReflect.Descriptor instead.
func (*DeviceStatusService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceStatusService) GetRemoteDeviceBatteryStatusChangedNotification() *DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification {
	if x != nil {
		return x.RemoteDeviceBatteryStatusChangedNotification
	}
	return nil
}

func (x *DeviceStatusService) GetRemoteDeviceBatteryStatusRequest() *DeviceStatusService_RemoteDeviceBatteryStatusRequest {
	if x != nil {
		return x.RemoteDeviceBatteryStatusRequest
	}
	return nil
}

func (x *DeviceStatusService) GetRemoteDeviceBatteryStatusResponse() *DeviceStatusService_RemoteDeviceBatteryStatusResponse {
	if x != nil {
		return x.RemoteDeviceBatteryStatusResponse
	}
	return nil
}

func (x *DeviceStatusService) GetActivityStatusRequest() *DeviceStatusService_ActivityStatusRequest {
	if x != nil {
		return x.ActivityStatusRequest
	}
	return nil
}

func (x *DeviceStatusService) GetActivityStatusResponse() *DeviceStatusService_ActivityStatusResponse {
	if x != nil {
		return x.ActivityStatusResponse
	}
	return nil
}

type DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification) Reset() {
	*x = DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification{}
	mi := &file_garmin_gdi_device_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification) ProtoMessage() {}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_device_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification.ProtoReflect.Descriptor instead.
func (*DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 0}
}

type DeviceStatusService_RemoteDeviceBatteryStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusRequest) Reset() {
	*x = DeviceStatusService_RemoteDeviceBatteryStatusRequest{}
	mi := &file_garmin_gdi_device_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusService_RemoteDeviceBatteryStatusRequest) ProtoMessage() {}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_device_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusService_RemoteDeviceBatteryStatusRequest.ProtoReflect.Descriptor instead.
func (*DeviceStatusService_RemoteDeviceBatteryStatusRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 1}
}

type DeviceStatusService_RemoteDeviceBatteryStatusResponse struct {
	state               protoimpl.MessageState              `protogen:"open.v1"`
	Status              *DeviceStatusService_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.DeviceStatusService_ResponseStatus" json:"status,omitempty"`
	CurrentBatteryLevel *int32                              `protobuf:"varint,2,opt,name=current_battery_level,json=currentBatteryLevel" json:"current_battery_level,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusResponse) Reset() {
	*x = DeviceStatusService_RemoteDeviceBatteryStatusResponse{}
	mi := &file_garmin_gdi_device_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusService_RemoteDeviceBatteryStatusResponse) ProtoMessage() {}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_device_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusService_RemoteDeviceBatteryStatusResponse.ProtoReflect.Descriptor instead.
func (*DeviceStatusService_RemoteDeviceBatteryStatusResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 2}
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusResponse) GetStatus() DeviceStatusService_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DeviceStatusService_UNKNOWN_RESPONSE_STATUS
}

func (x *DeviceStatusService_RemoteDeviceBatteryStatusResponse) GetCurrentBatteryLevel() int32 {
	if x != nil && x.CurrentBatteryLevel != nil {
		return *x.CurrentBatteryLevel
	}
	return 0
}

type DeviceStatusService_ActivityStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusService_ActivityStatusRequest) Reset() {
	*x = DeviceStatusService_ActivityStatusRequest{}
	mi := &file_garmin_gdi_device_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusService_ActivityStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusService_ActivityStatusRequest) ProtoMessage() {}

func (x *DeviceStatusService_ActivityStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_device_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusService_ActivityStatusRequest.ProtoReflect.Descriptor instead.
func (*DeviceStatusService_ActivityStatusRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 3}
}

type DeviceStatusService_ActivityStatusResponse struct {
	state         protoimpl.MessageState                                     `protogen:"open.v1"`
	Status        *DeviceStatusService_ActivityStatusResponse_ActivityStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.DeviceStatusService_ActivityStatusResponse_ActivityStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatusService_ActivityStatusResponse) Reset() {
	*x = DeviceStatusService_ActivityStatusResponse{}
	mi := &file_garmin_gdi_device_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatusService_ActivityStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatusService_ActivityStatusResponse) ProtoMessage() {}

func (x *DeviceStatusService_ActivityStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_device_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatusService_ActivityStatusResponse.ProtoReflect.Descriptor instead.
func (*DeviceStatusService_ActivityStatusResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_device_status_proto_rawDescGZIP(), []int{0, 4}
}

func (x *DeviceStatusService_ActivityStatusResponse) GetStatus() DeviceStatusService_ActivityStatusResponse_ActivityStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DeviceStatusService_ActivityStatusResponse_OFF
}

var File_garmin_gdi_device_status_proto protoreflect.FileDescriptor

const file_garmin_gdi_device_status_proto_rawDesc = "" +
	"\n" +
	"\x1egarmin/gdi_device_status.proto\x12\x11garmin_vivomovehr\"\x9a\n" +
	"\n" +
	"\x13DeviceStatusService\x12\xbc\x01\n" +
	"1remote_device_battery_status_changed_notification\x18\x01 \x01(\v2S.garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusChangedNotificationR,remoteDeviceBatteryStatusChangedNotification\x12\x97\x01\n" +
	"$remote_device_battery_status_request\x18\x02 \x01(\v2G.garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusRequestR remoteDeviceBatteryStatusRequest\x12\x9a\x01\n" +
	"%remote_device_battery_status_response\x18\x03 \x01(\v2H.garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusResponseR!remoteDeviceBatteryStatusResponse\x12t\n" +
	"\x17activity_status_request\x18\x04 \x01(\v2<.garmin_vivomovehr.DeviceStatusService.ActivityStatusRequestR\x15activityStatusRequest\x12w\n" +
	"\x18activity_status_response\x18\x05 \x01(\v2=.garmin_vivomovehr.DeviceStatusService.ActivityStatusResponseR\x16activityStatusResponse\x1a.\n" +
	",RemoteDeviceBatteryStatusChangedNotification\x1a\"\n" +
	" RemoteDeviceBatteryStatusRequest\x1a\xa6\x01\n" +
	"!RemoteDeviceBatteryStatusResponse\x12M\n" +
	"\x06status\x18\x01 \x01(\x0e25.garmin_vivomovehr.DeviceStatusService.ResponseStatusR\x06status\x122\n" +
	"\x15current_battery_level\x18\x02 \x01(\x05R\x13currentBatteryLevel\x1a\x17\n" +
	"\x15ActivityStatusRequest\x1a\xba\x01\n" +
	"\x16ActivityStatusResponse\x12d\n" +
	"\x06status\x18\x01 \x01(\x0e2L.garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse.ActivityStatusR\x06status\":\n" +
	"\x0eActivityStatus\x12\a\n" +
	"\x03OFF\x10\x00\x12\v\n" +
	"\aSTOPPED\x10\x01\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x02\x12\x06\n" +
	"\x02ON\x10\x03\"K\n" +
	"\x0eResponseStatus\x12\x1b\n" +
	"\x17UNKNOWN_RESPONSE_STATUS\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x14\n" +
	"\x10NO_REMOTE_DEVICE\x10\x02BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_device_status_proto_rawDescOnce sync.Once
	file_garmin_gdi_device_status_proto_rawDescData []byte
)

func file_garmin_gdi_device_status_proto_rawDescGZIP() []byte {
	file_garmin_gdi_device_status_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_device_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_device_status_proto_rawDesc), len(file_garmin_gdi_device_status_proto_rawDesc)))
	})
	return file_garmin_gdi_device_status_proto_rawDescData
}

var file_garmin_gdi_device_status_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_garmin_gdi_device_status_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_garmin_gdi_device_status_proto_goTypes = []any{
	(DeviceStatusService_ResponseStatus)(0),                                  // 0: garmin_vivomovehr.DeviceStatusService.ResponseStatus
	(DeviceStatusService_ActivityStatusResponse_ActivityStatus)(0),           // 1: garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse.ActivityStatus
	(*DeviceStatusService)(nil),                                              // 2: garmin_vivomovehr.DeviceStatusService
	(*DeviceStatusService_RemoteDeviceBatteryStatusChangedNotification)(nil), // 3: garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusChangedNotification
	(*DeviceStatusService_RemoteDeviceBatteryStatusRequest)(nil),             // 4: garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusRequest
	(*DeviceStatusService_RemoteDeviceBatteryStatusResponse)(nil),            // 5: garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusResponse
	(*DeviceStatusService_ActivityStatusRequest)(nil),                        // 6: garmin_vivomovehr.DeviceStatusService.ActivityStatusRequest
	(*DeviceStatusService_ActivityStatusResponse)(nil),                       // 7: garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse
}
var file_garmin_gdi_device_status_proto_depIdxs = []int32{
	3, // 0: garmin_vivomovehr.DeviceStatusService.remote_device_battery_status_changed_notification:type_name -> garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusChangedNotification
	4, // 1: garmin_vivomovehr.DeviceStatusService.remote_device_battery_status_request:type_name -> garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusRequest
	5, // 2: garmin_vivomovehr.DeviceStatusService.remote_device_battery_status_response:type_name -> garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusResponse
	6, // 3: garmin_vivomovehr.DeviceStatusService.activity_status_request:type_name -> garmin_vivomovehr.DeviceStatusService.ActivityStatusRequest
	7, // 4: garmin_vivomovehr.DeviceStatusService.activity_status_response:type_name -> garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse
	0, // 5: garmin_vivomovehr.DeviceStatusService.RemoteDeviceBatteryStatusResponse.status:type_name -> garmin_vivomovehr.DeviceStatusService.ResponseStatus
	1, // 6: garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse.status:type_name -> garmin_vivomovehr.DeviceStatusService.ActivityStatusResponse.ActivityStatus
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_garmin_gdi_device_status_proto_init() }
func file_garmin_gdi_device_status_proto_init() {
	if File_garmin_gdi_device_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_device_status_proto_rawDesc), len(file_garmin_gdi_device_status_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_device_status_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_device_status_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_device_status_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_device_status_proto_msgTypes,
	}.Build()
	File_garmin_gdi_device_status_proto = out.File
	file_garmin_gdi_device_status_proto_goTypes = nil
	file_garmin_gdi_device_status_proto_depIdxs = nil
}
