// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_app_config_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AppConfigService struct {
	state              protoimpl.MessageState           `protogen:"open.v1"`
	AppConfigGet       *AppConfigService_AppConfig      `protobuf:"bytes,1,opt,name=appConfigGet" json:"appConfigGet,omitempty"`
	AppConfigGetStatus *AppConfigServiceAppConfigStatus `protobuf:"bytes,2,opt,name=appConfigGetStatus" json:"appConfigGetStatus,omitempty"`
	AppConfigSet       *AppConfigService_AppConfig      `protobuf:"bytes,3,opt,name=appConfigSet" json:"appConfigSet,omitempty"`
	AppConfigSetStatus *AppConfigServiceAppConfigStatus `protobuf:"bytes,4,opt,name=appConfigSetStatus" json:"appConfigSetStatus,omitempty"`
	AppConfigRet       *AppConfigService_AppConfig      `protobuf:"bytes,5,opt,name=appConfigRet" json:"appConfigRet,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AppConfigService) Reset() {
	*x = AppConfigService{}
	mi := &file_garmin_gdi_app_config_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfigService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfigService) ProtoMessage() {}

func (x *AppConfigService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_app_config_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfigService.ProtoReflect.Descriptor instead.
func (*AppConfigService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_app_config_service_proto_rawDescGZIP(), []int{0}
}

func (x *AppConfigService) GetAppConfigGet() *AppConfigService_AppConfig {
	if x != nil {
		return x.AppConfigGet
	}
	return nil
}

func (x *AppConfigService) GetAppConfigGetStatus() *AppConfigServiceAppConfigStatus {
	if x != nil {
		return x.AppConfigGetStatus
	}
	return nil
}

func (x *AppConfigService) GetAppConfigSet() *AppConfigService_AppConfig {
	if x != nil {
		return x.AppConfigSet
	}
	return nil
}

func (x *AppConfigService) GetAppConfigSetStatus() *AppConfigServiceAppConfigStatus {
	if x != nil {
		return x.AppConfigSetStatus
	}
	return nil
}

func (x *AppConfigService) GetAppConfigRet() *AppConfigService_AppConfig {
	if x != nil {
		return x.AppConfigRet
	}
	return nil
}

type AppConfigServiceAppConfigStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         []byte                 `protobuf:"bytes,1,req,name=appId" json:"appId,omitempty"`
	Status        *uint32                `protobuf:"varint,2,opt,name=status" json:"status,omitempty"` // 1 if it has settings / set was success, 2 app not installed / does not have settings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfigServiceAppConfigStatus) Reset() {
	*x = AppConfigServiceAppConfigStatus{}
	mi := &file_garmin_gdi_app_config_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfigServiceAppConfigStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfigServiceAppConfigStatus) ProtoMessage() {}

func (x *AppConfigServiceAppConfigStatus) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_app_config_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfigServiceAppConfigStatus.ProtoReflect.Descriptor instead.
func (*AppConfigServiceAppConfigStatus) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_app_config_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *AppConfigServiceAppConfigStatus) GetAppId() []byte {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *AppConfigServiceAppConfigStatus) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

type AppConfigService_AppConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         []byte                 `protobuf:"bytes,1,req,name=appId" json:"appId,omitempty"`
	AppConfig     []byte                 `protobuf:"bytes,2,opt,name=appConfig" json:"appConfig,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppConfigService_AppConfig) Reset() {
	*x = AppConfigService_AppConfig{}
	mi := &file_garmin_gdi_app_config_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppConfigService_AppConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppConfigService_AppConfig) ProtoMessage() {}

func (x *AppConfigService_AppConfig) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_app_config_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppConfigService_AppConfig.ProtoReflect.Descriptor instead.
func (*AppConfigService_AppConfig) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_app_config_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *AppConfigService_AppConfig) GetAppId() []byte {
	if x != nil {
		return x.AppId
	}
	return nil
}

func (x *AppConfigService_AppConfig) GetAppConfig() []byte {
	if x != nil {
		return x.AppConfig
	}
	return nil
}

var File_garmin_gdi_app_config_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_app_config_service_proto_rawDesc = "" +
	"\n" +
	"#garmin/gdi_app_config_service.proto\x12\x11garmin_vivomovehr\"\xd7\x04\n" +
	"\x10AppConfigService\x12Q\n" +
	"\fappConfigGet\x18\x01 \x01(\v2-.garmin_vivomovehr.AppConfigService.AppConfigR\fappConfigGet\x12c\n" +
	"\x12appConfigGetStatus\x18\x02 \x01(\v23.garmin_vivomovehr.AppConfigService.appConfigStatusR\x12appConfigGetStatus\x12Q\n" +
	"\fappConfigSet\x18\x03 \x01(\v2-.garmin_vivomovehr.AppConfigService.AppConfigR\fappConfigSet\x12c\n" +
	"\x12appConfigSetStatus\x18\x04 \x01(\v23.garmin_vivomovehr.AppConfigService.appConfigStatusR\x12appConfigSetStatus\x12Q\n" +
	"\fappConfigRet\x18\x05 \x01(\v2-.garmin_vivomovehr.AppConfigService.AppConfigR\fappConfigRet\x1a?\n" +
	"\x0fappConfigStatus\x12\x14\n" +
	"\x05appId\x18\x01 \x02(\fR\x05appId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\x1a?\n" +
	"\tAppConfig\x12\x14\n" +
	"\x05appId\x18\x01 \x02(\fR\x05appId\x12\x1c\n" +
	"\tappConfig\x18\x02 \x01(\fR\tappConfigBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_app_config_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_app_config_service_proto_rawDescData []byte
)

func file_garmin_gdi_app_config_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_app_config_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_app_config_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_app_config_service_proto_rawDesc), len(file_garmin_gdi_app_config_service_proto_rawDesc)))
	})
	return file_garmin_gdi_app_config_service_proto_rawDescData
}

var file_garmin_gdi_app_config_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_garmin_gdi_app_config_service_proto_goTypes = []any{
	(*AppConfigService)(nil),                // 0: garmin_vivomovehr.AppConfigService
	(*AppConfigServiceAppConfigStatus)(nil), // 1: garmin_vivomovehr.AppConfigService.appConfigStatus
	(*AppConfigService_AppConfig)(nil),      // 2: garmin_vivomovehr.AppConfigService.AppConfig
}
var file_garmin_gdi_app_config_service_proto_depIdxs = []int32{
	2, // 0: garmin_vivomovehr.AppConfigService.appConfigGet:type_name -> garmin_vivomovehr.AppConfigService.AppConfig
	1, // 1: garmin_vivomovehr.AppConfigService.appConfigGetStatus:type_name -> garmin_vivomovehr.AppConfigService.appConfigStatus
	2, // 2: garmin_vivomovehr.AppConfigService.appConfigSet:type_name -> garmin_vivomovehr.AppConfigService.AppConfig
	1, // 3: garmin_vivomovehr.AppConfigService.appConfigSetStatus:type_name -> garmin_vivomovehr.AppConfigService.appConfigStatus
	2, // 4: garmin_vivomovehr.AppConfigService.appConfigRet:type_name -> garmin_vivomovehr.AppConfigService.AppConfig
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_garmin_gdi_app_config_service_proto_init() }
func file_garmin_gdi_app_config_service_proto_init() {
	if File_garmin_gdi_app_config_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_app_config_service_proto_rawDesc), len(file_garmin_gdi_app_config_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_app_config_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_app_config_service_proto_depIdxs,
		MessageInfos:      file_garmin_gdi_app_config_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_app_config_service_proto = out.File
	file_garmin_gdi_app_config_service_proto_goTypes = nil
	file_garmin_gdi_app_config_service_proto_depIdxs = nil
}
