// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_find_my_watch.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindMyWatchService_ResponseStatus int32

const (
	FindMyWatchService_UNKNOWN_RESPONSE_STATUS FindMyWatchService_ResponseStatus = 0
	FindMyWatchService_OK                      FindMyWatchService_ResponseStatus = 100
	FindMyWatchService_ERROR                   FindMyWatchService_ResponseStatus = 200
)

// Enum value maps for FindMyWatchService_ResponseStatus.
var (
	FindMyWatchService_ResponseStatus_name = map[int32]string{
		0:   "UNKNOWN_RESPONSE_STATUS",
		100: "OK",
		200: "ERROR",
	}
	FindMyWatchService_ResponseStatus_value = map[string]int32{
		"UNKNOWN_RESPONSE_STATUS": 0,
		"OK":                      100,
		"ERROR":                   200,
	}
)

func (x FindMyWatchService_ResponseStatus) Enum() *FindMyWatchService_ResponseStatus {
	p := new(FindMyWatchService_ResponseStatus)
	*p = x
	return p
}

func (x FindMyWatchService_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FindMyWatchService_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_find_my_watch_proto_enumTypes[0].Descriptor()
}

func (FindMyWatchService_ResponseStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_find_my_watch_proto_enumTypes[0]
}

func (x FindMyWatchService_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *FindMyWatchService_ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = FindMyWatchService_ResponseStatus(num)
	return nil
}

// Deprecated: Use FindMyWatchService_ResponseStatus.Descriptor instead.
func (FindMyWatchService_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_find_my_watch_proto_rawDescGZIP(), []int{0, 0}
}

type FindMyWatchService struct {
	state          protoimpl.MessageState                        `protogen:"open.v1"`
	FindRequest    *FindMyWatchService_FindMyWatchRequest        `protobuf:"bytes,1,opt,name=find_request,json=findRequest" json:"find_request,omitempty"`
	FindResponse   *FindMyWatchService_FindMyWatchResponse       `protobuf:"bytes,2,opt,name=find_response,json=findResponse" json:"find_response,omitempty"`
	CancelRequest  *FindMyWatchService_FindMyWatchCancelRequest  `protobuf:"bytes,3,opt,name=cancel_request,json=cancelRequest" json:"cancel_request,omitempty"`
	CancelResponse *FindMyWatchService_FindMyWatchCancelResponse `protobuf:"bytes,4,opt,name=cancel_response,json=cancelResponse" json:"cancel_response,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindMyWatchService) Reset() {
	*x = FindMyWatchService{}
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMyWatchService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMyWatchService) ProtoMessage() {}

func (x *FindMyWatchService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMyWatchService.ProtoReflect.Descriptor instead.
func (*FindMyWatchService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_find_my_watch_proto_rawDescGZIP(), []int{0}
}

func (x *FindMyWatchService) GetFindRequest() *FindMyWatchService_FindMyWatchRequest {
	if x != nil {
		return x.FindRequest
	}
	return nil
}

func (x *FindMyWatchService) GetFindResponse() *FindMyWatchService_FindMyWatchResponse {
	if x != nil {
		return x.FindResponse
	}
	return nil
}

func (x *FindMyWatchService) GetCancelRequest() *FindMyWatchService_FindMyWatchCancelRequest {
	if x != nil {
		return x.CancelRequest
	}
	return nil
}

func (x *FindMyWatchService) GetCancelResponse() *FindMyWatchService_FindMyWatchCancelResponse {
	if x != nil {
		return x.CancelResponse
	}
	return nil
}

type FindMyWatchService_FindMyWatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timeout       *int32                 `protobuf:"varint,1,req,name=timeout" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMyWatchService_FindMyWatchRequest) Reset() {
	*x = FindMyWatchService_FindMyWatchRequest{}
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMyWatchService_FindMyWatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMyWatchService_FindMyWatchRequest) ProtoMessage() {}

func (x *FindMyWatchService_FindMyWatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMyWatchService_FindMyWatchRequest.ProtoReflect.Descriptor instead.
func (*FindMyWatchService_FindMyWatchRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_find_my_watch_proto_rawDescGZIP(), []int{0, 0}
}

func (x *FindMyWatchService_FindMyWatchRequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

type FindMyWatchService_FindMyWatchResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        *FindMyWatchService_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.FindMyWatchService_ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMyWatchService_FindMyWatchResponse) Reset() {
	*x = FindMyWatchService_FindMyWatchResponse{}
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMyWatchService_FindMyWatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMyWatchService_FindMyWatchResponse) ProtoMessage() {}

func (x *FindMyWatchService_FindMyWatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMyWatchService_FindMyWatchResponse.ProtoReflect.Descriptor instead.
func (*FindMyWatchService_FindMyWatchResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_find_my_watch_proto_rawDescGZIP(), []int{0, 1}
}

func (x *FindMyWatchService_FindMyWatchResponse) GetStatus() FindMyWatchService_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return FindMyWatchService_UNKNOWN_RESPONSE_STATUS
}

type FindMyWatchService_FindMyWatchCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMyWatchService_FindMyWatchCancelRequest) Reset() {
	*x = FindMyWatchService_FindMyWatchCancelRequest{}
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMyWatchService_FindMyWatchCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMyWatchService_FindMyWatchCancelRequest) ProtoMessage() {}

func (x *FindMyWatchService_FindMyWatchCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMyWatchService_FindMyWatchCancelRequest.ProtoReflect.Descriptor instead.
func (*FindMyWatchService_FindMyWatchCancelRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_find_my_watch_proto_rawDescGZIP(), []int{0, 2}
}

type FindMyWatchService_FindMyWatchCancelResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Status        *FindMyWatchService_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.FindMyWatchService_ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindMyWatchService_FindMyWatchCancelResponse) Reset() {
	*x = FindMyWatchService_FindMyWatchCancelResponse{}
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindMyWatchService_FindMyWatchCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindMyWatchService_FindMyWatchCancelResponse) ProtoMessage() {}

func (x *FindMyWatchService_FindMyWatchCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_find_my_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindMyWatchService_FindMyWatchCancelResponse.ProtoReflect.Descriptor instead.
func (*FindMyWatchService_FindMyWatchCancelResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_find_my_watch_proto_rawDescGZIP(), []int{0, 3}
}

func (x *FindMyWatchService_FindMyWatchCancelResponse) GetStatus() FindMyWatchService_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return FindMyWatchService_UNKNOWN_RESPONSE_STATUS
}

var File_garmin_gdi_find_my_watch_proto protoreflect.FileDescriptor

const file_garmin_gdi_find_my_watch_proto_rawDesc = "" +
	"\n" +
	"\x1egarmin/gdi_find_my_watch.proto\x12\x11garmin_vivomovehr\"\x81\x06\n" +
	"\x12FindMyWatchService\x12[\n" +
	"\ffind_request\x18\x01 \x01(\v28.garmin_vivomovehr.FindMyWatchService.FindMyWatchRequestR\vfindRequest\x12^\n" +
	"\rfind_response\x18\x02 \x01(\v29.garmin_vivomovehr.FindMyWatchService.FindMyWatchResponseR\ffindResponse\x12e\n" +
	"\x0ecancel_request\x18\x03 \x01(\v2>.garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelRequestR\rcancelRequest\x12h\n" +
	"\x0fcancel_response\x18\x04 \x01(\v2?.garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelResponseR\x0ecancelResponse\x1a.\n" +
	"\x12FindMyWatchRequest\x12\x18\n" +
	"\atimeout\x18\x01 \x02(\x05R\atimeout\x1ac\n" +
	"\x13FindMyWatchResponse\x12L\n" +
	"\x06status\x18\x01 \x01(\x0e24.garmin_vivomovehr.FindMyWatchService.ResponseStatusR\x06status\x1a\x1a\n" +
	"\x18FindMyWatchCancelRequest\x1ai\n" +
	"\x19FindMyWatchCancelResponse\x12L\n" +
	"\x06status\x18\x01 \x01(\x0e24.garmin_vivomovehr.FindMyWatchService.ResponseStatusR\x06status\"A\n" +
	"\x0eResponseStatus\x12\x1b\n" +
	"\x17UNKNOWN_RESPONSE_STATUS\x10\x00\x12\x06\n" +
	"\x02OK\x10d\x12\n" +
	"\n" +
	"\x05ERROR\x10\xc8\x01BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_find_my_watch_proto_rawDescOnce sync.Once
	file_garmin_gdi_find_my_watch_proto_rawDescData []byte
)

func file_garmin_gdi_find_my_watch_proto_rawDescGZIP() []byte {
	file_garmin_gdi_find_my_watch_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_find_my_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_find_my_watch_proto_rawDesc), len(file_garmin_gdi_find_my_watch_proto_rawDesc)))
	})
	return file_garmin_gdi_find_my_watch_proto_rawDescData
}

var file_garmin_gdi_find_my_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_garmin_gdi_find_my_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_garmin_gdi_find_my_watch_proto_goTypes = []any{
	(FindMyWatchService_ResponseStatus)(0),               // 0: garmin_vivomovehr.FindMyWatchService.ResponseStatus
	(*FindMyWatchService)(nil),                           // 1: garmin_vivomovehr.FindMyWatchService
	(*FindMyWatchService_FindMyWatchRequest)(nil),        // 2: garmin_vivomovehr.FindMyWatchService.FindMyWatchRequest
	(*FindMyWatchService_FindMyWatchResponse)(nil),       // 3: garmin_vivomovehr.FindMyWatchService.FindMyWatchResponse
	(*FindMyWatchService_FindMyWatchCancelRequest)(nil),  // 4: garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelRequest
	(*FindMyWatchService_FindMyWatchCancelResponse)(nil), // 5: garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelResponse
}
var file_garmin_gdi_find_my_watch_proto_depIdxs = []int32{
	2, // 0: garmin_vivomovehr.FindMyWatchService.find_request:type_name -> garmin_vivomovehr.FindMyWatchService.FindMyWatchRequest
	3, // 1: garmin_vivomovehr.FindMyWatchService.find_response:type_name -> garmin_vivomovehr.FindMyWatchService.FindMyWatchResponse
	4, // 2: garmin_vivomovehr.FindMyWatchService.cancel_request:type_name -> garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelRequest
	5, // 3: garmin_vivomovehr.FindMyWatchService.cancel_response:type_name -> garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelResponse
	0, // 4: garmin_vivomovehr.FindMyWatchService.FindMyWatchResponse.status:type_name -> garmin_vivomovehr.FindMyWatchService.ResponseStatus
	0, // 5: garmin_vivomovehr.FindMyWatchService.FindMyWatchCancelResponse.status:type_name -> garmin_vivomovehr.FindMyWatchService.ResponseStatus
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_garmin_gdi_find_my_watch_proto_init() }
func file_garmin_gdi_find_my_watch_proto_init() {
	if File_garmin_gdi_find_my_watch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_find_my_watch_proto_rawDesc), len(file_garmin_gdi_find_my_watch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_find_my_watch_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_find_my_watch_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_find_my_watch_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_find_my_watch_proto_msgTypes,
	}.Build()
	File_garmin_gdi_find_my_watch_proto = out.File
	file_garmin_gdi_find_my_watch_proto_goTypes = nil
	file_garmin_gdi_find_my_watch_proto_depIdxs = nil
}
