// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_smart_proto.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Smart struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	CalendarService        *CalendarService        `protobuf:"bytes,1,opt,name=calendar_service,json=calendarService" json:"calendar_service,omitempty"`
	HttpService            *HttpService            `protobuf:"bytes,2,opt,name=http_service,json=httpService" json:"http_service,omitempty"`
	AppConfigService       *AppConfigService       `protobuf:"bytes,4,opt,name=app_config_service,json=appConfigService" json:"app_config_service,omitempty"`
	InstalledAppsService   *InstalledAppsService   `protobuf:"bytes,3,opt,name=installed_apps_service,json=installedAppsService" json:"installed_apps_service,omitempty"`
	DataTransferService    *DataTransferService    `protobuf:"bytes,7,opt,name=data_transfer_service,json=dataTransferService" json:"data_transfer_service,omitempty"`
	DeviceStatusService    *DeviceStatusService    `protobuf:"bytes,8,opt,name=device_status_service,json=deviceStatusService" json:"device_status_service,omitempty"`
	FindMyWatchService     *FindMyWatchService     `protobuf:"bytes,12,opt,name=find_my_watch_service,json=findMyWatchService" json:"find_my_watch_service,omitempty"`
	CoreService            *CoreService            `protobuf:"bytes,13,opt,name=core_service,json=coreService" json:"core_service,omitempty"`
	SmsNotificationService *SmsNotificationService `protobuf:"bytes,16,opt,name=sms_notification_service,json=smsNotificationService" json:"sms_notification_service,omitempty"`
	AuthenticationService  *AuthenticationService  `protobuf:"bytes,27,opt,name=authenticationService" json:"authenticationService,omitempty"`
	ExploreSyncService     *ExploreSyncService     `protobuf:"bytes,22,opt,name=explore_sync_service,json=exploreSyncService" json:"explore_sync_service,omitempty"`
	EcgService             *EcgService             `protobuf:"bytes,39,opt,name=ecg_service,json=ecgService" json:"ecg_service,omitempty"`
	SettingsService        *SettingsService        `protobuf:"bytes,42,opt,name=settings_service,json=settingsService" json:"settings_service,omitempty"`
	FileSyncService        *FileSyncService        `protobuf:"bytes,43,opt,name=file_sync_service,json=fileSyncService" json:"file_sync_service,omitempty"`
	NotificationsService   *NotificationsService   `protobuf:"bytes,49,opt,name=notifications_service,json=notificationsService" json:"notifications_service,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Smart) Reset() {
	*x = Smart{}
	mi := &file_garmin_gdi_smart_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Smart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Smart) ProtoMessage() {}

func (x *Smart) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_smart_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Smart.ProtoReflect.Descriptor instead.
func (*Smart) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_smart_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Smart) GetCalendarService() *CalendarService {
	if x != nil {
		return x.CalendarService
	}
	return nil
}

func (x *Smart) GetHttpService() *HttpService {
	if x != nil {
		return x.HttpService
	}
	return nil
}

func (x *Smart) GetAppConfigService() *AppConfigService {
	if x != nil {
		return x.AppConfigService
	}
	return nil
}

func (x *Smart) GetInstalledAppsService() *InstalledAppsService {
	if x != nil {
		return x.InstalledAppsService
	}
	return nil
}

func (x *Smart) GetDataTransferService() *DataTransferService {
	if x != nil {
		return x.DataTransferService
	}
	return nil
}

func (x *Smart) GetDeviceStatusService() *DeviceStatusService {
	if x != nil {
		return x.DeviceStatusService
	}
	return nil
}

func (x *Smart) GetFindMyWatchService() *FindMyWatchService {
	if x != nil {
		return x.FindMyWatchService
	}
	return nil
}

func (x *Smart) GetCoreService() *CoreService {
	if x != nil {
		return x.CoreService
	}
	return nil
}

func (x *Smart) GetSmsNotificationService() *SmsNotificationService {
	if x != nil {
		return x.SmsNotificationService
	}
	return nil
}

func (x *Smart) GetAuthenticationService() *AuthenticationService {
	if x != nil {
		return x.AuthenticationService
	}
	return nil
}

func (x *Smart) GetExploreSyncService() *ExploreSyncService {
	if x != nil {
		return x.ExploreSyncService
	}
	return nil
}

func (x *Smart) GetEcgService() *EcgService {
	if x != nil {
		return x.EcgService
	}
	return nil
}

func (x *Smart) GetSettingsService() *SettingsService {
	if x != nil {
		return x.SettingsService
	}
	return nil
}

func (x *Smart) GetFileSyncService() *FileSyncService {
	if x != nil {
		return x.FileSyncService
	}
	return nil
}

func (x *Smart) GetNotificationsService() *NotificationsService {
	if x != nil {
		return x.NotificationsService
	}
	return nil
}

var File_garmin_gdi_smart_proto_proto protoreflect.FileDescriptor

const file_garmin_gdi_smart_proto_proto_rawDesc = "" +
	"\n" +
	"\x1cgarmin/gdi_smart_proto.proto\x12\x11garmin_vivomovehr\x1a'garmin/gdi_authentication_service.proto\x1a\x1egarmin/gdi_device_status.proto\x1a\"garmin/gdi_file_sync_service.proto\x1a\x1egarmin/gdi_find_my_watch.proto\x1a\x15garmin/gdi_core.proto\x1a\x1dgarmin/gdi_http_service.proto\x1a#garmin/gdi_app_config_service.proto\x1a'garmin/gdi_installed_apps_service.proto\x1a&garmin/gdi_data_transfer_service.proto\x1a!garmin/gdi_sms_notification.proto\x1a!garmin/gdi_calendar_service.proto\x1a!garmin/gdi_settings_service.proto\x1a&garmin/gdi_notifications_service.proto\x1a\x1cgarmin/gdi_ecg_service.proto\x1a\x1dgarmin/gdi_explore_sync.proto\"\xfb\t\n" +
	"\x05Smart\x12M\n" +
	"\x10calendar_service\x18\x01 \x01(\v2\".garmin_vivomovehr.CalendarServiceR\x0fcalendarService\x12A\n" +
	"\fhttp_service\x18\x02 \x01(\v2\x1e.garmin_vivomovehr.HttpServiceR\vhttpService\x12Q\n" +
	"\x12app_config_service\x18\x04 \x01(\v2#.garmin_vivomovehr.AppConfigServiceR\x10appConfigService\x12]\n" +
	"\x16installed_apps_service\x18\x03 \x01(\v2'.garmin_vivomovehr.InstalledAppsServiceR\x14installedAppsService\x12Z\n" +
	"\x15data_transfer_service\x18\a \x01(\v2&.garmin_vivomovehr.DataTransferServiceR\x13dataTransferService\x12Z\n" +
	"\x15device_status_service\x18\b \x01(\v2&.garmin_vivomovehr.DeviceStatusServiceR\x13deviceStatusService\x12X\n" +
	"\x15find_my_watch_service\x18\f \x01(\v2%.garmin_vivomovehr.FindMyWatchServiceR\x12findMyWatchService\x12A\n" +
	"\fcore_service\x18\r \x01(\v2\x1e.garmin_vivomovehr.CoreServiceR\vcoreService\x12c\n" +
	"\x18sms_notification_service\x18\x10 \x01(\v2).garmin_vivomovehr.SmsNotificationServiceR\x16smsNotificationService\x12^\n" +
	"\x15authenticationService\x18\x1b \x01(\v2(.garmin_vivomovehr.AuthenticationServiceR\x15authenticationService\x12W\n" +
	"\x14explore_sync_service\x18\x16 \x01(\v2%.garmin_vivomovehr.ExploreSyncServiceR\x12exploreSyncService\x12>\n" +
	"\vecg_service\x18' \x01(\v2\x1d.garmin_vivomovehr.EcgServiceR\n" +
	"ecgService\x12M\n" +
	"\x10settings_service\x18* \x01(\v2\".garmin_vivomovehr.SettingsServiceR\x0fsettingsService\x12N\n" +
	"\x11file_sync_service\x18+ \x01(\v2\".garmin_vivomovehr.FileSyncServiceR\x0ffileSyncService\x12\\\n" +
	"\x15notifications_service\x181 \x01(\v2'.garmin_vivomovehr.NotificationsServiceR\x14notificationsServiceBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_smart_proto_proto_rawDescOnce sync.Once
	file_garmin_gdi_smart_proto_proto_rawDescData []byte
)

func file_garmin_gdi_smart_proto_proto_rawDescGZIP() []byte {
	file_garmin_gdi_smart_proto_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_smart_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_smart_proto_proto_rawDesc), len(file_garmin_gdi_smart_proto_proto_rawDesc)))
	})
	return file_garmin_gdi_smart_proto_proto_rawDescData
}

var file_garmin_gdi_smart_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_garmin_gdi_smart_proto_proto_goTypes = []any{
	(*Smart)(nil),                  // 0: garmin_vivomovehr.Smart
	(*CalendarService)(nil),        // 1: garmin_vivomovehr.CalendarService
	(*HttpService)(nil),            // 2: garmin_vivomovehr.HttpService
	(*AppConfigService)(nil),       // 3: garmin_vivomovehr.AppConfigService
	(*InstalledAppsService)(nil),   // 4: garmin_vivomovehr.InstalledAppsService
	(*DataTransferService)(nil),    // 5: garmin_vivomovehr.DataTransferService
	(*DeviceStatusService)(nil),    // 6: garmin_vivomovehr.DeviceStatusService
	(*FindMyWatchService)(nil),     // 7: garmin_vivomovehr.FindMyWatchService
	(*CoreService)(nil),            // 8: garmin_vivomovehr.CoreService
	(*SmsNotificationService)(nil), // 9: garmin_vivomovehr.SmsNotificationService
	(*AuthenticationService)(nil),  // 10: garmin_vivomovehr.AuthenticationService
	(*ExploreSyncService)(nil),     // 11: garmin_vivomovehr.ExploreSyncService
	(*EcgService)(nil),             // 12: garmin_vivomovehr.EcgService
	(*SettingsService)(nil),        // 13: garmin_vivomovehr.SettingsService
	(*FileSyncService)(nil),        // 14: garmin_vivomovehr.FileSyncService
	(*NotificationsService)(nil),   // 15: garmin_vivomovehr.NotificationsService
}
var file_garmin_gdi_smart_proto_proto_depIdxs = []int32{
	1,  // 0: garmin_vivomovehr.Smart.calendar_service:type_name -> garmin_vivomovehr.CalendarService
	2,  // 1: garmin_vivomovehr.Smart.http_service:type_name -> garmin_vivomovehr.HttpService
	3,  // 2: garmin_vivomovehr.Smart.app_config_service:type_name -> garmin_vivomovehr.AppConfigService
	4,  // 3: garmin_vivomovehr.Smart.installed_apps_service:type_name -> garmin_vivomovehr.InstalledAppsService
	5,  // 4: garmin_vivomovehr.Smart.data_transfer_service:type_name -> garmin_vivomovehr.DataTransferService
	6,  // 5: garmin_vivomovehr.Smart.device_status_service:type_name -> garmin_vivomovehr.DeviceStatusService
	7,  // 6: garmin_vivomovehr.Smart.find_my_watch_service:type_name -> garmin_vivomovehr.FindMyWatchService
	8,  // 7: garmin_vivomovehr.Smart.core_service:type_name -> garmin_vivomovehr.CoreService
	9,  // 8: garmin_vivomovehr.Smart.sms_notification_service:type_name -> garmin_vivomovehr.SmsNotificationService
	10, // 9: garmin_vivomovehr.Smart.authenticationService:type_name -> garmin_vivomovehr.AuthenticationService
	11, // 10: garmin_vivomovehr.Smart.explore_sync_service:type_name -> garmin_vivomovehr.ExploreSyncService
	12, // 11: garmin_vivomovehr.Smart.ecg_service:type_name -> garmin_vivomovehr.EcgService
	13, // 12: garmin_vivomovehr.Smart.settings_service:type_name -> garmin_vivomovehr.SettingsService
	14, // 13: garmin_vivomovehr.Smart.file_sync_service:type_name -> garmin_vivomovehr.FileSyncService
	15, // 14: garmin_vivomovehr.Smart.notifications_service:type_name -> garmin_vivomovehr.NotificationsService
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_garmin_gdi_smart_proto_proto_init() }
func file_garmin_gdi_smart_proto_proto_init() {
	if File_garmin_gdi_smart_proto_proto != nil {
		return
	}
	file_garmin_gdi_authentication_service_proto_init()
	file_garmin_gdi_device_status_proto_init()
	file_garmin_gdi_file_sync_service_proto_init()
	file_garmin_gdi_find_my_watch_proto_init()
	file_garmin_gdi_core_proto_init()
	file_garmin_gdi_http_service_proto_init()
	file_garmin_gdi_app_config_service_proto_init()
	file_garmin_gdi_installed_apps_service_proto_init()
	file_garmin_gdi_data_transfer_service_proto_init()
	file_garmin_gdi_sms_notification_proto_init()
	file_garmin_gdi_calendar_service_proto_init()
	file_garmin_gdi_settings_service_proto_init()
	file_garmin_gdi_notifications_service_proto_init()
	file_garmin_gdi_ecg_service_proto_init()
	file_garmin_gdi_explore_sync_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_smart_proto_proto_rawDesc), len(file_garmin_gdi_smart_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_smart_proto_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_smart_proto_proto_depIdxs,
		MessageInfos:      file_garmin_gdi_smart_proto_proto_msgTypes,
	}.Build()
	File_garmin_gdi_smart_proto_proto = out.File
	file_garmin_gdi_smart_proto_proto_goTypes = nil
	file_garmin_gdi_smart_proto_proto_depIdxs = nil
}
