// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_notifications_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationsService struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PictureRequest  *PictureRequest        `protobuf:"bytes,1,opt,name=pictureRequest" json:"pictureRequest,omitempty"`
	PictureResponse *PictureResponse       `protobuf:"bytes,2,opt,name=pictureResponse" json:"pictureResponse,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NotificationsService) Reset() {
	*x = NotificationsService{}
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationsService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationsService) ProtoMessage() {}

func (x *NotificationsService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationsService.ProtoReflect.Descriptor instead.
func (*NotificationsService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_notifications_service_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationsService) GetPictureRequest() *PictureRequest {
	if x != nil {
		return x.PictureRequest
	}
	return nil
}

func (x *NotificationsService) GetPictureResponse() *PictureResponse {
	if x != nil {
		return x.PictureResponse
	}
	return nil
}

type PictureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId *uint32                `protobuf:"varint,1,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
	Unk2           *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"`            // 0
	Parameters     *PictureParameters     `protobuf:"bytes,3,opt,name=parameters" json:"parameters,omitempty"` // unk4 "\001"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PictureRequest) Reset() {
	*x = PictureRequest{}
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PictureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureRequest) ProtoMessage() {}

func (x *PictureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureRequest.ProtoReflect.Descriptor instead.
func (*PictureRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_notifications_service_proto_rawDescGZIP(), []int{1}
}

func (x *PictureRequest) GetNotificationId() uint32 {
	if x != nil && x.NotificationId != nil {
		return *x.NotificationId
	}
	return 0
}

func (x *PictureRequest) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *PictureRequest) GetParameters() *PictureParameters {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type PictureParameters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         *uint32                `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height        *uint32                `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"`       // 204800 max size?
	Quality       *uint32                `protobuf:"varint,4,opt,name=quality" json:"quality,omitempty"` // 80
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PictureParameters) Reset() {
	*x = PictureParameters{}
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PictureParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureParameters) ProtoMessage() {}

func (x *PictureParameters) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureParameters.ProtoReflect.Descriptor instead.
func (*PictureParameters) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_notifications_service_proto_rawDescGZIP(), []int{2}
}

func (x *PictureParameters) GetWidth() uint32 {
	if x != nil && x.Width != nil {
		return *x.Width
	}
	return 0
}

func (x *PictureParameters) GetHeight() uint32 {
	if x != nil && x.Height != nil {
		return *x.Height
	}
	return 0
}

func (x *PictureParameters) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *PictureParameters) GetQuality() uint32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return 0
}

type PictureResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Unk1             *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 1
	NotificationId   *uint32                `protobuf:"varint,2,opt,name=notification_id,json=notificationId" json:"notification_id,omitempty"`
	Unk3             *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 0
	Unk4             *uint32                `protobuf:"varint,4,opt,name=unk4" json:"unk4,omitempty"` // 1
	DataTransferItem *DataTransferItem      `protobuf:"bytes,5,opt,name=dataTransferItem" json:"dataTransferItem,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PictureResponse) Reset() {
	*x = PictureResponse{}
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PictureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PictureResponse) ProtoMessage() {}

func (x *PictureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PictureResponse.ProtoReflect.Descriptor instead.
func (*PictureResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_notifications_service_proto_rawDescGZIP(), []int{3}
}

func (x *PictureResponse) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

func (x *PictureResponse) GetNotificationId() uint32 {
	if x != nil && x.NotificationId != nil {
		return *x.NotificationId
	}
	return 0
}

func (x *PictureResponse) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *PictureResponse) GetUnk4() uint32 {
	if x != nil && x.Unk4 != nil {
		return *x.Unk4
	}
	return 0
}

func (x *PictureResponse) GetDataTransferItem() *DataTransferItem {
	if x != nil {
		return x.DataTransferItem
	}
	return nil
}

type DataTransferItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Size          *uint32                `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTransferItem) Reset() {
	*x = DataTransferItem{}
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTransferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransferItem) ProtoMessage() {}

func (x *DataTransferItem) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_notifications_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransferItem.ProtoReflect.Descriptor instead.
func (*DataTransferItem) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_notifications_service_proto_rawDescGZIP(), []int{4}
}

func (x *DataTransferItem) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DataTransferItem) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

var File_garmin_gdi_notifications_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_notifications_service_proto_rawDesc = "" +
	"\n" +
	"&garmin/gdi_notifications_service.proto\x12\x11garmin_vivomovehr\"\xaf\x01\n" +
	"\x14NotificationsService\x12I\n" +
	"\x0epictureRequest\x18\x01 \x01(\v2!.garmin_vivomovehr.PictureRequestR\x0epictureRequest\x12L\n" +
	"\x0fpictureResponse\x18\x02 \x01(\v2\".garmin_vivomovehr.PictureResponseR\x0fpictureResponse\"\x93\x01\n" +
	"\x0ePictureRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\rR\x0enotificationId\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12D\n" +
	"\n" +
	"parameters\x18\x03 \x01(\v2$.garmin_vivomovehr.PictureParametersR\n" +
	"parameters\"o\n" +
	"\x11PictureParameters\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12\x18\n" +
	"\aquality\x18\x04 \x01(\rR\aquality\"\xc7\x01\n" +
	"\x0fPictureResponse\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\rR\x0enotificationId\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12\x12\n" +
	"\x04unk4\x18\x04 \x01(\rR\x04unk4\x12O\n" +
	"\x10dataTransferItem\x18\x05 \x01(\v2#.garmin_vivomovehr.DataTransferItemR\x10dataTransferItem\"6\n" +
	"\x10DataTransferItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04sizeBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_notifications_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_notifications_service_proto_rawDescData []byte
)

func file_garmin_gdi_notifications_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_notifications_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_notifications_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_notifications_service_proto_rawDesc), len(file_garmin_gdi_notifications_service_proto_rawDesc)))
	})
	return file_garmin_gdi_notifications_service_proto_rawDescData
}

var file_garmin_gdi_notifications_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_garmin_gdi_notifications_service_proto_goTypes = []any{
	(*NotificationsService)(nil), // 0: garmin_vivomovehr.NotificationsService
	(*PictureRequest)(nil),       // 1: garmin_vivomovehr.PictureRequest
	(*PictureParameters)(nil),    // 2: garmin_vivomovehr.PictureParameters
	(*PictureResponse)(nil),      // 3: garmin_vivomovehr.PictureResponse
	(*DataTransferItem)(nil),     // 4: garmin_vivomovehr.DataTransferItem
}
var file_garmin_gdi_notifications_service_proto_depIdxs = []int32{
	1, // 0: garmin_vivomovehr.NotificationsService.pictureRequest:type_name -> garmin_vivomovehr.PictureRequest
	3, // 1: garmin_vivomovehr.NotificationsService.pictureResponse:type_name -> garmin_vivomovehr.PictureResponse
	2, // 2: garmin_vivomovehr.PictureRequest.parameters:type_name -> garmin_vivomovehr.PictureParameters
	4, // 3: garmin_vivomovehr.PictureResponse.dataTransferItem:type_name -> garmin_vivomovehr.DataTransferItem
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_garmin_gdi_notifications_service_proto_init() }
func file_garmin_gdi_notifications_service_proto_init() {
	if File_garmin_gdi_notifications_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_notifications_service_proto_rawDesc), len(file_garmin_gdi_notifications_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_notifications_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_notifications_service_proto_depIdxs,
		MessageInfos:      file_garmin_gdi_notifications_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_notifications_service_proto = out.File
	file_garmin_gdi_notifications_service_proto_goTypes = nil
	file_garmin_gdi_notifications_service_proto_depIdxs = nil
}
