// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_http_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpService_Method int32

const (
	HttpService_UNKNOWN_METHOD HttpService_Method = 0
	HttpService_GET            HttpService_Method = 1
	HttpService_PUT            HttpService_Method = 2
	HttpService_POST           HttpService_Method = 3
	HttpService_DELETE         HttpService_Method = 4
	HttpService_PATCH          HttpService_Method = 5
	HttpService_HEAD           HttpService_Method = 6
)

// Enum value maps for HttpService_Method.
var (
	HttpService_Method_name = map[int32]string{
		0: "UNKNOWN_METHOD",
		1: "GET",
		2: "PUT",
		3: "POST",
		4: "DELETE",
		5: "PATCH",
		6: "HEAD",
	}
	HttpService_Method_value = map[string]int32{
		"UNKNOWN_METHOD": 0,
		"GET":            1,
		"PUT":            2,
		"POST":           3,
		"DELETE":         4,
		"PATCH":          5,
		"HEAD":           6,
	}
)

func (x HttpService_Method) Enum() *HttpService_Method {
	p := new(HttpService_Method)
	*p = x
	return p
}

func (x HttpService_Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpService_Method) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_http_service_proto_enumTypes[0].Descriptor()
}

func (HttpService_Method) Type() protoreflect.EnumType {
	return &file_garmin_gdi_http_service_proto_enumTypes[0]
}

func (x HttpService_Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HttpService_Method) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HttpService_Method(num)
	return nil
}

// Deprecated: Use HttpService_Method.Descriptor instead.
func (HttpService_Method) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 0}
}

type HttpService_Status int32

const (
	HttpService_UNKNOWN_STATUS             HttpService_Status = 0
	HttpService_OK                         HttpService_Status = 100
	HttpService_NETWORK_REQUEST_TIMED_OUT  HttpService_Status = 200
	HttpService_FILE_TOO_LARGE             HttpService_Status = 300
	HttpService_DATA_TRANSFER_ITEM_FAILURE HttpService_Status = 400
)

// Enum value maps for HttpService_Status.
var (
	HttpService_Status_name = map[int32]string{
		0:   "UNKNOWN_STATUS",
		100: "OK",
		200: "NETWORK_REQUEST_TIMED_OUT",
		300: "FILE_TOO_LARGE",
		400: "DATA_TRANSFER_ITEM_FAILURE",
	}
	HttpService_Status_value = map[string]int32{
		"UNKNOWN_STATUS":             0,
		"OK":                         100,
		"NETWORK_REQUEST_TIMED_OUT":  200,
		"FILE_TOO_LARGE":             300,
		"DATA_TRANSFER_ITEM_FAILURE": 400,
	}
)

func (x HttpService_Status) Enum() *HttpService_Status {
	p := new(HttpService_Status)
	*p = x
	return p
}

func (x HttpService_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpService_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_http_service_proto_enumTypes[1].Descriptor()
}

func (HttpService_Status) Type() protoreflect.EnumType {
	return &file_garmin_gdi_http_service_proto_enumTypes[1]
}

func (x HttpService_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HttpService_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HttpService_Status(num)
	return nil
}

// Deprecated: Use HttpService_Status.Descriptor instead.
func (HttpService_Status) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 1}
}

type HttpService_ResponseType int32

const (
	HttpService_JSON        HttpService_ResponseType = 0
	HttpService_URL_ENCODED HttpService_ResponseType = 1
	HttpService_PLAIN_TEXT  HttpService_ResponseType = 2
	HttpService_XML         HttpService_ResponseType = 3
)

// Enum value maps for HttpService_ResponseType.
var (
	HttpService_ResponseType_name = map[int32]string{
		0: "JSON",
		1: "URL_ENCODED",
		2: "PLAIN_TEXT",
		3: "XML",
	}
	HttpService_ResponseType_value = map[string]int32{
		"JSON":        0,
		"URL_ENCODED": 1,
		"PLAIN_TEXT":  2,
		"XML":         3,
	}
)

func (x HttpService_ResponseType) Enum() *HttpService_ResponseType {
	p := new(HttpService_ResponseType)
	*p = x
	return p
}

func (x HttpService_ResponseType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpService_ResponseType) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_http_service_proto_enumTypes[2].Descriptor()
}

func (HttpService_ResponseType) Type() protoreflect.EnumType {
	return &file_garmin_gdi_http_service_proto_enumTypes[2]
}

func (x HttpService_ResponseType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HttpService_ResponseType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HttpService_ResponseType(num)
	return nil
}

// Deprecated: Use HttpService_ResponseType.Descriptor instead.
func (HttpService_ResponseType) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 2}
}

type HttpService_Version int32

const (
	HttpService_VERSION_1 HttpService_Version = 0
	HttpService_VERSION_2 HttpService_Version = 1
)

// Enum value maps for HttpService_Version.
var (
	HttpService_Version_name = map[int32]string{
		0: "VERSION_1",
		1: "VERSION_2",
	}
	HttpService_Version_value = map[string]int32{
		"VERSION_1": 0,
		"VERSION_2": 1,
	}
)

func (x HttpService_Version) Enum() *HttpService_Version {
	p := new(HttpService_Version)
	*p = x
	return p
}

func (x HttpService_Version) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpService_Version) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_http_service_proto_enumTypes[3].Descriptor()
}

func (HttpService_Version) Type() protoreflect.EnumType {
	return &file_garmin_gdi_http_service_proto_enumTypes[3]
}

func (x HttpService_Version) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HttpService_Version) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HttpService_Version(num)
	return nil
}

// Deprecated: Use HttpService_Version.Descriptor instead.
func (HttpService_Version) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 3}
}

type HttpService struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	WebRequest     *HttpService_WebRequest     `protobuf:"bytes,1,opt,name=webRequest" json:"webRequest,omitempty"`
	WebResponse    *HttpService_WebResponse    `protobuf:"bytes,2,opt,name=webResponse" json:"webResponse,omitempty"`
	RawRequest     *HttpService_RawRequest     `protobuf:"bytes,5,opt,name=rawRequest" json:"rawRequest,omitempty"`
	RawResponse    *HttpService_RawResponse    `protobuf:"bytes,6,opt,name=rawResponse" json:"rawResponse,omitempty"`
	ShowURLRequest *HttpService_ShowURLRequest `protobuf:"bytes,11,opt,name=showURLRequest" json:"showURLRequest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HttpService) Reset() {
	*x = HttpService{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService) ProtoMessage() {}

func (x *HttpService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService.ProtoReflect.Descriptor instead.
func (*HttpService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0}
}

func (x *HttpService) GetWebRequest() *HttpService_WebRequest {
	if x != nil {
		return x.WebRequest
	}
	return nil
}

func (x *HttpService) GetWebResponse() *HttpService_WebResponse {
	if x != nil {
		return x.WebResponse
	}
	return nil
}

func (x *HttpService) GetRawRequest() *HttpService_RawRequest {
	if x != nil {
		return x.RawRequest
	}
	return nil
}

func (x *HttpService) GetRawResponse() *HttpService_RawResponse {
	if x != nil {
		return x.RawResponse
	}
	return nil
}

func (x *HttpService) GetShowURLRequest() *HttpService_ShowURLRequest {
	if x != nil {
		return x.ShowURLRequest
	}
	return nil
}

type HttpService_WebRequest struct {
	state                 protoimpl.MessageState    `protogen:"open.v1"`
	Url                   *string                   `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Method                *HttpService_Method       `protobuf:"varint,2,opt,name=method,enum=garmin_vivomovehr.HttpService_Method" json:"method,omitempty"`
	Headers               []byte                    `protobuf:"bytes,3,opt,name=headers" json:"headers,omitempty"`
	Body                  []byte                    `protobuf:"bytes,4,opt,name=body" json:"body,omitempty"`
	MaxResponseLength     *uint32                   `protobuf:"varint,5,opt,name=maxResponseLength" json:"maxResponseLength,omitempty"`
	HttpHeadersInResponse *bool                     `protobuf:"varint,6,opt,name=httpHeadersInResponse,def=1" json:"httpHeadersInResponse,omitempty"`
	CompressResponseBody  *bool                     `protobuf:"varint,7,opt,name=compressResponseBody,def=0" json:"compressResponseBody,omitempty"`
	ResponseType          *HttpService_ResponseType `protobuf:"varint,8,opt,name=responseType,enum=garmin_vivomovehr.HttpService_ResponseType" json:"responseType,omitempty"`
	Version               *HttpService_Version      `protobuf:"varint,9,opt,name=version,enum=garmin_vivomovehr.HttpService_Version,def=0" json:"version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

// Default values for HttpService_WebRequest fields.
const (
	Default_HttpService_WebRequest_HttpHeadersInResponse = bool(true)
	Default_HttpService_WebRequest_CompressResponseBody  = bool(false)
	Default_HttpService_WebRequest_Version               = HttpService_VERSION_1
)

func (x *HttpService_WebRequest) Reset() {
	*x = HttpService_WebRequest{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_WebRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_WebRequest) ProtoMessage() {}

func (x *HttpService_WebRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_WebRequest.ProtoReflect.Descriptor instead.
func (*HttpService_WebRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *HttpService_WebRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *HttpService_WebRequest) GetMethod() HttpService_Method {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return HttpService_UNKNOWN_METHOD
}

func (x *HttpService_WebRequest) GetHeaders() []byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpService_WebRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpService_WebRequest) GetMaxResponseLength() uint32 {
	if x != nil && x.MaxResponseLength != nil {
		return *x.MaxResponseLength
	}
	return 0
}

func (x *HttpService_WebRequest) GetHttpHeadersInResponse() bool {
	if x != nil && x.HttpHeadersInResponse != nil {
		return *x.HttpHeadersInResponse
	}
	return Default_HttpService_WebRequest_HttpHeadersInResponse
}

func (x *HttpService_WebRequest) GetCompressResponseBody() bool {
	if x != nil && x.CompressResponseBody != nil {
		return *x.CompressResponseBody
	}
	return Default_HttpService_WebRequest_CompressResponseBody
}

func (x *HttpService_WebRequest) GetResponseType() HttpService_ResponseType {
	if x != nil && x.ResponseType != nil {
		return *x.ResponseType
	}
	return HttpService_JSON
}

func (x *HttpService_WebRequest) GetVersion() HttpService_Version {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return Default_HttpService_WebRequest_Version
}

type HttpService_WebResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Status        *HttpService_Status       `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.HttpService_Status" json:"status,omitempty"`
	HttpStatus    *uint32                   `protobuf:"varint,2,opt,name=httpStatus" json:"httpStatus,omitempty"`
	Body          []byte                    `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Headers       []byte                    `protobuf:"bytes,4,opt,name=headers" json:"headers,omitempty"`
	Size          *uint32                   `protobuf:"varint,5,opt,name=size" json:"size,omitempty"`
	ResponseType  *HttpService_ResponseType `protobuf:"varint,6,opt,name=responseType,enum=garmin_vivomovehr.HttpService_ResponseType" json:"responseType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpService_WebResponse) Reset() {
	*x = HttpService_WebResponse{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_WebResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_WebResponse) ProtoMessage() {}

func (x *HttpService_WebResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_WebResponse.ProtoReflect.Descriptor instead.
func (*HttpService_WebResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *HttpService_WebResponse) GetStatus() HttpService_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return HttpService_UNKNOWN_STATUS
}

func (x *HttpService_WebResponse) GetHttpStatus() uint32 {
	if x != nil && x.HttpStatus != nil {
		return *x.HttpStatus
	}
	return 0
}

func (x *HttpService_WebResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpService_WebResponse) GetHeaders() []byte {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpService_WebResponse) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *HttpService_WebResponse) GetResponseType() HttpService_ResponseType {
	if x != nil && x.ResponseType != nil {
		return *x.ResponseType
	}
	return HttpService_JSON
}

type HttpService_RawRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Method        *HttpService_Method    `protobuf:"varint,3,opt,name=method,enum=garmin_vivomovehr.HttpService_Method" json:"method,omitempty"`
	Header        []*HttpService_Header  `protobuf:"bytes,5,rep,name=header" json:"header,omitempty"`
	UseDataXfer   *bool                  `protobuf:"varint,6,opt,name=useDataXfer" json:"useDataXfer,omitempty"`
	RawBody       []byte                 `protobuf:"bytes,7,opt,name=rawBody" json:"rawBody,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpService_RawRequest) Reset() {
	*x = HttpService_RawRequest{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_RawRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_RawRequest) ProtoMessage() {}

func (x *HttpService_RawRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_RawRequest.ProtoReflect.Descriptor instead.
func (*HttpService_RawRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *HttpService_RawRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *HttpService_RawRequest) GetMethod() HttpService_Method {
	if x != nil && x.Method != nil {
		return *x.Method
	}
	return HttpService_UNKNOWN_METHOD
}

func (x *HttpService_RawRequest) GetHeader() []*HttpService_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *HttpService_RawRequest) GetUseDataXfer() bool {
	if x != nil && x.UseDataXfer != nil {
		return *x.UseDataXfer
	}
	return false
}

func (x *HttpService_RawRequest) GetRawBody() []byte {
	if x != nil {
		return x.RawBody
	}
	return nil
}

type HttpService_RawResponse struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	Status        *HttpService_Status           `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.HttpService_Status" json:"status,omitempty"`
	HttpStatus    *uint32                       `protobuf:"varint,2,opt,name=httpStatus" json:"httpStatus,omitempty"`
	Body          []byte                        `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	XferData      *HttpService_DataTransferItem `protobuf:"bytes,4,opt,name=xferData" json:"xferData,omitempty"`
	Header        []*HttpService_Header         `protobuf:"bytes,5,rep,name=header" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpService_RawResponse) Reset() {
	*x = HttpService_RawResponse{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_RawResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_RawResponse) ProtoMessage() {}

func (x *HttpService_RawResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_RawResponse.ProtoReflect.Descriptor instead.
func (*HttpService_RawResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *HttpService_RawResponse) GetStatus() HttpService_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return HttpService_UNKNOWN_STATUS
}

func (x *HttpService_RawResponse) GetHttpStatus() uint32 {
	if x != nil && x.HttpStatus != nil {
		return *x.HttpStatus
	}
	return 0
}

func (x *HttpService_RawResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpService_RawResponse) GetXferData() *HttpService_DataTransferItem {
	if x != nil {
		return x.XferData
	}
	return nil
}

func (x *HttpService_RawResponse) GetHeader() []*HttpService_Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type HttpService_DataTransferItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Size          *uint32                `protobuf:"varint,2,req,name=size" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpService_DataTransferItem) Reset() {
	*x = HttpService_DataTransferItem{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_DataTransferItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_DataTransferItem) ProtoMessage() {}

func (x *HttpService_DataTransferItem) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_DataTransferItem.ProtoReflect.Descriptor instead.
func (*HttpService_DataTransferItem) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 4}
}

func (x *HttpService_DataTransferItem) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *HttpService_DataTransferItem) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

type HttpService_Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           *string                `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value         *string                `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpService_Header) Reset() {
	*x = HttpService_Header{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_Header) ProtoMessage() {}

func (x *HttpService_Header) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_Header.ProtoReflect.Descriptor instead.
func (*HttpService_Header) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 5}
}

func (x *HttpService_Header) GetKey() string {
	if x != nil && x.Key != nil {
		return *x.Key
	}
	return ""
}

func (x *HttpService_Header) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type HttpService_ShowURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           *string                `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	Parameters    []byte                 `protobuf:"bytes,2,opt,name=parameters" json:"parameters,omitempty"`
	App           *string                `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpService_ShowURLRequest) Reset() {
	*x = HttpService_ShowURLRequest{}
	mi := &file_garmin_gdi_http_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpService_ShowURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpService_ShowURLRequest) ProtoMessage() {}

func (x *HttpService_ShowURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_http_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpService_ShowURLRequest.ProtoReflect.Descriptor instead.
func (*HttpService_ShowURLRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_http_service_proto_rawDescGZIP(), []int{0, 6}
}

func (x *HttpService_ShowURLRequest) GetUrl() string {
	if x != nil && x.Url != nil {
		return *x.Url
	}
	return ""
}

func (x *HttpService_ShowURLRequest) GetParameters() []byte {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *HttpService_ShowURLRequest) GetApp() string {
	if x != nil && x.App != nil {
		return *x.App
	}
	return ""
}

var File_garmin_gdi_http_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_http_service_proto_rawDesc = "" +
	"\n" +
	"\x1dgarmin/gdi_http_service.proto\x12\x11garmin_vivomovehr\"\xd7\x10\n" +
	"\vHttpService\x12I\n" +
	"\n" +
	"webRequest\x18\x01 \x01(\v2).garmin_vivomovehr.HttpService.WebRequestR\n" +
	"webRequest\x12L\n" +
	"\vwebResponse\x18\x02 \x01(\v2*.garmin_vivomovehr.HttpService.WebResponseR\vwebResponse\x12I\n" +
	"\n" +
	"rawRequest\x18\x05 \x01(\v2).garmin_vivomovehr.HttpService.RawRequestR\n" +
	"rawRequest\x12L\n" +
	"\vrawResponse\x18\x06 \x01(\v2*.garmin_vivomovehr.HttpService.RawResponseR\vrawResponse\x12U\n" +
	"\x0eshowURLRequest\x18\v \x01(\v2-.garmin_vivomovehr.HttpService.ShowURLRequestR\x0eshowURLRequest\x1a\xce\x03\n" +
	"\n" +
	"WebRequest\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12=\n" +
	"\x06method\x18\x02 \x01(\x0e2%.garmin_vivomovehr.HttpService.MethodR\x06method\x12\x18\n" +
	"\aheaders\x18\x03 \x01(\fR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12,\n" +
	"\x11maxResponseLength\x18\x05 \x01(\rR\x11maxResponseLength\x12:\n" +
	"\x15httpHeadersInResponse\x18\x06 \x01(\b:\x04trueR\x15httpHeadersInResponse\x129\n" +
	"\x14compressResponseBody\x18\a \x01(\b:\x05falseR\x14compressResponseBody\x12O\n" +
	"\fresponseType\x18\b \x01(\x0e2+.garmin_vivomovehr.HttpService.ResponseTypeR\fresponseType\x12K\n" +
	"\aversion\x18\t \x01(\x0e2&.garmin_vivomovehr.HttpService.Version:\tVERSION_1R\aversion\x1a\xff\x01\n" +
	"\vWebResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.garmin_vivomovehr.HttpService.StatusR\x06status\x12\x1e\n" +
	"\n" +
	"httpStatus\x18\x02 \x01(\rR\n" +
	"httpStatus\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12\x18\n" +
	"\aheaders\x18\x04 \x01(\fR\aheaders\x12\x12\n" +
	"\x04size\x18\x05 \x01(\rR\x04size\x12O\n" +
	"\fresponseType\x18\x06 \x01(\x0e2+.garmin_vivomovehr.HttpService.ResponseTypeR\fresponseType\x1a\xd8\x01\n" +
	"\n" +
	"RawRequest\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12=\n" +
	"\x06method\x18\x03 \x01(\x0e2%.garmin_vivomovehr.HttpService.MethodR\x06method\x12=\n" +
	"\x06header\x18\x05 \x03(\v2%.garmin_vivomovehr.HttpService.HeaderR\x06header\x12 \n" +
	"\vuseDataXfer\x18\x06 \x01(\bR\vuseDataXfer\x12\x18\n" +
	"\arawBody\x18\a \x01(\fR\arawBody\x1a\x8c\x02\n" +
	"\vRawResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.garmin_vivomovehr.HttpService.StatusR\x06status\x12\x1e\n" +
	"\n" +
	"httpStatus\x18\x02 \x01(\rR\n" +
	"httpStatus\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\x12K\n" +
	"\bxferData\x18\x04 \x01(\v2/.garmin_vivomovehr.HttpService.DataTransferItemR\bxferData\x12=\n" +
	"\x06header\x18\x05 \x03(\v2%.garmin_vivomovehr.HttpService.HeaderR\x06header\x1a6\n" +
	"\x10DataTransferItem\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x02(\rR\x04size\x1a0\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x02(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x02(\tR\x05value\x1aT\n" +
	"\x0eShowURLRequest\x12\x10\n" +
	"\x03url\x18\x01 \x02(\tR\x03url\x12\x1e\n" +
	"\n" +
	"parameters\x18\x02 \x01(\fR\n" +
	"parameters\x12\x10\n" +
	"\x03app\x18\x03 \x01(\tR\x03app\"Y\n" +
	"\x06Method\x12\x12\n" +
	"\x0eUNKNOWN_METHOD\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\a\n" +
	"\x03PUT\x10\x02\x12\b\n" +
	"\x04POST\x10\x03\x12\n" +
	"\n" +
	"\x06DELETE\x10\x04\x12\t\n" +
	"\x05PATCH\x10\x05\x12\b\n" +
	"\x04HEAD\x10\x06\"z\n" +
	"\x06Status\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\x06\n" +
	"\x02OK\x10d\x12\x1e\n" +
	"\x19NETWORK_REQUEST_TIMED_OUT\x10\xc8\x01\x12\x13\n" +
	"\x0eFILE_TOO_LARGE\x10\xac\x02\x12\x1f\n" +
	"\x1aDATA_TRANSFER_ITEM_FAILURE\x10\x90\x03\"B\n" +
	"\fResponseType\x12\b\n" +
	"\x04JSON\x10\x00\x12\x0f\n" +
	"\vURL_ENCODED\x10\x01\x12\x0e\n" +
	"\n" +
	"PLAIN_TEXT\x10\x02\x12\a\n" +
	"\x03XML\x10\x03\"'\n" +
	"\aVersion\x12\r\n" +
	"\tVERSION_1\x10\x00\x12\r\n" +
	"\tVERSION_2\x10\x01BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_http_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_http_service_proto_rawDescData []byte
)

func file_garmin_gdi_http_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_http_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_http_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_http_service_proto_rawDesc), len(file_garmin_gdi_http_service_proto_rawDesc)))
	})
	return file_garmin_gdi_http_service_proto_rawDescData
}

var file_garmin_gdi_http_service_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_garmin_gdi_http_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_garmin_gdi_http_service_proto_goTypes = []any{
	(HttpService_Method)(0),              // 0: garmin_vivomovehr.HttpService.Method
	(HttpService_Status)(0),              // 1: garmin_vivomovehr.HttpService.Status
	(HttpService_ResponseType)(0),        // 2: garmin_vivomovehr.HttpService.ResponseType
	(HttpService_Version)(0),             // 3: garmin_vivomovehr.HttpService.Version
	(*HttpService)(nil),                  // 4: garmin_vivomovehr.HttpService
	(*HttpService_WebRequest)(nil),       // 5: garmin_vivomovehr.HttpService.WebRequest
	(*HttpService_WebResponse)(nil),      // 6: garmin_vivomovehr.HttpService.WebResponse
	(*HttpService_RawRequest)(nil),       // 7: garmin_vivomovehr.HttpService.RawRequest
	(*HttpService_RawResponse)(nil),      // 8: garmin_vivomovehr.HttpService.RawResponse
	(*HttpService_DataTransferItem)(nil), // 9: garmin_vivomovehr.HttpService.DataTransferItem
	(*HttpService_Header)(nil),           // 10: garmin_vivomovehr.HttpService.Header
	(*HttpService_ShowURLRequest)(nil),   // 11: garmin_vivomovehr.HttpService.ShowURLRequest
}
var file_garmin_gdi_http_service_proto_depIdxs = []int32{
	5,  // 0: garmin_vivomovehr.HttpService.webRequest:type_name -> garmin_vivomovehr.HttpService.WebRequest
	6,  // 1: garmin_vivomovehr.HttpService.webResponse:type_name -> garmin_vivomovehr.HttpService.WebResponse
	7,  // 2: garmin_vivomovehr.HttpService.rawRequest:type_name -> garmin_vivomovehr.HttpService.RawRequest
	8,  // 3: garmin_vivomovehr.HttpService.rawResponse:type_name -> garmin_vivomovehr.HttpService.RawResponse
	11, // 4: garmin_vivomovehr.HttpService.showURLRequest:type_name -> garmin_vivomovehr.HttpService.ShowURLRequest
	0,  // 5: garmin_vivomovehr.HttpService.WebRequest.method:type_name -> garmin_vivomovehr.HttpService.Method
	2,  // 6: garmin_vivomovehr.HttpService.WebRequest.responseType:type_name -> garmin_vivomovehr.HttpService.ResponseType
	3,  // 7: garmin_vivomovehr.HttpService.WebRequest.version:type_name -> garmin_vivomovehr.HttpService.Version
	1,  // 8: garmin_vivomovehr.HttpService.WebResponse.status:type_name -> garmin_vivomovehr.HttpService.Status
	2,  // 9: garmin_vivomovehr.HttpService.WebResponse.responseType:type_name -> garmin_vivomovehr.HttpService.ResponseType
	0,  // 10: garmin_vivomovehr.HttpService.RawRequest.method:type_name -> garmin_vivomovehr.HttpService.Method
	10, // 11: garmin_vivomovehr.HttpService.RawRequest.header:type_name -> garmin_vivomovehr.HttpService.Header
	1,  // 12: garmin_vivomovehr.HttpService.RawResponse.status:type_name -> garmin_vivomovehr.HttpService.Status
	9,  // 13: garmin_vivomovehr.HttpService.RawResponse.xferData:type_name -> garmin_vivomovehr.HttpService.DataTransferItem
	10, // 14: garmin_vivomovehr.HttpService.RawResponse.header:type_name -> garmin_vivomovehr.HttpService.Header
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_garmin_gdi_http_service_proto_init() }
func file_garmin_gdi_http_service_proto_init() {
	if File_garmin_gdi_http_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_http_service_proto_rawDesc), len(file_garmin_gdi_http_service_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_http_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_http_service_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_http_service_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_http_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_http_service_proto = out.File
	file_garmin_gdi_http_service_proto_goTypes = nil
	file_garmin_gdi_http_service_proto_depIdxs = nil
}
