// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_installed_apps_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstalledAppsService_AppType int32

const (
	InstalledAppsService_UNKNOWN_APP_TYPE       InstalledAppsService_AppType = 0
	InstalledAppsService_WATCH_APP              InstalledAppsService_AppType = 1
	InstalledAppsService_WIDGET                 InstalledAppsService_AppType = 2
	InstalledAppsService_WATCH_FACE             InstalledAppsService_AppType = 3
	InstalledAppsService_DATA_FIELD             InstalledAppsService_AppType = 4
	InstalledAppsService_ALL                    InstalledAppsService_AppType = 5
	InstalledAppsService_NONE                   InstalledAppsService_AppType = 6
	InstalledAppsService_AUDIO_CONTENT_PROVIDER InstalledAppsService_AppType = 7
	InstalledAppsService_ACTIVITY               InstalledAppsService_AppType = 8
)

// Enum value maps for InstalledAppsService_AppType.
var (
	InstalledAppsService_AppType_name = map[int32]string{
		0: "UNKNOWN_APP_TYPE",
		1: "WATCH_APP",
		2: "WIDGET",
		3: "WATCH_FACE",
		4: "DATA_FIELD",
		5: "ALL",
		6: "NONE",
		7: "AUDIO_CONTENT_PROVIDER",
		8: "ACTIVITY",
	}
	InstalledAppsService_AppType_value = map[string]int32{
		"UNKNOWN_APP_TYPE":       0,
		"WATCH_APP":              1,
		"WIDGET":                 2,
		"WATCH_FACE":             3,
		"DATA_FIELD":             4,
		"ALL":                    5,
		"NONE":                   6,
		"AUDIO_CONTENT_PROVIDER": 7,
		"ACTIVITY":               8,
	}
)

func (x InstalledAppsService_AppType) Enum() *InstalledAppsService_AppType {
	p := new(InstalledAppsService_AppType)
	*p = x
	return p
}

func (x InstalledAppsService_AppType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstalledAppsService_AppType) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_installed_apps_service_proto_enumTypes[0].Descriptor()
}

func (InstalledAppsService_AppType) Type() protoreflect.EnumType {
	return &file_garmin_gdi_installed_apps_service_proto_enumTypes[0]
}

func (x InstalledAppsService_AppType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InstalledAppsService_AppType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InstalledAppsService_AppType(num)
	return nil
}

// Deprecated: Use InstalledAppsService_AppType.Descriptor instead.
func (InstalledAppsService_AppType) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 0}
}

type InstalledAppsService_DeleteAppResponse_Status int32

const (
	InstalledAppsService_DeleteAppResponse_UNKNOWN_STATUS   InstalledAppsService_DeleteAppResponse_Status = 0
	InstalledAppsService_DeleteAppResponse_OK               InstalledAppsService_DeleteAppResponse_Status = 1
	InstalledAppsService_DeleteAppResponse_FAILED_TO_DELETE InstalledAppsService_DeleteAppResponse_Status = 2
)

// Enum value maps for InstalledAppsService_DeleteAppResponse_Status.
var (
	InstalledAppsService_DeleteAppResponse_Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "OK",
		2: "FAILED_TO_DELETE",
	}
	InstalledAppsService_DeleteAppResponse_Status_value = map[string]int32{
		"UNKNOWN_STATUS":   0,
		"OK":               1,
		"FAILED_TO_DELETE": 2,
	}
)

func (x InstalledAppsService_DeleteAppResponse_Status) Enum() *InstalledAppsService_DeleteAppResponse_Status {
	p := new(InstalledAppsService_DeleteAppResponse_Status)
	*p = x
	return p
}

func (x InstalledAppsService_DeleteAppResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstalledAppsService_DeleteAppResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_installed_apps_service_proto_enumTypes[1].Descriptor()
}

func (InstalledAppsService_DeleteAppResponse_Status) Type() protoreflect.EnumType {
	return &file_garmin_gdi_installed_apps_service_proto_enumTypes[1]
}

func (x InstalledAppsService_DeleteAppResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *InstalledAppsService_DeleteAppResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = InstalledAppsService_DeleteAppResponse_Status(num)
	return nil
}

// Deprecated: Use InstalledAppsService_DeleteAppResponse_Status.Descriptor instead.
func (InstalledAppsService_DeleteAppResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 4, 0}
}

type InstalledAppsService struct {
	state                    protoimpl.MessageState                         `protogen:"open.v1"`
	GetInstalledAppsRequest  *InstalledAppsService_GetInstalledAppsRequest  `protobuf:"bytes,1,opt,name=getInstalledAppsRequest" json:"getInstalledAppsRequest,omitempty"`
	GetInstalledAppsResponse *InstalledAppsService_GetInstalledAppsResponse `protobuf:"bytes,2,opt,name=getInstalledAppsResponse" json:"getInstalledAppsResponse,omitempty"`
	DeleteAppRequest         *InstalledAppsService_DeleteAppRequest         `protobuf:"bytes,3,opt,name=deleteAppRequest" json:"deleteAppRequest,omitempty"`
	DeleteAppResponse        *InstalledAppsService_DeleteAppResponse        `protobuf:"bytes,4,opt,name=deleteAppResponse" json:"deleteAppResponse,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InstalledAppsService) Reset() {
	*x = InstalledAppsService{}
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledAppsService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledAppsService) ProtoMessage() {}

func (x *InstalledAppsService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledAppsService.ProtoReflect.Descriptor instead.
func (*InstalledAppsService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0}
}

func (x *InstalledAppsService) GetGetInstalledAppsRequest() *InstalledAppsService_GetInstalledAppsRequest {
	if x != nil {
		return x.GetInstalledAppsRequest
	}
	return nil
}

func (x *InstalledAppsService) GetGetInstalledAppsResponse() *InstalledAppsService_GetInstalledAppsResponse {
	if x != nil {
		return x.GetInstalledAppsResponse
	}
	return nil
}

func (x *InstalledAppsService) GetDeleteAppRequest() *InstalledAppsService_DeleteAppRequest {
	if x != nil {
		return x.DeleteAppRequest
	}
	return nil
}

func (x *InstalledAppsService) GetDeleteAppResponse() *InstalledAppsService_DeleteAppResponse {
	if x != nil {
		return x.DeleteAppResponse
	}
	return nil
}

type InstalledAppsService_InstalledApp struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	StoreAppId    []byte                        `protobuf:"bytes,1,req,name=storeAppId" json:"storeAppId,omitempty"`
	Type          *InstalledAppsService_AppType `protobuf:"varint,2,req,name=type,enum=garmin_vivomovehr.InstalledAppsService_AppType" json:"type,omitempty"`
	Name          *string                       `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Disabled      *bool                         `protobuf:"varint,4,req,name=disabled" json:"disabled,omitempty"`
	Version       *uint32                       `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	FileName      *string                       `protobuf:"bytes,6,opt,name=fileName" json:"fileName,omitempty"`
	FileSize      *uint64                       `protobuf:"varint,7,opt,name=fileSize" json:"fileSize,omitempty"`
	NativeAppId   *uint32                       `protobuf:"varint,8,opt,name=nativeAppId" json:"nativeAppId,omitempty"`
	Favorite      *bool                         `protobuf:"varint,9,opt,name=favorite" json:"favorite,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledAppsService_InstalledApp) Reset() {
	*x = InstalledAppsService_InstalledApp{}
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledAppsService_InstalledApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledAppsService_InstalledApp) ProtoMessage() {}

func (x *InstalledAppsService_InstalledApp) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledAppsService_InstalledApp.ProtoReflect.Descriptor instead.
func (*InstalledAppsService_InstalledApp) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *InstalledAppsService_InstalledApp) GetStoreAppId() []byte {
	if x != nil {
		return x.StoreAppId
	}
	return nil
}

func (x *InstalledAppsService_InstalledApp) GetType() InstalledAppsService_AppType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return InstalledAppsService_UNKNOWN_APP_TYPE
}

func (x *InstalledAppsService_InstalledApp) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *InstalledAppsService_InstalledApp) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *InstalledAppsService_InstalledApp) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *InstalledAppsService_InstalledApp) GetFileName() string {
	if x != nil && x.FileName != nil {
		return *x.FileName
	}
	return ""
}

func (x *InstalledAppsService_InstalledApp) GetFileSize() uint64 {
	if x != nil && x.FileSize != nil {
		return *x.FileSize
	}
	return 0
}

func (x *InstalledAppsService_InstalledApp) GetNativeAppId() uint32 {
	if x != nil && x.NativeAppId != nil {
		return *x.NativeAppId
	}
	return 0
}

func (x *InstalledAppsService_InstalledApp) GetFavorite() bool {
	if x != nil && x.Favorite != nil {
		return *x.Favorite
	}
	return false
}

type InstalledAppsService_GetInstalledAppsRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	AppType       *InstalledAppsService_AppType `protobuf:"varint,1,req,name=appType,enum=garmin_vivomovehr.InstalledAppsService_AppType" json:"appType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledAppsService_GetInstalledAppsRequest) Reset() {
	*x = InstalledAppsService_GetInstalledAppsRequest{}
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledAppsService_GetInstalledAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledAppsService_GetInstalledAppsRequest) ProtoMessage() {}

func (x *InstalledAppsService_GetInstalledAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledAppsService_GetInstalledAppsRequest.ProtoReflect.Descriptor instead.
func (*InstalledAppsService_GetInstalledAppsRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *InstalledAppsService_GetInstalledAppsRequest) GetAppType() InstalledAppsService_AppType {
	if x != nil && x.AppType != nil {
		return *x.AppType
	}
	return InstalledAppsService_UNKNOWN_APP_TYPE
}

type InstalledAppsService_GetInstalledAppsResponse struct {
	state          protoimpl.MessageState               `protogen:"open.v1"`
	AvailableSpace *uint64                              `protobuf:"varint,1,req,name=availableSpace" json:"availableSpace,omitempty"`
	AvailableSlots *uint64                              `protobuf:"varint,2,req,name=availableSlots" json:"availableSlots,omitempty"`
	InstalledApps  []*InstalledAppsService_InstalledApp `protobuf:"bytes,3,rep,name=installedApps" json:"installedApps,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InstalledAppsService_GetInstalledAppsResponse) Reset() {
	*x = InstalledAppsService_GetInstalledAppsResponse{}
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledAppsService_GetInstalledAppsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledAppsService_GetInstalledAppsResponse) ProtoMessage() {}

func (x *InstalledAppsService_GetInstalledAppsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledAppsService_GetInstalledAppsResponse.ProtoReflect.Descriptor instead.
func (*InstalledAppsService_GetInstalledAppsResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *InstalledAppsService_GetInstalledAppsResponse) GetAvailableSpace() uint64 {
	if x != nil && x.AvailableSpace != nil {
		return *x.AvailableSpace
	}
	return 0
}

func (x *InstalledAppsService_GetInstalledAppsResponse) GetAvailableSlots() uint64 {
	if x != nil && x.AvailableSlots != nil {
		return *x.AvailableSlots
	}
	return 0
}

func (x *InstalledAppsService_GetInstalledAppsResponse) GetInstalledApps() []*InstalledAppsService_InstalledApp {
	if x != nil {
		return x.InstalledApps
	}
	return nil
}

type InstalledAppsService_DeleteAppRequest struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	StoreAppId    []byte                        `protobuf:"bytes,1,req,name=storeAppId" json:"storeAppId,omitempty"`
	AppType       *InstalledAppsService_AppType `protobuf:"varint,2,req,name=appType,enum=garmin_vivomovehr.InstalledAppsService_AppType" json:"appType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledAppsService_DeleteAppRequest) Reset() {
	*x = InstalledAppsService_DeleteAppRequest{}
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledAppsService_DeleteAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledAppsService_DeleteAppRequest) ProtoMessage() {}

func (x *InstalledAppsService_DeleteAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledAppsService_DeleteAppRequest.ProtoReflect.Descriptor instead.
func (*InstalledAppsService_DeleteAppRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 3}
}

func (x *InstalledAppsService_DeleteAppRequest) GetStoreAppId() []byte {
	if x != nil {
		return x.StoreAppId
	}
	return nil
}

func (x *InstalledAppsService_DeleteAppRequest) GetAppType() InstalledAppsService_AppType {
	if x != nil && x.AppType != nil {
		return *x.AppType
	}
	return InstalledAppsService_UNKNOWN_APP_TYPE
}

type InstalledAppsService_DeleteAppResponse struct {
	state         protoimpl.MessageState                         `protogen:"open.v1"`
	Status        *InstalledAppsService_DeleteAppResponse_Status `protobuf:"varint,1,req,name=status,enum=garmin_vivomovehr.InstalledAppsService_DeleteAppResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstalledAppsService_DeleteAppResponse) Reset() {
	*x = InstalledAppsService_DeleteAppResponse{}
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstalledAppsService_DeleteAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstalledAppsService_DeleteAppResponse) ProtoMessage() {}

func (x *InstalledAppsService_DeleteAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_installed_apps_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstalledAppsService_DeleteAppResponse.ProtoReflect.Descriptor instead.
func (*InstalledAppsService_DeleteAppResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_installed_apps_service_proto_rawDescGZIP(), []int{0, 4}
}

func (x *InstalledAppsService_DeleteAppResponse) GetStatus() InstalledAppsService_DeleteAppResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return InstalledAppsService_DeleteAppResponse_UNKNOWN_STATUS
}

var File_garmin_gdi_installed_apps_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_installed_apps_service_proto_rawDesc = "" +
	"\n" +
	"'garmin/gdi_installed_apps_service.proto\x12\x11garmin_vivomovehr\"\x88\f\n" +
	"\x14InstalledAppsService\x12y\n" +
	"\x17getInstalledAppsRequest\x18\x01 \x01(\v2?.garmin_vivomovehr.InstalledAppsService.GetInstalledAppsRequestR\x17getInstalledAppsRequest\x12|\n" +
	"\x18getInstalledAppsResponse\x18\x02 \x01(\v2@.garmin_vivomovehr.InstalledAppsService.GetInstalledAppsResponseR\x18getInstalledAppsResponse\x12d\n" +
	"\x10deleteAppRequest\x18\x03 \x01(\v28.garmin_vivomovehr.InstalledAppsService.DeleteAppRequestR\x10deleteAppRequest\x12g\n" +
	"\x11deleteAppResponse\x18\x04 \x01(\v29.garmin_vivomovehr.InstalledAppsService.DeleteAppResponseR\x11deleteAppResponse\x1a\xb3\x02\n" +
	"\fInstalledApp\x12\x1e\n" +
	"\n" +
	"storeAppId\x18\x01 \x02(\fR\n" +
	"storeAppId\x12C\n" +
	"\x04type\x18\x02 \x02(\x0e2/.garmin_vivomovehr.InstalledAppsService.AppTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x03 \x02(\tR\x04name\x12\x1a\n" +
	"\bdisabled\x18\x04 \x02(\bR\bdisabled\x12\x18\n" +
	"\aversion\x18\x05 \x01(\rR\aversion\x12\x1a\n" +
	"\bfileName\x18\x06 \x01(\tR\bfileName\x12\x1a\n" +
	"\bfileSize\x18\a \x01(\x04R\bfileSize\x12 \n" +
	"\vnativeAppId\x18\b \x01(\rR\vnativeAppId\x12\x1a\n" +
	"\bfavorite\x18\t \x01(\bR\bfavorite\x1ad\n" +
	"\x17GetInstalledAppsRequest\x12I\n" +
	"\aappType\x18\x01 \x02(\x0e2/.garmin_vivomovehr.InstalledAppsService.AppTypeR\aappType\x1a\xc6\x01\n" +
	"\x18GetInstalledAppsResponse\x12&\n" +
	"\x0eavailableSpace\x18\x01 \x02(\x04R\x0eavailableSpace\x12&\n" +
	"\x0eavailableSlots\x18\x02 \x02(\x04R\x0eavailableSlots\x12Z\n" +
	"\rinstalledApps\x18\x03 \x03(\v24.garmin_vivomovehr.InstalledAppsService.InstalledAppR\rinstalledApps\x1a}\n" +
	"\x10DeleteAppRequest\x12\x1e\n" +
	"\n" +
	"storeAppId\x18\x01 \x02(\fR\n" +
	"storeAppId\x12I\n" +
	"\aappType\x18\x02 \x02(\x0e2/.garmin_vivomovehr.InstalledAppsService.AppTypeR\aappType\x1a\xa9\x01\n" +
	"\x11DeleteAppResponse\x12X\n" +
	"\x06status\x18\x01 \x02(\x0e2@.garmin_vivomovehr.InstalledAppsService.DeleteAppResponse.StatusR\x06status\":\n" +
	"\x06Status\x12\x12\n" +
	"\x0eUNKNOWN_STATUS\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x14\n" +
	"\x10FAILED_TO_DELETE\x10\x02\"\x97\x01\n" +
	"\aAppType\x12\x14\n" +
	"\x10UNKNOWN_APP_TYPE\x10\x00\x12\r\n" +
	"\tWATCH_APP\x10\x01\x12\n" +
	"\n" +
	"\x06WIDGET\x10\x02\x12\x0e\n" +
	"\n" +
	"WATCH_FACE\x10\x03\x12\x0e\n" +
	"\n" +
	"DATA_FIELD\x10\x04\x12\a\n" +
	"\x03ALL\x10\x05\x12\b\n" +
	"\x04NONE\x10\x06\x12\x1a\n" +
	"\x16AUDIO_CONTENT_PROVIDER\x10\a\x12\f\n" +
	"\bACTIVITY\x10\bBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_installed_apps_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_installed_apps_service_proto_rawDescData []byte
)

func file_garmin_gdi_installed_apps_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_installed_apps_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_installed_apps_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_installed_apps_service_proto_rawDesc), len(file_garmin_gdi_installed_apps_service_proto_rawDesc)))
	})
	return file_garmin_gdi_installed_apps_service_proto_rawDescData
}

var file_garmin_gdi_installed_apps_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_garmin_gdi_installed_apps_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_garmin_gdi_installed_apps_service_proto_goTypes = []any{
	(InstalledAppsService_AppType)(0),                     // 0: garmin_vivomovehr.InstalledAppsService.AppType
	(InstalledAppsService_DeleteAppResponse_Status)(0),    // 1: garmin_vivomovehr.InstalledAppsService.DeleteAppResponse.Status
	(*InstalledAppsService)(nil),                          // 2: garmin_vivomovehr.InstalledAppsService
	(*InstalledAppsService_InstalledApp)(nil),             // 3: garmin_vivomovehr.InstalledAppsService.InstalledApp
	(*InstalledAppsService_GetInstalledAppsRequest)(nil),  // 4: garmin_vivomovehr.InstalledAppsService.GetInstalledAppsRequest
	(*InstalledAppsService_GetInstalledAppsResponse)(nil), // 5: garmin_vivomovehr.InstalledAppsService.GetInstalledAppsResponse
	(*InstalledAppsService_DeleteAppRequest)(nil),         // 6: garmin_vivomovehr.InstalledAppsService.DeleteAppRequest
	(*InstalledAppsService_DeleteAppResponse)(nil),        // 7: garmin_vivomovehr.InstalledAppsService.DeleteAppResponse
}
var file_garmin_gdi_installed_apps_service_proto_depIdxs = []int32{
	4, // 0: garmin_vivomovehr.InstalledAppsService.getInstalledAppsRequest:type_name -> garmin_vivomovehr.InstalledAppsService.GetInstalledAppsRequest
	5, // 1: garmin_vivomovehr.InstalledAppsService.getInstalledAppsResponse:type_name -> garmin_vivomovehr.InstalledAppsService.GetInstalledAppsResponse
	6, // 2: garmin_vivomovehr.InstalledAppsService.deleteAppRequest:type_name -> garmin_vivomovehr.InstalledAppsService.DeleteAppRequest
	7, // 3: garmin_vivomovehr.InstalledAppsService.deleteAppResponse:type_name -> garmin_vivomovehr.InstalledAppsService.DeleteAppResponse
	0, // 4: garmin_vivomovehr.InstalledAppsService.InstalledApp.type:type_name -> garmin_vivomovehr.InstalledAppsService.AppType
	0, // 5: garmin_vivomovehr.InstalledAppsService.GetInstalledAppsRequest.appType:type_name -> garmin_vivomovehr.InstalledAppsService.AppType
	3, // 6: garmin_vivomovehr.InstalledAppsService.GetInstalledAppsResponse.installedApps:type_name -> garmin_vivomovehr.InstalledAppsService.InstalledApp
	0, // 7: garmin_vivomovehr.InstalledAppsService.DeleteAppRequest.appType:type_name -> garmin_vivomovehr.InstalledAppsService.AppType
	1, // 8: garmin_vivomovehr.InstalledAppsService.DeleteAppResponse.status:type_name -> garmin_vivomovehr.InstalledAppsService.DeleteAppResponse.Status
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_garmin_gdi_installed_apps_service_proto_init() }
func file_garmin_gdi_installed_apps_service_proto_init() {
	if File_garmin_gdi_installed_apps_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_installed_apps_service_proto_rawDesc), len(file_garmin_gdi_installed_apps_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_installed_apps_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_installed_apps_service_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_installed_apps_service_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_installed_apps_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_installed_apps_service_proto = out.File
	file_garmin_gdi_installed_apps_service_proto_goTypes = nil
	file_garmin_gdi_installed_apps_service_proto_depIdxs = nil
}
