// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_file_sync_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileSyncService struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	FileRequest            *FileRequest            `protobuf:"bytes,1,opt,name=file_request,json=fileRequest" json:"file_request,omitempty"`
	FileResponse           *FileResponse           `protobuf:"bytes,2,opt,name=file_response,json=fileResponse" json:"file_response,omitempty"`
	FileListRequest        *FileListRequest        `protobuf:"bytes,9,opt,name=file_list_request,json=fileListRequest" json:"file_list_request,omitempty"`
	FileListResponse       *FileListResponse       `protobuf:"bytes,10,opt,name=file_list_response,json=fileListResponse" json:"file_list_response,omitempty"`
	NewFileNotification    *NewFileNotification    `protobuf:"bytes,12,opt,name=new_file_notification,json=newFileNotification" json:"new_file_notification,omitempty"`
	FileSetFlags           *FileSetFlags           `protobuf:"bytes,15,opt,name=file_set_flags,json=fileSetFlags" json:"file_set_flags,omitempty"`
	FileUpdateNotification *FileUpdateNotification `protobuf:"bytes,17,opt,name=file_update_notification,json=fileUpdateNotification" json:"file_update_notification,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *FileSyncService) Reset() {
	*x = FileSyncService{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSyncService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSyncService) ProtoMessage() {}

func (x *FileSyncService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSyncService.ProtoReflect.Descriptor instead.
func (*FileSyncService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{0}
}

func (x *FileSyncService) GetFileRequest() *FileRequest {
	if x != nil {
		return x.FileRequest
	}
	return nil
}

func (x *FileSyncService) GetFileResponse() *FileResponse {
	if x != nil {
		return x.FileResponse
	}
	return nil
}

func (x *FileSyncService) GetFileListRequest() *FileListRequest {
	if x != nil {
		return x.FileListRequest
	}
	return nil
}

func (x *FileSyncService) GetFileListResponse() *FileListResponse {
	if x != nil {
		return x.FileListResponse
	}
	return nil
}

func (x *FileSyncService) GetNewFileNotification() *NewFileNotification {
	if x != nil {
		return x.NewFileNotification
	}
	return nil
}

func (x *FileSyncService) GetFileSetFlags() *FileSetFlags {
	if x != nil {
		return x.FileSetFlags
	}
	return nil
}

func (x *FileSyncService) GetFileUpdateNotification() *FileUpdateNotification {
	if x != nil {
		return x.FileUpdateNotification
	}
	return nil
}

type NewFileNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          []*File                `protobuf:"bytes,1,rep,name=file" json:"file,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 24
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 0
	Unk4          *uint32                `protobuf:"varint,4,opt,name=unk4" json:"unk4,omitempty"` // 0
	Unk5          *uint32                `protobuf:"varint,5,opt,name=unk5" json:"unk5,omitempty"` // 15
	Unk6          *uint32                `protobuf:"varint,6,opt,name=unk6" json:"unk6,omitempty"` // 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewFileNotification) Reset() {
	*x = NewFileNotification{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewFileNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewFileNotification) ProtoMessage() {}

func (x *NewFileNotification) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewFileNotification.ProtoReflect.Descriptor instead.
func (*NewFileNotification) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{1}
}

func (x *NewFileNotification) GetFile() []*File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *NewFileNotification) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *NewFileNotification) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *NewFileNotification) GetUnk4() uint32 {
	if x != nil && x.Unk4 != nil {
		return *x.Unk4
	}
	return 0
}

func (x *NewFileNotification) GetUnk5() uint32 {
	if x != nil && x.Unk5 != nil {
		return *x.Unk5
	}
	return 0
}

func (x *NewFileNotification) GetUnk6() uint32 {
	if x != nil && x.Unk6 != nil {
		return *x.Unk6
	}
	return 0
}

type FileSetFlags struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileId                `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Flags         *FileId                `protobuf:"bytes,2,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSetFlags) Reset() {
	*x = FileSetFlags{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSetFlags) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSetFlags) ProtoMessage() {}

func (x *FileSetFlags) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSetFlags.ProtoReflect.Descriptor instead.
func (*FileSetFlags) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{2}
}

func (x *FileSetFlags) GetFile() *FileId {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileSetFlags) GetFlags() *FileId {
	if x != nil {
		return x.Flags
	}
	return nil
}

type FileUpdateNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *FileId                `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Flags         *FileId                `protobuf:"bytes,2,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileUpdateNotification) Reset() {
	*x = FileUpdateNotification{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileUpdateNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileUpdateNotification) ProtoMessage() {}

func (x *FileUpdateNotification) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileUpdateNotification.ProtoReflect.Descriptor instead.
func (*FileUpdateNotification) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{3}
}

func (x *FileUpdateNotification) GetFile() *FileId {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileUpdateNotification) GetFlags() *FileId {
	if x != nil {
		return x.Flags
	}
	return nil
}

type FileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          *File                  `protobuf:"bytes,1,opt,name=file" json:"file,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 24
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 0
	Unk4          *uint32                `protobuf:"varint,4,opt,name=unk4" json:"unk4,omitempty"` // 0
	Unk5          *uint32                `protobuf:"varint,5,opt,name=unk5" json:"unk5,omitempty"` // 15
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{4}
}

func (x *FileRequest) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileRequest) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *FileRequest) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *FileRequest) GetUnk4() uint32 {
	if x != nil && x.Unk4 != nil {
		return *x.Unk4
	}
	return 0
}

func (x *FileRequest) GetUnk5() uint32 {
	if x != nil && x.Unk5 != nil {
		return *x.Unk5
	}
	return 0
}

type FileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *uint32                `protobuf:"varint,1,opt,name=status" json:"status,omitempty"` // 0 success 3 failure
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"`     // 0
	Handle        *uint32                `protobuf:"varint,3,opt,name=handle" json:"handle,omitempty"` // varies
	Unk7          *uint32                `protobuf:"varint,7,opt,name=unk7" json:"unk7,omitempty"`     // 11
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{5}
}

func (x *FileResponse) GetStatus() uint32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *FileResponse) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *FileResponse) GetHandle() uint32 {
	if x != nil && x.Handle != nil {
		return *x.Handle
	}
	return 0
}

func (x *FileResponse) GetUnk7() uint32 {
	if x != nil && x.Unk7 != nil {
		return *x.Unk7
	}
	return 0
}

type FileListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set to FileListResponse.cursor_id to continue an in-progress listing.
	// Mutually exclusive with start_page_id: only set one of the two.
	CursorId    *uint32 `protobuf:"varint,1,opt,name=cursor_id,json=cursorId" json:"cursor_id,omitempty"`
	StartPageId *uint32 `protobuf:"varint,2,opt,name=start_page_id,json=startPageId" json:"start_page_id,omitempty"` // 33737
	// Exclusion flags? If we omit this, it sends back already synced files going back months.
	// 0x000000000000a5a5 / 42405 appears to be the "already synced" flag.
	Flags1        *FileId `protobuf:"bytes,4,opt,name=flags1" json:"flags1,omitempty"`
	Flags2        *FileId `protobuf:"bytes,5,opt,name=flags2" json:"flags2,omitempty"` // 0x000000000000a5a5 / 42405
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{6}
}

func (x *FileListRequest) GetCursorId() uint32 {
	if x != nil && x.CursorId != nil {
		return *x.CursorId
	}
	return 0
}

func (x *FileListRequest) GetStartPageId() uint32 {
	if x != nil && x.StartPageId != nil {
		return *x.StartPageId
	}
	return 0
}

func (x *FileListRequest) GetFlags1() *FileId {
	if x != nil {
		return x.Flags1
	}
	return nil
}

func (x *FileListRequest) GetFlags2() *FileId {
	if x != nil {
		return x.Flags2
	}
	return nil
}

type FileListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Unk1  *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 0
	// Present when more items are pending for *this* listing (> 100 items) - send it back
	// on the next FileListRequest.cursor_id to get the remaining items.
	// Mutually exclusive with next_page_id: only one of the two is set.
	CursorId      *uint32 `protobuf:"varint,2,opt,name=cursor_id,json=cursorId" json:"cursor_id,omitempty"`         // 2 on venu 4, 1 on venu 3
	NextPageId    *uint32 `protobuf:"varint,3,opt,name=next_page_id,json=nextPageId" json:"next_page_id,omitempty"` // 33737, incrementing
	File          []*File `protobuf:"bytes,4,rep,name=file" json:"file,omitempty"`
	Unk6          *uint32 `protobuf:"varint,6,opt,name=unk6" json:"unk6,omitempty"` // 1 on venu 4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{7}
}

func (x *FileListResponse) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

func (x *FileListResponse) GetCursorId() uint32 {
	if x != nil && x.CursorId != nil {
		return *x.CursorId
	}
	return 0
}

func (x *FileListResponse) GetNextPageId() uint32 {
	if x != nil && x.NextPageId != nil {
		return *x.NextPageId
	}
	return 0
}

func (x *FileListResponse) GetFile() []*File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileListResponse) GetUnk6() uint32 {
	if x != nil && x.Unk6 != nil {
		return *x.Unk6
	}
	return 0
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *FileId                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Type          *FileType              `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Size          *uint32                `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	PageId        *uint32                `protobuf:"varint,5,opt,name=page_id,json=pageId" json:"page_id,omitempty"` // 33652, 33653, ... incrementing
	Unk4          *uint32                `protobuf:"varint,4,opt,name=unk4" json:"unk4,omitempty"`                   // 0 on venu 4
	Unk6          *uint32                `protobuf:"varint,6,opt,name=unk6" json:"unk6,omitempty"`                   // 2 on venu 4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{8}
}

func (x *File) GetId() *FileId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *File) GetType() *FileType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *File) GetSize() uint32 {
	if x != nil && x.Size != nil {
		return *x.Size
	}
	return 0
}

func (x *File) GetPageId() uint32 {
	if x != nil && x.PageId != nil {
		return *x.PageId
	}
	return 0
}

func (x *File) GetUnk4() uint32 {
	if x != nil && x.Unk4 != nil {
		return *x.Unk4
	}
	return 0
}

func (x *File) GetUnk6() uint32 {
	if x != nil && x.Unk6 != nil {
		return *x.Unk6
	}
	return 0
}

type FileId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id1           *uint64                `protobuf:"fixed64,1,opt,name=id1" json:"id1,omitempty"`
	Id2           *uint64                `protobuf:"fixed64,2,opt,name=id2" json:"id2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileId) Reset() {
	*x = FileId{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileId) ProtoMessage() {}

func (x *FileId) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileId.ProtoReflect.Descriptor instead.
func (*FileId) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{9}
}

func (x *FileId) GetId1() uint64 {
	if x != nil && x.Id1 != nil {
		return *x.Id1
	}
	return 0
}

func (x *FileId) GetId2() uint64 {
	if x != nil && x.Id2 != nil {
		return *x.Id2
	}
	return 0
}

type FileType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 0
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Code          *uint32                `protobuf:"varint,3,opt,name=code" json:"code,omitempty"` // 8 monitor 9 sports
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileType) Reset() {
	*x = FileType{}
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileType) ProtoMessage() {}

func (x *FileType) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_file_sync_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileType.ProtoReflect.Descriptor instead.
func (*FileType) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_file_sync_service_proto_rawDescGZIP(), []int{10}
}

func (x *FileType) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

func (x *FileType) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *FileType) GetCode() uint32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

var File_garmin_gdi_file_sync_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_file_sync_service_proto_rawDesc = "" +
	"\n" +
	"\"garmin/gdi_file_sync_service.proto\x12\x11garmin_vivomovehr\"\xc5\x04\n" +
	"\x0fFileSyncService\x12A\n" +
	"\ffile_request\x18\x01 \x01(\v2\x1e.garmin_vivomovehr.FileRequestR\vfileRequest\x12D\n" +
	"\rfile_response\x18\x02 \x01(\v2\x1f.garmin_vivomovehr.FileResponseR\ffileResponse\x12N\n" +
	"\x11file_list_request\x18\t \x01(\v2\".garmin_vivomovehr.FileListRequestR\x0ffileListRequest\x12Q\n" +
	"\x12file_list_response\x18\n" +
	" \x01(\v2#.garmin_vivomovehr.FileListResponseR\x10fileListResponse\x12Z\n" +
	"\x15new_file_notification\x18\f \x01(\v2&.garmin_vivomovehr.NewFileNotificationR\x13newFileNotification\x12E\n" +
	"\x0efile_set_flags\x18\x0f \x01(\v2\x1f.garmin_vivomovehr.FileSetFlagsR\ffileSetFlags\x12c\n" +
	"\x18file_update_notification\x18\x11 \x01(\v2).garmin_vivomovehr.FileUpdateNotificationR\x16fileUpdateNotification\"\xa6\x01\n" +
	"\x13NewFileNotification\x12+\n" +
	"\x04file\x18\x01 \x03(\v2\x17.garmin_vivomovehr.FileR\x04file\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12\x12\n" +
	"\x04unk4\x18\x04 \x01(\rR\x04unk4\x12\x12\n" +
	"\x04unk5\x18\x05 \x01(\rR\x04unk5\x12\x12\n" +
	"\x04unk6\x18\x06 \x01(\rR\x04unk6\"n\n" +
	"\fFileSetFlags\x12-\n" +
	"\x04file\x18\x01 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x04file\x12/\n" +
	"\x05flags\x18\x02 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x05flags\"x\n" +
	"\x16FileUpdateNotification\x12-\n" +
	"\x04file\x18\x01 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x04file\x12/\n" +
	"\x05flags\x18\x02 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x05flags\"\x8a\x01\n" +
	"\vFileRequest\x12+\n" +
	"\x04file\x18\x01 \x01(\v2\x17.garmin_vivomovehr.FileR\x04file\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12\x12\n" +
	"\x04unk4\x18\x04 \x01(\rR\x04unk4\x12\x12\n" +
	"\x04unk5\x18\x05 \x01(\rR\x04unk5\"f\n" +
	"\fFileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\rR\x06status\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x16\n" +
	"\x06handle\x18\x03 \x01(\rR\x06handle\x12\x12\n" +
	"\x04unk7\x18\a \x01(\rR\x04unk7\"\xb8\x01\n" +
	"\x0fFileListRequest\x12\x1b\n" +
	"\tcursor_id\x18\x01 \x01(\rR\bcursorId\x12\"\n" +
	"\rstart_page_id\x18\x02 \x01(\rR\vstartPageId\x121\n" +
	"\x06flags1\x18\x04 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x06flags1\x121\n" +
	"\x06flags2\x18\x05 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x06flags2\"\xa6\x01\n" +
	"\x10FileListResponse\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x12\x1b\n" +
	"\tcursor_id\x18\x02 \x01(\rR\bcursorId\x12 \n" +
	"\fnext_page_id\x18\x03 \x01(\rR\n" +
	"nextPageId\x12+\n" +
	"\x04file\x18\x04 \x03(\v2\x17.garmin_vivomovehr.FileR\x04file\x12\x12\n" +
	"\x04unk6\x18\x06 \x01(\rR\x04unk6\"\xb7\x01\n" +
	"\x04File\x12)\n" +
	"\x02id\x18\x01 \x01(\v2\x19.garmin_vivomovehr.FileIdR\x02id\x12/\n" +
	"\x04type\x18\x02 \x01(\v2\x1b.garmin_vivomovehr.FileTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x03 \x01(\rR\x04size\x12\x17\n" +
	"\apage_id\x18\x05 \x01(\rR\x06pageId\x12\x12\n" +
	"\x04unk4\x18\x04 \x01(\rR\x04unk4\x12\x12\n" +
	"\x04unk6\x18\x06 \x01(\rR\x04unk6\",\n" +
	"\x06FileId\x12\x10\n" +
	"\x03id1\x18\x01 \x01(\x06R\x03id1\x12\x10\n" +
	"\x03id2\x18\x02 \x01(\x06R\x03id2\"F\n" +
	"\bFileType\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\rR\x04codeBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_file_sync_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_file_sync_service_proto_rawDescData []byte
)

func file_garmin_gdi_file_sync_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_file_sync_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_file_sync_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_file_sync_service_proto_rawDesc), len(file_garmin_gdi_file_sync_service_proto_rawDesc)))
	})
	return file_garmin_gdi_file_sync_service_proto_rawDescData
}

var file_garmin_gdi_file_sync_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_garmin_gdi_file_sync_service_proto_goTypes = []any{
	(*FileSyncService)(nil),        // 0: garmin_vivomovehr.FileSyncService
	(*NewFileNotification)(nil),    // 1: garmin_vivomovehr.NewFileNotification
	(*FileSetFlags)(nil),           // 2: garmin_vivomovehr.FileSetFlags
	(*FileUpdateNotification)(nil), // 3: garmin_vivomovehr.FileUpdateNotification
	(*FileRequest)(nil),            // 4: garmin_vivomovehr.FileRequest
	(*FileResponse)(nil),           // 5: garmin_vivomovehr.FileResponse
	(*FileListRequest)(nil),        // 6: garmin_vivomovehr.FileListRequest
	(*FileListResponse)(nil),       // 7: garmin_vivomovehr.FileListResponse
	(*File)(nil),                   // 8: garmin_vivomovehr.File
	(*FileId)(nil),                 // 9: garmin_vivomovehr.FileId
	(*FileType)(nil),               // 10: garmin_vivomovehr.FileType
}
var file_garmin_gdi_file_sync_service_proto_depIdxs = []int32{
	4,  // 0: garmin_vivomovehr.FileSyncService.file_request:type_name -> garmin_vivomovehr.FileRequest
	5,  // 1: garmin_vivomovehr.FileSyncService.file_response:type_name -> garmin_vivomovehr.FileResponse
	6,  // 2: garmin_vivomovehr.FileSyncService.file_list_request:type_name -> garmin_vivomovehr.FileListRequest
	7,  // 3: garmin_vivomovehr.FileSyncService.file_list_response:type_name -> garmin_vivomovehr.FileListResponse
	1,  // 4: garmin_vivomovehr.FileSyncService.new_file_notification:type_name -> garmin_vivomovehr.NewFileNotification
	2,  // 5: garmin_vivomovehr.FileSyncService.file_set_flags:type_name -> garmin_vivomovehr.FileSetFlags
	3,  // 6: garmin_vivomovehr.FileSyncService.file_update_notification:type_name -> garmin_vivomovehr.FileUpdateNotification
	8,  // 7: garmin_vivomovehr.NewFileNotification.file:type_name -> garmin_vivomovehr.File
	9,  // 8: garmin_vivomovehr.FileSetFlags.file:type_name -> garmin_vivomovehr.FileId
	9,  // 9: garmin_vivomovehr.FileSetFlags.flags:type_name -> garmin_vivomovehr.FileId
	9,  // 10: garmin_vivomovehr.FileUpdateNotification.file:type_name -> garmin_vivomovehr.FileId
	9,  // 11: garmin_vivomovehr.FileUpdateNotification.flags:type_name -> garmin_vivomovehr.FileId
	8,  // 12: garmin_vivomovehr.FileRequest.file:type_name -> garmin_vivomovehr.File
	9,  // 13: garmin_vivomovehr.FileListRequest.flags1:type_name -> garmin_vivomovehr.FileId
	9,  // 14: garmin_vivomovehr.FileListRequest.flags2:type_name -> garmin_vivomovehr.FileId
	8,  // 15: garmin_vivomovehr.FileListResponse.file:type_name -> garmin_vivomovehr.File
	9,  // 16: garmin_vivomovehr.File.id:type_name -> garmin_vivomovehr.FileId
	10, // 17: garmin_vivomovehr.File.type:type_name -> garmin_vivomovehr.FileType
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_garmin_gdi_file_sync_service_proto_init() }
func file_garmin_gdi_file_sync_service_proto_init() {
	if File_garmin_gdi_file_sync_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_file_sync_service_proto_rawDesc), len(file_garmin_gdi_file_sync_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_file_sync_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_file_sync_service_proto_depIdxs,
		MessageInfos:      file_garmin_gdi_file_sync_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_file_sync_service_proto = out.File
	file_garmin_gdi_file_sync_service_proto_goTypes = nil
	file_garmin_gdi_file_sync_service_proto_depIdxs = nil
}
