// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_settings_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_SUCCESS       ResponseStatus = 0
	ResponseStatus_GENERIC_ERROR ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "GENERIC_ERROR",
	}
	ResponseStatus_value = map[string]int32{
		"SUCCESS":       0,
		"GENERIC_ERROR": 1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_settings_service_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_settings_service_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseStatus(num)
	return nil
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{0}
}

type SettingsService struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	DefinitionRequest  *ScreenDefinitionRequest  `protobuf:"bytes,1,opt,name=definitionRequest" json:"definitionRequest,omitempty"`
	DefinitionResponse *ScreenDefinitionResponse `protobuf:"bytes,2,opt,name=definitionResponse" json:"definitionResponse,omitempty"`
	StateRequest       *ScreenStateRequest       `protobuf:"bytes,3,opt,name=stateRequest" json:"stateRequest,omitempty"`
	StateResponse      *ScreenStateResponse      `protobuf:"bytes,4,opt,name=stateResponse" json:"stateResponse,omitempty"`
	ChangeRequest      *ChangeRequest            `protobuf:"bytes,5,opt,name=changeRequest" json:"changeRequest,omitempty"`
	ChangeResponse     *ChangeResponse           `protobuf:"bytes,6,opt,name=changeResponse" json:"changeResponse,omitempty"`
	InitRequest        *InitRequest              `protobuf:"bytes,8,opt,name=initRequest" json:"initRequest,omitempty"`
	InitResponse       *InitResponse             `protobuf:"bytes,9,opt,name=initResponse" json:"initResponse,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SettingsService) Reset() {
	*x = SettingsService{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsService) ProtoMessage() {}

func (x *SettingsService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsService.ProtoReflect.Descriptor instead.
func (*SettingsService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{0}
}

func (x *SettingsService) GetDefinitionRequest() *ScreenDefinitionRequest {
	if x != nil {
		return x.DefinitionRequest
	}
	return nil
}

func (x *SettingsService) GetDefinitionResponse() *ScreenDefinitionResponse {
	if x != nil {
		return x.DefinitionResponse
	}
	return nil
}

func (x *SettingsService) GetStateRequest() *ScreenStateRequest {
	if x != nil {
		return x.StateRequest
	}
	return nil
}

func (x *SettingsService) GetStateResponse() *ScreenStateResponse {
	if x != nil {
		return x.StateResponse
	}
	return nil
}

func (x *SettingsService) GetChangeRequest() *ChangeRequest {
	if x != nil {
		return x.ChangeRequest
	}
	return nil
}

func (x *SettingsService) GetChangeResponse() *ChangeResponse {
	if x != nil {
		return x.ChangeResponse
	}
	return nil
}

func (x *SettingsService) GetInitRequest() *InitRequest {
	if x != nil {
		return x.InitRequest
	}
	return nil
}

func (x *SettingsService) GetInitResponse() *InitResponse {
	if x != nil {
		return x.InitResponse
	}
	return nil
}

type ScreenDefinitionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      *uint32                `protobuf:"varint,1,opt,name=screenId" json:"screenId,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"`        // 0
	Language      *string                `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"` // en_US
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenDefinitionRequest) Reset() {
	*x = ScreenDefinitionRequest{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenDefinitionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenDefinitionRequest) ProtoMessage() {}

func (x *ScreenDefinitionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenDefinitionRequest.ProtoReflect.Descriptor instead.
func (*ScreenDefinitionRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{1}
}

func (x *ScreenDefinitionRequest) GetScreenId() uint32 {
	if x != nil && x.ScreenId != nil {
		return *x.ScreenId
	}
	return 0
}

func (x *ScreenDefinitionRequest) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *ScreenDefinitionRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

type ScreenDefinitionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 0, status?
	Definition    *ScreenDefinition      `protobuf:"bytes,2,opt,name=definition" json:"definition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenDefinitionResponse) Reset() {
	*x = ScreenDefinitionResponse{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenDefinitionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenDefinitionResponse) ProtoMessage() {}

func (x *ScreenDefinitionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenDefinitionResponse.ProtoReflect.Descriptor instead.
func (*ScreenDefinitionResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{2}
}

func (x *ScreenDefinitionResponse) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

func (x *ScreenDefinitionResponse) GetDefinition() *ScreenDefinition {
	if x != nil {
		return x.Definition
	}
	return nil
}

type ScreenDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      *uint32                `protobuf:"varint,1,opt,name=screenId" json:"screenId,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 0
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 928002
	Title         *Label                 `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Entry         []*ScreenEntry         `protobuf:"bytes,5,rep,name=entry" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenDefinition) Reset() {
	*x = ScreenDefinition{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenDefinition) ProtoMessage() {}

func (x *ScreenDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenDefinition.ProtoReflect.Descriptor instead.
func (*ScreenDefinition) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{3}
}

func (x *ScreenDefinition) GetScreenId() uint32 {
	if x != nil && x.ScreenId != nil {
		return *x.ScreenId
	}
	return 0
}

func (x *ScreenDefinition) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *ScreenDefinition) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *ScreenDefinition) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ScreenDefinition) GetEntry() []*ScreenEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Text          *string                `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{4}
}

func (x *Label) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Label) GetText() string {
	if x != nil && x.Text != nil {
		return *x.Text
	}
	return ""
}

type ScreenEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type          *uint32                `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Title         *Label                 `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Icon          *uint32                `protobuf:"varint,5,opt,name=icon" json:"icon,omitempty"`
	Target        *Target                `protobuf:"bytes,9,opt,name=target" json:"target,omitempty"`
	SortOptions   *SortOptions           `protobuf:"bytes,12,opt,name=sortOptions" json:"sortOptions,omitempty"`
	TextOption    *TextOption            `protobuf:"bytes,13,opt,name=textOption" json:"textOption,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenEntry) Reset() {
	*x = ScreenEntry{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenEntry) ProtoMessage() {}

func (x *ScreenEntry) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenEntry.ProtoReflect.Descriptor instead.
func (*ScreenEntry) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{5}
}

func (x *ScreenEntry) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ScreenEntry) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *ScreenEntry) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ScreenEntry) GetIcon() uint32 {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return 0
}

func (x *ScreenEntry) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ScreenEntry) GetSortOptions() *SortOptions {
	if x != nil {
		return x.SortOptions
	}
	return nil
}

func (x *ScreenEntry) GetTextOption() *TextOption {
	if x != nil {
		return x.TextOption
	}
	return nil
}

type SortOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 1
	Entries       []*SortEntry           `protobuf:"bytes,5,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortOptions) Reset() {
	*x = SortOptions{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortOptions) ProtoMessage() {}

func (x *SortOptions) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortOptions.ProtoReflect.Descriptor instead.
func (*SortOptions) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{6}
}

func (x *SortOptions) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *SortOptions) GetEntries() []*SortEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type SortEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title         *Label                 `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Unk5          *uint32                `protobuf:"varint,5,opt,name=unk5" json:"unk5,omitempty"` // 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SortEntry) Reset() {
	*x = SortEntry{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SortEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortEntry) ProtoMessage() {}

func (x *SortEntry) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortEntry.ProtoReflect.Descriptor instead.
func (*SortEntry) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{7}
}

func (x *SortEntry) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *SortEntry) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SortEntry) GetUnk5() uint32 {
	if x != nil && x.Unk5 != nil {
		return *x.Unk5
	}
	return 0
}

type TextOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limits        *TextLimits            `protobuf:"bytes,1,opt,name=limits" json:"limits,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextOption) Reset() {
	*x = TextOption{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextOption) ProtoMessage() {}

func (x *TextOption) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextOption.ProtoReflect.Descriptor instead.
func (*TextOption) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{8}
}

func (x *TextOption) GetLimits() *TextLimits {
	if x != nil {
		return x.Limits
	}
	return nil
}

func (x *TextOption) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

type TextLimits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxLength     *uint32                `protobuf:"varint,1,opt,name=maxLength" json:"maxLength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextLimits) Reset() {
	*x = TextLimits{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextLimits) ProtoMessage() {}

func (x *TextLimits) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextLimits.ProtoReflect.Descriptor instead.
func (*TextLimits) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{9}
}

func (x *TextLimits) GetMaxLength() uint32 {
	if x != nil && x.MaxLength != nil {
		return *x.MaxLength
	}
	return 0
}

type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          *uint32                `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`           // 0 subscreen, 1 list preference, 6 other activity, 7 hidden, 9 subscreen with options
	Subscreen     *uint32                `protobuf:"varint,2,opt,name=subscreen" json:"subscreen,omitempty"` // when 0
	Activity      *uint32                `protobuf:"varint,3,opt,name=activity" json:"activity,omitempty"`   // when 6
	Options       *TargetOptions         `protobuf:"bytes,4,opt,name=options" json:"options,omitempty"`      // when 1
	NumberPicker  *TargetNumberPicker    `protobuf:"bytes,8,opt,name=numberPicker" json:"numberPicker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{10}
}

func (x *Target) GetType() uint32 {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return 0
}

func (x *Target) GetSubscreen() uint32 {
	if x != nil && x.Subscreen != nil {
		return *x.Subscreen
	}
	return 0
}

func (x *Target) GetActivity() uint32 {
	if x != nil && x.Activity != nil {
		return *x.Activity
	}
	return 0
}

func (x *Target) GetOptions() *TargetOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Target) GetNumberPicker() *TargetNumberPicker {
	if x != nil {
		return x.NumberPicker
	}
	return nil
}

type ScreenStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      *uint32                `protobuf:"varint,1,opt,name=screenId" json:"screenId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStateRequest) Reset() {
	*x = ScreenStateRequest{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStateRequest) ProtoMessage() {}

func (x *ScreenStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStateRequest.ProtoReflect.Descriptor instead.
func (*ScreenStateRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{11}
}

func (x *ScreenStateRequest) GetScreenId() uint32 {
	if x != nil && x.ScreenId != nil {
		return *x.ScreenId
	}
	return 0
}

type TargetOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Option        []*TargetOptionEntry   `protobuf:"bytes,1,rep,name=option" json:"option,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetOptions) Reset() {
	*x = TargetOptions{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetOptions) ProtoMessage() {}

func (x *TargetOptions) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetOptions.ProtoReflect.Descriptor instead.
func (*TargetOptions) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{12}
}

func (x *TargetOptions) GetOption() []*TargetOptionEntry {
	if x != nil {
		return x.Option
	}
	return nil
}

type TargetOptionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *Label                 `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetOptionEntry) Reset() {
	*x = TargetOptionEntry{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetOptionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetOptionEntry) ProtoMessage() {}

func (x *TargetOptionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetOptionEntry.ProtoReflect.Descriptor instead.
func (*TargetOptionEntry) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{13}
}

func (x *TargetOptionEntry) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

type TargetNumberPicker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           *uint32                `protobuf:"varint,1,opt,name=min" json:"min,omitempty"`
	Max           *uint32                `protobuf:"varint,2,opt,name=max" json:"max,omitempty"`
	Step          *uint32                `protobuf:"varint,3,opt,name=step" json:"step,omitempty"` // maybe? 1 on weight
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TargetNumberPicker) Reset() {
	*x = TargetNumberPicker{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetNumberPicker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetNumberPicker) ProtoMessage() {}

func (x *TargetNumberPicker) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetNumberPicker.ProtoReflect.Descriptor instead.
func (*TargetNumberPicker) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{14}
}

func (x *TargetNumberPicker) GetMin() uint32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *TargetNumberPicker) GetMax() uint32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *TargetNumberPicker) GetStep() uint32 {
	if x != nil && x.Step != nil {
		return *x.Step
	}
	return 0
}

type ScreenStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 0
	State         *ScreenState           `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStateResponse) Reset() {
	*x = ScreenStateResponse{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStateResponse) ProtoMessage() {}

func (x *ScreenStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStateResponse.ProtoReflect.Descriptor instead.
func (*ScreenStateResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{15}
}

func (x *ScreenStateResponse) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

func (x *ScreenStateResponse) GetState() *ScreenState {
	if x != nil {
		return x.State
	}
	return nil
}

type ScreenState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ScreenId      *uint32                `protobuf:"varint,1,opt,name=screenId" json:"screenId,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 0
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 928002
	State         []*EntryState          `protobuf:"bytes,4,rep,name=state" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenState) Reset() {
	*x = ScreenState{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenState) ProtoMessage() {}

func (x *ScreenState) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenState.ProtoReflect.Descriptor instead.
func (*ScreenState) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{16}
}

func (x *ScreenState) GetScreenId() uint32 {
	if x != nil && x.ScreenId != nil {
		return *x.ScreenId
	}
	return 0
}

func (x *ScreenState) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

func (x *ScreenState) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *ScreenState) GetState() []*EntryState {
	if x != nil {
		return x.State
	}
	return nil
}

type EntryState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	State         *uint32                `protobuf:"varint,2,opt,name=state" json:"state,omitempty"`
	Switch        *Switch                `protobuf:"bytes,3,opt,name=switch" json:"switch,omitempty"`
	Summary       *Summary               `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntryState) Reset() {
	*x = EntryState{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntryState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntryState) ProtoMessage() {}

func (x *EntryState) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntryState.ProtoReflect.Descriptor instead.
func (*EntryState) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{17}
}

func (x *EntryState) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *EntryState) GetState() uint32 {
	if x != nil && x.State != nil {
		return *x.State
	}
	return 0
}

func (x *EntryState) GetSwitch() *Switch {
	if x != nil {
		return x.Switch
	}
	return nil
}

func (x *EntryState) GetSummary() *Summary {
	if x != nil {
		return x.Summary
	}
	return nil
}

type Switch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	Title         *Label                 `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Switch) Reset() {
	*x = Switch{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Switch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Switch) ProtoMessage() {}

func (x *Switch) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Switch.ProtoReflect.Descriptor instead.
func (*Switch) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{18}
}

func (x *Switch) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *Switch) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

type Summary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *Label                 `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	ValueList     *ValueList             `protobuf:"bytes,2,opt,name=valueList" json:"valueList,omitempty"`
	ValueTime     *ValueTime             `protobuf:"bytes,4,opt,name=valueTime" json:"valueTime,omitempty"`
	ValueNumber   *ValueNumber           `protobuf:"bytes,6,opt,name=valueNumber" json:"valueNumber,omitempty"`
	ValueDate     *ValueDate             `protobuf:"bytes,8,opt,name=valueDate" json:"valueDate,omitempty"`
	ValueHeight   *ValueHeight           `protobuf:"bytes,10,opt,name=valueHeight" json:"valueHeight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summary) Reset() {
	*x = Summary{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summary) ProtoMessage() {}

func (x *Summary) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summary.ProtoReflect.Descriptor instead.
func (*Summary) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{19}
}

func (x *Summary) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Summary) GetValueList() *ValueList {
	if x != nil {
		return x.ValueList
	}
	return nil
}

func (x *Summary) GetValueTime() *ValueTime {
	if x != nil {
		return x.ValueTime
	}
	return nil
}

func (x *Summary) GetValueNumber() *ValueNumber {
	if x != nil {
		return x.ValueNumber
	}
	return nil
}

func (x *Summary) GetValueDate() *ValueDate {
	if x != nil {
		return x.ValueDate
	}
	return nil
}

func (x *Summary) GetValueHeight() *ValueHeight {
	if x != nil {
		return x.ValueHeight
	}
	return nil
}

type ValueList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *uint32                `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueList) Reset() {
	*x = ValueList{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueList) ProtoMessage() {}

func (x *ValueList) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueList.ProtoReflect.Descriptor instead.
func (*ValueList) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{20}
}

func (x *ValueList) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type ValueTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       *uint32                `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	TimeFormat    *uint32                `protobuf:"varint,3,opt,name=timeFormat" json:"timeFormat,omitempty"` // 0 12h, 1 24h
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueTime) Reset() {
	*x = ValueTime{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueTime) ProtoMessage() {}

func (x *ValueTime) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueTime.ProtoReflect.Descriptor instead.
func (*ValueTime) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{21}
}

func (x *ValueTime) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

func (x *ValueTime) GetTimeFormat() uint32 {
	if x != nil && x.TimeFormat != nil {
		return *x.TimeFormat
	}
	return 0
}

type ValueNumber struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Subtitle      *Label                 `protobuf:"bytes,2,opt,name=subtitle" json:"subtitle,omitempty"`
	Title         *Label                 `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Unit          *Label                 `protobuf:"bytes,4,opt,name=unit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueNumber) Reset() {
	*x = ValueNumber{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueNumber) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueNumber) ProtoMessage() {}

func (x *ValueNumber) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueNumber.ProtoReflect.Descriptor instead.
func (*ValueNumber) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{22}
}

func (x *ValueNumber) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ValueNumber) GetSubtitle() *Label {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *ValueNumber) GetTitle() *Label {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *ValueNumber) GetUnit() *Label {
	if x != nil {
		return x.Unit
	}
	return nil
}

type ValueDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subtitle      *Label                 `protobuf:"bytes,1,opt,name=subtitle" json:"subtitle,omitempty"`
	CurrentDate   *Date                  `protobuf:"bytes,2,opt,name=currentDate" json:"currentDate,omitempty"`
	MinDate       *Date                  `protobuf:"bytes,3,opt,name=minDate" json:"minDate,omitempty"`
	MaxDate       *Date                  `protobuf:"bytes,4,opt,name=maxDate" json:"maxDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueDate) Reset() {
	*x = ValueDate{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueDate) ProtoMessage() {}

func (x *ValueDate) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueDate.ProtoReflect.Descriptor instead.
func (*ValueDate) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{23}
}

func (x *ValueDate) GetSubtitle() *Label {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *ValueDate) GetCurrentDate() *Date {
	if x != nil {
		return x.CurrentDate
	}
	return nil
}

func (x *ValueDate) GetMinDate() *Date {
	if x != nil {
		return x.MinDate
	}
	return nil
}

func (x *ValueDate) GetMaxDate() *Date {
	if x != nil {
		return x.MaxDate
	}
	return nil
}

type ValueHeight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subtitle      *Label                 `protobuf:"bytes,1,opt,name=subtitle" json:"subtitle,omitempty"`
	Value         *uint32                `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	Unit          *uint32                `protobuf:"varint,3,opt,name=unit" json:"unit,omitempty"` // 0 cm
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueHeight) Reset() {
	*x = ValueHeight{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueHeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueHeight) ProtoMessage() {}

func (x *ValueHeight) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueHeight.ProtoReflect.Descriptor instead.
func (*ValueHeight) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{24}
}

func (x *ValueHeight) GetSubtitle() *Label {
	if x != nil {
		return x.Subtitle
	}
	return nil
}

func (x *ValueHeight) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ValueHeight) GetUnit() uint32 {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return 0
}

type Date struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Month         *uint32                `protobuf:"varint,1,opt,name=month" json:"month,omitempty"`
	Day           *uint32                `protobuf:"varint,2,opt,name=day" json:"day,omitempty"`
	Year          *uint32                `protobuf:"varint,3,opt,name=year" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Date) Reset() {
	*x = Date{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Date) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Date) ProtoMessage() {}

func (x *Date) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Date.ProtoReflect.Descriptor instead.
func (*Date) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{25}
}

func (x *Date) GetMonth() uint32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *Date) GetDay() uint32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

func (x *Date) GetYear() uint32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

type ChangeRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ScreenId      *uint32                 `protobuf:"varint,1,opt,name=screenId" json:"screenId,omitempty"`
	EntryId       *uint32                 `protobuf:"varint,2,opt,name=entryId" json:"entryId,omitempty"`
	Switch        *ChangeRequest_Switch   `protobuf:"bytes,3,opt,name=switch" json:"switch,omitempty"`
	Option        *ChangeRequest_Option   `protobuf:"bytes,4,opt,name=option" json:"option,omitempty"`
	Time          *ChangeRequest_Time     `protobuf:"bytes,6,opt,name=time" json:"time,omitempty"`
	Number        *ChangeRequest_Number   `protobuf:"bytes,8,opt,name=number" json:"number,omitempty"`
	Position      *ChangeRequest_Position `protobuf:"bytes,11,opt,name=position" json:"position,omitempty"`
	NewDate       *ChangeRequest_NewDate  `protobuf:"bytes,12,opt,name=newDate" json:"newDate,omitempty"`
	Text          *ChangeRequest_Text     `protobuf:"bytes,14,opt,name=text" json:"text,omitempty"`
	Height        *ChangeRequest_Height   `protobuf:"bytes,15,opt,name=height" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest) Reset() {
	*x = ChangeRequest{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest) ProtoMessage() {}

func (x *ChangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest.ProtoReflect.Descriptor instead.
func (*ChangeRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26}
}

func (x *ChangeRequest) GetScreenId() uint32 {
	if x != nil && x.ScreenId != nil {
		return *x.ScreenId
	}
	return 0
}

func (x *ChangeRequest) GetEntryId() uint32 {
	if x != nil && x.EntryId != nil {
		return *x.EntryId
	}
	return 0
}

func (x *ChangeRequest) GetSwitch() *ChangeRequest_Switch {
	if x != nil {
		return x.Switch
	}
	return nil
}

func (x *ChangeRequest) GetOption() *ChangeRequest_Option {
	if x != nil {
		return x.Option
	}
	return nil
}

func (x *ChangeRequest) GetTime() *ChangeRequest_Time {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *ChangeRequest) GetNumber() *ChangeRequest_Number {
	if x != nil {
		return x.Number
	}
	return nil
}

func (x *ChangeRequest) GetPosition() *ChangeRequest_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *ChangeRequest) GetNewDate() *ChangeRequest_NewDate {
	if x != nil {
		return x.NewDate
	}
	return nil
}

func (x *ChangeRequest) GetText() *ChangeRequest_Text {
	if x != nil {
		return x.Text
	}
	return nil
}

func (x *ChangeRequest) GetHeight() *ChangeRequest_Height {
	if x != nil {
		return x.Height
	}
	return nil
}

type ChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *ResponseStatus        `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.ResponseStatus" json:"status,omitempty"`
	State         *ScreenState           `protobuf:"bytes,3,opt,name=state" json:"state,omitempty"`
	ShouldReturn  *bool                  `protobuf:"varint,5,opt,name=shouldReturn" json:"shouldReturn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeResponse) Reset() {
	*x = ChangeResponse{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeResponse) ProtoMessage() {}

func (x *ChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeResponse.ProtoReflect.Descriptor instead.
func (*ChangeResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{27}
}

func (x *ChangeResponse) GetStatus() ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ResponseStatus_SUCCESS
}

func (x *ChangeResponse) GetState() *ScreenState {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *ChangeResponse) GetShouldReturn() bool {
	if x != nil && x.ShouldReturn != nil {
		return *x.ShouldReturn
	}
	return false
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      *string                `protobuf:"bytes,1,opt,name=language" json:"language,omitempty"` // en_US
	Region        *string                `protobuf:"bytes,2,opt,name=region" json:"region,omitempty"`     // us
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{28}
}

func (x *InitRequest) GetLanguage() string {
	if x != nil && x.Language != nil {
		return *x.Language
	}
	return ""
}

func (x *InitRequest) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *string                `protobuf:"bytes,1,opt,name=unk1" json:"unk1,omitempty"`
	Unk2          *string                `protobuf:"bytes,2,opt,name=unk2" json:"unk2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{29}
}

func (x *InitResponse) GetUnk1() string {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return ""
}

func (x *InitResponse) GetUnk2() string {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return ""
}

type ChangeRequest_Switch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *bool                  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Switch) Reset() {
	*x = ChangeRequest_Switch{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Switch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Switch) ProtoMessage() {}

func (x *ChangeRequest_Switch) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Switch.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Switch) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 0}
}

func (x *ChangeRequest_Switch) GetValue() bool {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return false
}

type ChangeRequest_Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *uint32                `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Option) Reset() {
	*x = ChangeRequest_Option{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Option) ProtoMessage() {}

func (x *ChangeRequest_Option) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Option.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Option) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 1}
}

func (x *ChangeRequest_Option) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type ChangeRequest_Time struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seconds       *uint32                `protobuf:"varint,1,opt,name=seconds" json:"seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Time) Reset() {
	*x = ChangeRequest_Time{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Time) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Time) ProtoMessage() {}

func (x *ChangeRequest_Time) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Time.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Time) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 2}
}

func (x *ChangeRequest_Time) GetSeconds() uint32 {
	if x != nil && x.Seconds != nil {
		return *x.Seconds
	}
	return 0
}

type ChangeRequest_Number struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Number) Reset() {
	*x = ChangeRequest_Number{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Number) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Number) ProtoMessage() {}

func (x *ChangeRequest_Number) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Number.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Number) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 3}
}

func (x *ChangeRequest_Number) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

type ChangeRequest_Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         *uint32                `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	Delete        *bool                  `protobuf:"varint,2,opt,name=delete" json:"delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Position) Reset() {
	*x = ChangeRequest_Position{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Position) ProtoMessage() {}

func (x *ChangeRequest_Position) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Position.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Position) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 4}
}

func (x *ChangeRequest_Position) GetIndex() uint32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

func (x *ChangeRequest_Position) GetDelete() bool {
	if x != nil && x.Delete != nil {
		return *x.Delete
	}
	return false
}

type ChangeRequest_NewDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Date                  `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_NewDate) Reset() {
	*x = ChangeRequest_NewDate{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_NewDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_NewDate) ProtoMessage() {}

func (x *ChangeRequest_NewDate) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_NewDate.ProtoReflect.Descriptor instead.
func (*ChangeRequest_NewDate) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 5}
}

func (x *ChangeRequest_NewDate) GetValue() *Date {
	if x != nil {
		return x.Value
	}
	return nil
}

type ChangeRequest_Text struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *string                `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Text) Reset() {
	*x = ChangeRequest_Text{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Text) ProtoMessage() {}

func (x *ChangeRequest_Text) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Text.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Text) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 6}
}

func (x *ChangeRequest_Text) GetValue() string {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return ""
}

type ChangeRequest_Height struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *uint32                `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Unit          *uint32                `protobuf:"varint,2,opt,name=unit" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeRequest_Height) Reset() {
	*x = ChangeRequest_Height{}
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeRequest_Height) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeRequest_Height) ProtoMessage() {}

func (x *ChangeRequest_Height) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_settings_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeRequest_Height.ProtoReflect.Descriptor instead.
func (*ChangeRequest_Height) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_settings_service_proto_rawDescGZIP(), []int{26, 7}
}

func (x *ChangeRequest_Height) GetValue() uint32 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

func (x *ChangeRequest_Height) GetUnit() uint32 {
	if x != nil && x.Unit != nil {
		return *x.Unit
	}
	return 0
}

var File_garmin_gdi_settings_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_settings_service_proto_rawDesc = "" +
	"\n" +
	"!garmin/gdi_settings_service.proto\x12\x11garmin_vivomovehr\"\xfb\x04\n" +
	"\x0fSettingsService\x12X\n" +
	"\x11definitionRequest\x18\x01 \x01(\v2*.garmin_vivomovehr.ScreenDefinitionRequestR\x11definitionRequest\x12[\n" +
	"\x12definitionResponse\x18\x02 \x01(\v2+.garmin_vivomovehr.ScreenDefinitionResponseR\x12definitionResponse\x12I\n" +
	"\fstateRequest\x18\x03 \x01(\v2%.garmin_vivomovehr.ScreenStateRequestR\fstateRequest\x12L\n" +
	"\rstateResponse\x18\x04 \x01(\v2&.garmin_vivomovehr.ScreenStateResponseR\rstateResponse\x12F\n" +
	"\rchangeRequest\x18\x05 \x01(\v2 .garmin_vivomovehr.ChangeRequestR\rchangeRequest\x12I\n" +
	"\x0echangeResponse\x18\x06 \x01(\v2!.garmin_vivomovehr.ChangeResponseR\x0echangeResponse\x12@\n" +
	"\vinitRequest\x18\b \x01(\v2\x1e.garmin_vivomovehr.InitRequestR\vinitRequest\x12C\n" +
	"\finitResponse\x18\t \x01(\v2\x1f.garmin_vivomovehr.InitResponseR\finitResponse\"e\n" +
	"\x17ScreenDefinitionRequest\x12\x1a\n" +
	"\bscreenId\x18\x01 \x01(\rR\bscreenId\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\"s\n" +
	"\x18ScreenDefinitionResponse\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x12C\n" +
	"\n" +
	"definition\x18\x02 \x01(\v2#.garmin_vivomovehr.ScreenDefinitionR\n" +
	"definition\"\xbc\x01\n" +
	"\x10ScreenDefinition\x12\x1a\n" +
	"\bscreenId\x18\x01 \x01(\rR\bscreenId\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12.\n" +
	"\x05title\x18\x04 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\x124\n" +
	"\x05entry\x18\x05 \x03(\v2\x1e.garmin_vivomovehr.ScreenEntryR\x05entry\"+\n" +
	"\x05Label\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\xa9\x02\n" +
	"\vScreenEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\rR\x04type\x12.\n" +
	"\x05title\x18\x03 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\x12\x12\n" +
	"\x04icon\x18\x05 \x01(\rR\x04icon\x121\n" +
	"\x06target\x18\t \x01(\v2\x19.garmin_vivomovehr.TargetR\x06target\x12@\n" +
	"\vsortOptions\x18\f \x01(\v2\x1e.garmin_vivomovehr.SortOptionsR\vsortOptions\x12=\n" +
	"\n" +
	"textOption\x18\r \x01(\v2\x1d.garmin_vivomovehr.TextOptionR\n" +
	"textOption\"Y\n" +
	"\vSortOptions\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x126\n" +
	"\aentries\x18\x05 \x03(\v2\x1c.garmin_vivomovehr.SortEntryR\aentries\"_\n" +
	"\tSortEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12.\n" +
	"\x05title\x18\x02 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\x12\x12\n" +
	"\x04unk5\x18\x05 \x01(\rR\x04unk5\"W\n" +
	"\n" +
	"TextOption\x125\n" +
	"\x06limits\x18\x01 \x01(\v2\x1d.garmin_vivomovehr.TextLimitsR\x06limits\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\"*\n" +
	"\n" +
	"TextLimits\x12\x1c\n" +
	"\tmaxLength\x18\x01 \x01(\rR\tmaxLength\"\xdd\x01\n" +
	"\x06Target\x12\x12\n" +
	"\x04type\x18\x01 \x01(\rR\x04type\x12\x1c\n" +
	"\tsubscreen\x18\x02 \x01(\rR\tsubscreen\x12\x1a\n" +
	"\bactivity\x18\x03 \x01(\rR\bactivity\x12:\n" +
	"\aoptions\x18\x04 \x01(\v2 .garmin_vivomovehr.TargetOptionsR\aoptions\x12I\n" +
	"\fnumberPicker\x18\b \x01(\v2%.garmin_vivomovehr.TargetNumberPickerR\fnumberPicker\"0\n" +
	"\x12ScreenStateRequest\x12\x1a\n" +
	"\bscreenId\x18\x01 \x01(\rR\bscreenId\"M\n" +
	"\rTargetOptions\x12<\n" +
	"\x06option\x18\x01 \x03(\v2$.garmin_vivomovehr.TargetOptionEntryR\x06option\"C\n" +
	"\x11TargetOptionEntry\x12.\n" +
	"\x05title\x18\x03 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\"L\n" +
	"\x12TargetNumberPicker\x12\x10\n" +
	"\x03min\x18\x01 \x01(\rR\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\rR\x03max\x12\x12\n" +
	"\x04step\x18\x03 \x01(\rR\x04step\"_\n" +
	"\x13ScreenStateResponse\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\x124\n" +
	"\x05state\x18\x02 \x01(\v2\x1e.garmin_vivomovehr.ScreenStateR\x05state\"\x86\x01\n" +
	"\vScreenState\x12\x1a\n" +
	"\bscreenId\x18\x01 \x01(\rR\bscreenId\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x123\n" +
	"\x05state\x18\x04 \x03(\v2\x1d.garmin_vivomovehr.EntryStateR\x05state\"\x9b\x01\n" +
	"\n" +
	"EntryState\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05state\x18\x02 \x01(\rR\x05state\x121\n" +
	"\x06switch\x18\x03 \x01(\v2\x19.garmin_vivomovehr.SwitchR\x06switch\x124\n" +
	"\asummary\x18\x04 \x01(\v2\x1a.garmin_vivomovehr.SummaryR\asummary\"R\n" +
	"\x06Switch\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12.\n" +
	"\x05title\x18\x02 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\"\xf1\x02\n" +
	"\aSummary\x12.\n" +
	"\x05title\x18\x01 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\x12:\n" +
	"\tvalueList\x18\x02 \x01(\v2\x1c.garmin_vivomovehr.ValueListR\tvalueList\x12:\n" +
	"\tvalueTime\x18\x04 \x01(\v2\x1c.garmin_vivomovehr.ValueTimeR\tvalueTime\x12@\n" +
	"\vvalueNumber\x18\x06 \x01(\v2\x1e.garmin_vivomovehr.ValueNumberR\vvalueNumber\x12:\n" +
	"\tvalueDate\x18\b \x01(\v2\x1c.garmin_vivomovehr.ValueDateR\tvalueDate\x12@\n" +
	"\vvalueHeight\x18\n" +
	" \x01(\v2\x1e.garmin_vivomovehr.ValueHeightR\vvalueHeight\"!\n" +
	"\tValueList\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\"E\n" +
	"\tValueTime\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\rR\aseconds\x12\x1e\n" +
	"\n" +
	"timeFormat\x18\x03 \x01(\rR\n" +
	"timeFormat\"\xb7\x01\n" +
	"\vValueNumber\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x124\n" +
	"\bsubtitle\x18\x02 \x01(\v2\x18.garmin_vivomovehr.LabelR\bsubtitle\x12.\n" +
	"\x05title\x18\x03 \x01(\v2\x18.garmin_vivomovehr.LabelR\x05title\x12,\n" +
	"\x04unit\x18\x04 \x01(\v2\x18.garmin_vivomovehr.LabelR\x04unit\"\xe2\x01\n" +
	"\tValueDate\x124\n" +
	"\bsubtitle\x18\x01 \x01(\v2\x18.garmin_vivomovehr.LabelR\bsubtitle\x129\n" +
	"\vcurrentDate\x18\x02 \x01(\v2\x17.garmin_vivomovehr.DateR\vcurrentDate\x121\n" +
	"\aminDate\x18\x03 \x01(\v2\x17.garmin_vivomovehr.DateR\aminDate\x121\n" +
	"\amaxDate\x18\x04 \x01(\v2\x17.garmin_vivomovehr.DateR\amaxDate\"m\n" +
	"\vValueHeight\x124\n" +
	"\bsubtitle\x18\x01 \x01(\v2\x18.garmin_vivomovehr.LabelR\bsubtitle\x12\x14\n" +
	"\x05value\x18\x02 \x01(\rR\x05value\x12\x12\n" +
	"\x04unit\x18\x03 \x01(\rR\x04unit\"B\n" +
	"\x04Date\x12\x14\n" +
	"\x05month\x18\x01 \x01(\rR\x05month\x12\x10\n" +
	"\x03day\x18\x02 \x01(\rR\x03day\x12\x12\n" +
	"\x04year\x18\x03 \x01(\rR\x04year\"\x92\a\n" +
	"\rChangeRequest\x12\x1a\n" +
	"\bscreenId\x18\x01 \x01(\rR\bscreenId\x12\x18\n" +
	"\aentryId\x18\x02 \x01(\rR\aentryId\x12?\n" +
	"\x06switch\x18\x03 \x01(\v2'.garmin_vivomovehr.ChangeRequest.SwitchR\x06switch\x12?\n" +
	"\x06option\x18\x04 \x01(\v2'.garmin_vivomovehr.ChangeRequest.OptionR\x06option\x129\n" +
	"\x04time\x18\x06 \x01(\v2%.garmin_vivomovehr.ChangeRequest.TimeR\x04time\x12?\n" +
	"\x06number\x18\b \x01(\v2'.garmin_vivomovehr.ChangeRequest.NumberR\x06number\x12E\n" +
	"\bposition\x18\v \x01(\v2).garmin_vivomovehr.ChangeRequest.PositionR\bposition\x12B\n" +
	"\anewDate\x18\f \x01(\v2(.garmin_vivomovehr.ChangeRequest.NewDateR\anewDate\x129\n" +
	"\x04text\x18\x0e \x01(\v2%.garmin_vivomovehr.ChangeRequest.TextR\x04text\x12?\n" +
	"\x06height\x18\x0f \x01(\v2'.garmin_vivomovehr.ChangeRequest.HeightR\x06height\x1a\x1e\n" +
	"\x06Switch\x12\x14\n" +
	"\x05value\x18\x01 \x02(\bR\x05value\x1a\x1e\n" +
	"\x06Option\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x1a \n" +
	"\x04Time\x12\x18\n" +
	"\aseconds\x18\x01 \x01(\rR\aseconds\x1a\x1e\n" +
	"\x06Number\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x1a8\n" +
	"\bPosition\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x16\n" +
	"\x06delete\x18\x02 \x01(\bR\x06delete\x1a8\n" +
	"\aNewDate\x12-\n" +
	"\x05value\x18\x01 \x01(\v2\x17.garmin_vivomovehr.DateR\x05value\x1a\x1c\n" +
	"\x04Text\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x1a2\n" +
	"\x06Height\x12\x14\n" +
	"\x05value\x18\x01 \x01(\rR\x05value\x12\x12\n" +
	"\x04unit\x18\x02 \x01(\rR\x04unit\"\xa5\x01\n" +
	"\x0eChangeResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.garmin_vivomovehr.ResponseStatusR\x06status\x124\n" +
	"\x05state\x18\x03 \x01(\v2\x1e.garmin_vivomovehr.ScreenStateR\x05state\x12\"\n" +
	"\fshouldReturn\x18\x05 \x01(\bR\fshouldReturn\"A\n" +
	"\vInitRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\"6\n" +
	"\fInitResponse\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\tR\x04unk1\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\tR\x04unk2*0\n" +
	"\x0eResponseStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rGENERIC_ERROR\x10\x01BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_settings_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_settings_service_proto_rawDescData []byte
)

func file_garmin_gdi_settings_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_settings_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_settings_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_settings_service_proto_rawDesc), len(file_garmin_gdi_settings_service_proto_rawDesc)))
	})
	return file_garmin_gdi_settings_service_proto_rawDescData
}

var file_garmin_gdi_settings_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_garmin_gdi_settings_service_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_garmin_gdi_settings_service_proto_goTypes = []any{
	(ResponseStatus)(0),              // 0: garmin_vivomovehr.ResponseStatus
	(*SettingsService)(nil),          // 1: garmin_vivomovehr.SettingsService
	(*ScreenDefinitionRequest)(nil),  // 2: garmin_vivomovehr.ScreenDefinitionRequest
	(*ScreenDefinitionResponse)(nil), // 3: garmin_vivomovehr.ScreenDefinitionResponse
	(*ScreenDefinition)(nil),         // 4: garmin_vivomovehr.ScreenDefinition
	(*Label)(nil),                    // 5: garmin_vivomovehr.Label
	(*ScreenEntry)(nil),              // 6: garmin_vivomovehr.ScreenEntry
	(*SortOptions)(nil),              // 7: garmin_vivomovehr.SortOptions
	(*SortEntry)(nil),                // 8: garmin_vivomovehr.SortEntry
	(*TextOption)(nil),               // 9: garmin_vivomovehr.TextOption
	(*TextLimits)(nil),               // 10: garmin_vivomovehr.TextLimits
	(*Target)(nil),                   // 11: garmin_vivomovehr.Target
	(*ScreenStateRequest)(nil),       // 12: garmin_vivomovehr.ScreenStateRequest
	(*TargetOptions)(nil),            // 13: garmin_vivomovehr.TargetOptions
	(*TargetOptionEntry)(nil),        // 14: garmin_vivomovehr.TargetOptionEntry
	(*TargetNumberPicker)(nil),       // 15: garmin_vivomovehr.TargetNumberPicker
	(*ScreenStateResponse)(nil),      // 16: garmin_vivomovehr.ScreenStateResponse
	(*ScreenState)(nil),              // 17: garmin_vivomovehr.ScreenState
	(*EntryState)(nil),               // 18: garmin_vivomovehr.EntryState
	(*Switch)(nil),                   // 19: garmin_vivomovehr.Switch
	(*Summary)(nil),                  // 20: garmin_vivomovehr.Summary
	(*ValueList)(nil),                // 21: garmin_vivomovehr.ValueList
	(*ValueTime)(nil),                // 22: garmin_vivomovehr.ValueTime
	(*ValueNumber)(nil),              // 23: garmin_vivomovehr.ValueNumber
	(*ValueDate)(nil),                // 24: garmin_vivomovehr.ValueDate
	(*ValueHeight)(nil),              // 25: garmin_vivomovehr.ValueHeight
	(*Date)(nil),                     // 26: garmin_vivomovehr.Date
	(*ChangeRequest)(nil),            // 27: garmin_vivomovehr.ChangeRequest
	(*ChangeResponse)(nil),           // 28: garmin_vivomovehr.ChangeResponse
	(*InitRequest)(nil),              // 29: garmin_vivomovehr.InitRequest
	(*InitResponse)(nil),             // 30: garmin_vivomovehr.InitResponse
	(*ChangeRequest_Switch)(nil),     // 31: garmin_vivomovehr.ChangeRequest.Switch
	(*ChangeRequest_Option)(nil),     // 32: garmin_vivomovehr.ChangeRequest.Option
	(*ChangeRequest_Time)(nil),       // 33: garmin_vivomovehr.ChangeRequest.Time
	(*ChangeRequest_Number)(nil),     // 34: garmin_vivomovehr.ChangeRequest.Number
	(*ChangeRequest_Position)(nil),   // 35: garmin_vivomovehr.ChangeRequest.Position
	(*ChangeRequest_NewDate)(nil),    // 36: garmin_vivomovehr.ChangeRequest.NewDate
	(*ChangeRequest_Text)(nil),       // 37: garmin_vivomovehr.ChangeRequest.Text
	(*ChangeRequest_Height)(nil),     // 38: garmin_vivomovehr.ChangeRequest.Height
}
var file_garmin_gdi_settings_service_proto_depIdxs = []int32{
	2,  // 0: garmin_vivomovehr.SettingsService.definitionRequest:type_name -> garmin_vivomovehr.ScreenDefinitionRequest
	3,  // 1: garmin_vivomovehr.SettingsService.definitionResponse:type_name -> garmin_vivomovehr.ScreenDefinitionResponse
	12, // 2: garmin_vivomovehr.SettingsService.stateRequest:type_name -> garmin_vivomovehr.ScreenStateRequest
	16, // 3: garmin_vivomovehr.SettingsService.stateResponse:type_name -> garmin_vivomovehr.ScreenStateResponse
	27, // 4: garmin_vivomovehr.SettingsService.changeRequest:type_name -> garmin_vivomovehr.ChangeRequest
	28, // 5: garmin_vivomovehr.SettingsService.changeResponse:type_name -> garmin_vivomovehr.ChangeResponse
	29, // 6: garmin_vivomovehr.SettingsService.initRequest:type_name -> garmin_vivomovehr.InitRequest
	30, // 7: garmin_vivomovehr.SettingsService.initResponse:type_name -> garmin_vivomovehr.InitResponse
	4,  // 8: garmin_vivomovehr.ScreenDefinitionResponse.definition:type_name -> garmin_vivomovehr.ScreenDefinition
	5,  // 9: garmin_vivomovehr.ScreenDefinition.title:type_name -> garmin_vivomovehr.Label
	6,  // 10: garmin_vivomovehr.ScreenDefinition.entry:type_name -> garmin_vivomovehr.ScreenEntry
	5,  // 11: garmin_vivomovehr.ScreenEntry.title:type_name -> garmin_vivomovehr.Label
	11, // 12: garmin_vivomovehr.ScreenEntry.target:type_name -> garmin_vivomovehr.Target
	7,  // 13: garmin_vivomovehr.ScreenEntry.sortOptions:type_name -> garmin_vivomovehr.SortOptions
	9,  // 14: garmin_vivomovehr.ScreenEntry.textOption:type_name -> garmin_vivomovehr.TextOption
	8,  // 15: garmin_vivomovehr.SortOptions.entries:type_name -> garmin_vivomovehr.SortEntry
	5,  // 16: garmin_vivomovehr.SortEntry.title:type_name -> garmin_vivomovehr.Label
	10, // 17: garmin_vivomovehr.TextOption.limits:type_name -> garmin_vivomovehr.TextLimits
	13, // 18: garmin_vivomovehr.Target.options:type_name -> garmin_vivomovehr.TargetOptions
	15, // 19: garmin_vivomovehr.Target.numberPicker:type_name -> garmin_vivomovehr.TargetNumberPicker
	14, // 20: garmin_vivomovehr.TargetOptions.option:type_name -> garmin_vivomovehr.TargetOptionEntry
	5,  // 21: garmin_vivomovehr.TargetOptionEntry.title:type_name -> garmin_vivomovehr.Label
	17, // 22: garmin_vivomovehr.ScreenStateResponse.state:type_name -> garmin_vivomovehr.ScreenState
	18, // 23: garmin_vivomovehr.ScreenState.state:type_name -> garmin_vivomovehr.EntryState
	19, // 24: garmin_vivomovehr.EntryState.switch:type_name -> garmin_vivomovehr.Switch
	20, // 25: garmin_vivomovehr.EntryState.summary:type_name -> garmin_vivomovehr.Summary
	5,  // 26: garmin_vivomovehr.Switch.title:type_name -> garmin_vivomovehr.Label
	5,  // 27: garmin_vivomovehr.Summary.title:type_name -> garmin_vivomovehr.Label
	21, // 28: garmin_vivomovehr.Summary.valueList:type_name -> garmin_vivomovehr.ValueList
	22, // 29: garmin_vivomovehr.Summary.valueTime:type_name -> garmin_vivomovehr.ValueTime
	23, // 30: garmin_vivomovehr.Summary.valueNumber:type_name -> garmin_vivomovehr.ValueNumber
	24, // 31: garmin_vivomovehr.Summary.valueDate:type_name -> garmin_vivomovehr.ValueDate
	25, // 32: garmin_vivomovehr.Summary.valueHeight:type_name -> garmin_vivomovehr.ValueHeight
	5,  // 33: garmin_vivomovehr.ValueNumber.subtitle:type_name -> garmin_vivomovehr.Label
	5,  // 34: garmin_vivomovehr.ValueNumber.title:type_name -> garmin_vivomovehr.Label
	5,  // 35: garmin_vivomovehr.ValueNumber.unit:type_name -> garmin_vivomovehr.Label
	5,  // 36: garmin_vivomovehr.ValueDate.subtitle:type_name -> garmin_vivomovehr.Label
	26, // 37: garmin_vivomovehr.ValueDate.currentDate:type_name -> garmin_vivomovehr.Date
	26, // 38: garmin_vivomovehr.ValueDate.minDate:type_name -> garmin_vivomovehr.Date
	26, // 39: garmin_vivomovehr.ValueDate.maxDate:type_name -> garmin_vivomovehr.Date
	5,  // 40: garmin_vivomovehr.ValueHeight.subtitle:type_name -> garmin_vivomovehr.Label
	31, // 41: garmin_vivomovehr.ChangeRequest.switch:type_name -> garmin_vivomovehr.ChangeRequest.Switch
	32, // 42: garmin_vivomovehr.ChangeRequest.option:type_name -> garmin_vivomovehr.ChangeRequest.Option
	33, // 43: garmin_vivomovehr.ChangeRequest.time:type_name -> garmin_vivomovehr.ChangeRequest.Time
	34, // 44: garmin_vivomovehr.ChangeRequest.number:type_name -> garmin_vivomovehr.ChangeRequest.Number
	35, // 45: garmin_vivomovehr.ChangeRequest.position:type_name -> garmin_vivomovehr.ChangeRequest.Position
	36, // 46: garmin_vivomovehr.ChangeRequest.newDate:type_name -> garmin_vivomovehr.ChangeRequest.NewDate
	37, // 47: garmin_vivomovehr.ChangeRequest.text:type_name -> garmin_vivomovehr.ChangeRequest.Text
	38, // 48: garmin_vivomovehr.ChangeRequest.height:type_name -> garmin_vivomovehr.ChangeRequest.Height
	0,  // 49: garmin_vivomovehr.ChangeResponse.status:type_name -> garmin_vivomovehr.ResponseStatus
	17, // 50: garmin_vivomovehr.ChangeResponse.state:type_name -> garmin_vivomovehr.ScreenState
	26, // 51: garmin_vivomovehr.ChangeRequest.NewDate.value:type_name -> garmin_vivomovehr.Date
	52, // [52:52] is the sub-list for method output_type
	52, // [52:52] is the sub-list for method input_type
	52, // [52:52] is the sub-list for extension type_name
	52, // [52:52] is the sub-list for extension extendee
	0,  // [0:52] is the sub-list for field type_name
}

func init() { file_garmin_gdi_settings_service_proto_init() }
func file_garmin_gdi_settings_service_proto_init() {
	if File_garmin_gdi_settings_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_settings_service_proto_rawDesc), len(file_garmin_gdi_settings_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_settings_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_settings_service_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_settings_service_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_settings_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_settings_service_proto = out.File
	file_garmin_gdi_settings_service_proto_goTypes = nil
	file_garmin_gdi_settings_service_proto_depIdxs = nil
}
