// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_sms_notification.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SmsNotificationService_CannedListType int32

const (
	SmsNotificationService_PHONE_CALL_RESPONSE  SmsNotificationService_CannedListType = 0
	SmsNotificationService_SMS_MESSAGE_RESPONSE SmsNotificationService_CannedListType = 1
)

// Enum value maps for SmsNotificationService_CannedListType.
var (
	SmsNotificationService_CannedListType_name = map[int32]string{
		0: "PHONE_CALL_RESPONSE",
		1: "SMS_MESSAGE_RESPONSE",
	}
	SmsNotificationService_CannedListType_value = map[string]int32{
		"PHONE_CALL_RESPONSE":  0,
		"SMS_MESSAGE_RESPONSE": 1,
	}
)

func (x SmsNotificationService_CannedListType) Enum() *SmsNotificationService_CannedListType {
	p := new(SmsNotificationService_CannedListType)
	*p = x
	return p
}

func (x SmsNotificationService_CannedListType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsNotificationService_CannedListType) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_sms_notification_proto_enumTypes[0].Descriptor()
}

func (SmsNotificationService_CannedListType) Type() protoreflect.EnumType {
	return &file_garmin_gdi_sms_notification_proto_enumTypes[0]
}

func (x SmsNotificationService_CannedListType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SmsNotificationService_CannedListType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SmsNotificationService_CannedListType(num)
	return nil
}

// Deprecated: Use SmsNotificationService_CannedListType.Descriptor instead.
func (SmsNotificationService_CannedListType) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 0}
}

type SmsNotificationService_ResponseStatus int32

const (
	SmsNotificationService_SUCCESS       SmsNotificationService_ResponseStatus = 0
	SmsNotificationService_GENERIC_ERROR SmsNotificationService_ResponseStatus = 1
)

// Enum value maps for SmsNotificationService_ResponseStatus.
var (
	SmsNotificationService_ResponseStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "GENERIC_ERROR",
	}
	SmsNotificationService_ResponseStatus_value = map[string]int32{
		"SUCCESS":       0,
		"GENERIC_ERROR": 1,
	}
)

func (x SmsNotificationService_ResponseStatus) Enum() *SmsNotificationService_ResponseStatus {
	p := new(SmsNotificationService_ResponseStatus)
	*p = x
	return p
}

func (x SmsNotificationService_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SmsNotificationService_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_sms_notification_proto_enumTypes[1].Descriptor()
}

func (SmsNotificationService_ResponseStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_sms_notification_proto_enumTypes[1]
}

func (x SmsNotificationService_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SmsNotificationService_ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SmsNotificationService_ResponseStatus(num)
	return nil
}

// Deprecated: Use SmsNotificationService_ResponseStatus.Descriptor instead.
func (SmsNotificationService_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 1}
}

type SmsNotificationService struct {
	state                            protoimpl.MessageState                                   `protogen:"open.v1"`
	SmsSendMessageRequest            *SmsNotificationService_SmsSendMessageRequest            `protobuf:"bytes,1,opt,name=sms_send_message_request,json=smsSendMessageRequest" json:"sms_send_message_request,omitempty"`
	SmsSendMessageResponse           *SmsNotificationService_SmsSendMessageResponse           `protobuf:"bytes,2,opt,name=sms_send_message_response,json=smsSendMessageResponse" json:"sms_send_message_response,omitempty"`
	SmsCannedListChangedNotification *SmsNotificationService_SmsCannedListChangedNotification `protobuf:"bytes,3,opt,name=sms_canned_list_changed_notification,json=smsCannedListChangedNotification" json:"sms_canned_list_changed_notification,omitempty"`
	SmsCannedListRequest             *SmsNotificationService_SmsCannedListRequest             `protobuf:"bytes,4,opt,name=sms_canned_list_request,json=smsCannedListRequest" json:"sms_canned_list_request,omitempty"`
	SmsCannedListResponse            *SmsNotificationService_SmsCannedListResponse            `protobuf:"bytes,5,opt,name=sms_canned_list_response,json=smsCannedListResponse" json:"sms_canned_list_response,omitempty"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *SmsNotificationService) Reset() {
	*x = SmsNotificationService{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService) ProtoMessage() {}

func (x *SmsNotificationService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService.ProtoReflect.Descriptor instead.
func (*SmsNotificationService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0}
}

func (x *SmsNotificationService) GetSmsSendMessageRequest() *SmsNotificationService_SmsSendMessageRequest {
	if x != nil {
		return x.SmsSendMessageRequest
	}
	return nil
}

func (x *SmsNotificationService) GetSmsSendMessageResponse() *SmsNotificationService_SmsSendMessageResponse {
	if x != nil {
		return x.SmsSendMessageResponse
	}
	return nil
}

func (x *SmsNotificationService) GetSmsCannedListChangedNotification() *SmsNotificationService_SmsCannedListChangedNotification {
	if x != nil {
		return x.SmsCannedListChangedNotification
	}
	return nil
}

func (x *SmsNotificationService) GetSmsCannedListRequest() *SmsNotificationService_SmsCannedListRequest {
	if x != nil {
		return x.SmsCannedListRequest
	}
	return nil
}

func (x *SmsNotificationService) GetSmsCannedListResponse() *SmsNotificationService_SmsCannedListResponse {
	if x != nil {
		return x.SmsCannedListResponse
	}
	return nil
}

type SmsNotificationService_SmsSendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReceiverNumber *string                `protobuf:"bytes,1,opt,name=receiver_number,json=receiverNumber" json:"receiver_number,omitempty"`
	Message        *string                `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SmsNotificationService_SmsSendMessageRequest) Reset() {
	*x = SmsNotificationService_SmsSendMessageRequest{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService_SmsSendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService_SmsSendMessageRequest) ProtoMessage() {}

func (x *SmsNotificationService_SmsSendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService_SmsSendMessageRequest.ProtoReflect.Descriptor instead.
func (*SmsNotificationService_SmsSendMessageRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SmsNotificationService_SmsSendMessageRequest) GetReceiverNumber() string {
	if x != nil && x.ReceiverNumber != nil {
		return *x.ReceiverNumber
	}
	return ""
}

func (x *SmsNotificationService_SmsSendMessageRequest) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type SmsNotificationService_SmsSendMessageResponse struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Status        *SmsNotificationService_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.SmsNotificationService_ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsNotificationService_SmsSendMessageResponse) Reset() {
	*x = SmsNotificationService_SmsSendMessageResponse{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService_SmsSendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService_SmsSendMessageResponse) ProtoMessage() {}

func (x *SmsNotificationService_SmsSendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService_SmsSendMessageResponse.ProtoReflect.Descriptor instead.
func (*SmsNotificationService_SmsSendMessageResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 1}
}

func (x *SmsNotificationService_SmsSendMessageResponse) GetStatus() SmsNotificationService_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return SmsNotificationService_SUCCESS
}

type SmsNotificationService_SmsCannedListChangedNotification struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	ChangedType   []SmsNotificationService_CannedListType `protobuf:"varint,1,rep,name=changed_type,json=changedType,enum=garmin_vivomovehr.SmsNotificationService_CannedListType" json:"changed_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsNotificationService_SmsCannedListChangedNotification) Reset() {
	*x = SmsNotificationService_SmsCannedListChangedNotification{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService_SmsCannedListChangedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService_SmsCannedListChangedNotification) ProtoMessage() {}

func (x *SmsNotificationService_SmsCannedListChangedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService_SmsCannedListChangedNotification.ProtoReflect.Descriptor instead.
func (*SmsNotificationService_SmsCannedListChangedNotification) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 2}
}

func (x *SmsNotificationService_SmsCannedListChangedNotification) GetChangedType() []SmsNotificationService_CannedListType {
	if x != nil {
		return x.ChangedType
	}
	return nil
}

type SmsNotificationService_SmsCannedListRequest struct {
	state          protoimpl.MessageState                  `protogen:"open.v1"`
	RequestedTypes []SmsNotificationService_CannedListType `protobuf:"varint,1,rep,name=requested_types,json=requestedTypes,enum=garmin_vivomovehr.SmsNotificationService_CannedListType" json:"requested_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SmsNotificationService_SmsCannedListRequest) Reset() {
	*x = SmsNotificationService_SmsCannedListRequest{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService_SmsCannedListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService_SmsCannedListRequest) ProtoMessage() {}

func (x *SmsNotificationService_SmsCannedListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService_SmsCannedListRequest.ProtoReflect.Descriptor instead.
func (*SmsNotificationService_SmsCannedListRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 3}
}

func (x *SmsNotificationService_SmsCannedListRequest) GetRequestedTypes() []SmsNotificationService_CannedListType {
	if x != nil {
		return x.RequestedTypes
	}
	return nil
}

type SmsNotificationService_SmsCannedListResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Status        *SmsNotificationService_ResponseStatus  `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.SmsNotificationService_ResponseStatus" json:"status,omitempty"`
	Lists         []*SmsNotificationService_SmsCannedList `protobuf:"bytes,2,rep,name=lists" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsNotificationService_SmsCannedListResponse) Reset() {
	*x = SmsNotificationService_SmsCannedListResponse{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService_SmsCannedListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService_SmsCannedListResponse) ProtoMessage() {}

func (x *SmsNotificationService_SmsCannedListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService_SmsCannedListResponse.ProtoReflect.Descriptor instead.
func (*SmsNotificationService_SmsCannedListResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 4}
}

func (x *SmsNotificationService_SmsCannedListResponse) GetStatus() SmsNotificationService_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return SmsNotificationService_SUCCESS
}

func (x *SmsNotificationService_SmsCannedListResponse) GetLists() []*SmsNotificationService_SmsCannedList {
	if x != nil {
		return x.Lists
	}
	return nil
}

type SmsNotificationService_SmsCannedList struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Type          *SmsNotificationService_CannedListType `protobuf:"varint,1,opt,name=type,enum=garmin_vivomovehr.SmsNotificationService_CannedListType" json:"type,omitempty"`
	Response      []string                               `protobuf:"bytes,2,rep,name=response" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SmsNotificationService_SmsCannedList) Reset() {
	*x = SmsNotificationService_SmsCannedList{}
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SmsNotificationService_SmsCannedList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsNotificationService_SmsCannedList) ProtoMessage() {}

func (x *SmsNotificationService_SmsCannedList) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_sms_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsNotificationService_SmsCannedList.ProtoReflect.Descriptor instead.
func (*SmsNotificationService_SmsCannedList) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_sms_notification_proto_rawDescGZIP(), []int{0, 5}
}

func (x *SmsNotificationService_SmsCannedList) GetType() SmsNotificationService_CannedListType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return SmsNotificationService_PHONE_CALL_RESPONSE
}

func (x *SmsNotificationService_SmsCannedList) GetResponse() []string {
	if x != nil {
		return x.Response
	}
	return nil
}

var File_garmin_gdi_sms_notification_proto protoreflect.FileDescriptor

const file_garmin_gdi_sms_notification_proto_rawDesc = "" +
	"\n" +
	"!garmin/gdi_sms_notification.proto\x12\x11garmin_vivomovehr\"\x8e\f\n" +
	"\x16SmsNotificationService\x12x\n" +
	"\x18sms_send_message_request\x18\x01 \x01(\v2?.garmin_vivomovehr.SmsNotificationService.SmsSendMessageRequestR\x15smsSendMessageRequest\x12{\n" +
	"\x19sms_send_message_response\x18\x02 \x01(\v2@.garmin_vivomovehr.SmsNotificationService.SmsSendMessageResponseR\x16smsSendMessageResponse\x12\x9a\x01\n" +
	"$sms_canned_list_changed_notification\x18\x03 \x01(\v2J.garmin_vivomovehr.SmsNotificationService.SmsCannedListChangedNotificationR smsCannedListChangedNotification\x12u\n" +
	"\x17sms_canned_list_request\x18\x04 \x01(\v2>.garmin_vivomovehr.SmsNotificationService.SmsCannedListRequestR\x14smsCannedListRequest\x12x\n" +
	"\x18sms_canned_list_response\x18\x05 \x01(\v2?.garmin_vivomovehr.SmsNotificationService.SmsCannedListResponseR\x15smsCannedListResponse\x1aZ\n" +
	"\x15SmsSendMessageRequest\x12'\n" +
	"\x0freceiver_number\x18\x01 \x01(\tR\x0ereceiverNumber\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x1aj\n" +
	"\x16SmsSendMessageResponse\x12P\n" +
	"\x06status\x18\x01 \x01(\x0e28.garmin_vivomovehr.SmsNotificationService.ResponseStatusR\x06status\x1a\x7f\n" +
	" SmsCannedListChangedNotification\x12[\n" +
	"\fchanged_type\x18\x01 \x03(\x0e28.garmin_vivomovehr.SmsNotificationService.CannedListTypeR\vchangedType\x1ay\n" +
	"\x14SmsCannedListRequest\x12a\n" +
	"\x0frequested_types\x18\x01 \x03(\x0e28.garmin_vivomovehr.SmsNotificationService.CannedListTypeR\x0erequestedTypes\x1a\xb8\x01\n" +
	"\x15SmsCannedListResponse\x12P\n" +
	"\x06status\x18\x01 \x01(\x0e28.garmin_vivomovehr.SmsNotificationService.ResponseStatusR\x06status\x12M\n" +
	"\x05lists\x18\x02 \x03(\v27.garmin_vivomovehr.SmsNotificationService.SmsCannedListR\x05lists\x1ay\n" +
	"\rSmsCannedList\x12L\n" +
	"\x04type\x18\x01 \x01(\x0e28.garmin_vivomovehr.SmsNotificationService.CannedListTypeR\x04type\x12\x1a\n" +
	"\bresponse\x18\x02 \x03(\tR\bresponse\"C\n" +
	"\x0eCannedListType\x12\x17\n" +
	"\x13PHONE_CALL_RESPONSE\x10\x00\x12\x18\n" +
	"\x14SMS_MESSAGE_RESPONSE\x10\x01\"0\n" +
	"\x0eResponseStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x11\n" +
	"\rGENERIC_ERROR\x10\x01BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_sms_notification_proto_rawDescOnce sync.Once
	file_garmin_gdi_sms_notification_proto_rawDescData []byte
)

func file_garmin_gdi_sms_notification_proto_rawDescGZIP() []byte {
	file_garmin_gdi_sms_notification_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_sms_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_sms_notification_proto_rawDesc), len(file_garmin_gdi_sms_notification_proto_rawDesc)))
	})
	return file_garmin_gdi_sms_notification_proto_rawDescData
}

var file_garmin_gdi_sms_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_garmin_gdi_sms_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_garmin_gdi_sms_notification_proto_goTypes = []any{
	(SmsNotificationService_CannedListType)(0),                      // 0: garmin_vivomovehr.SmsNotificationService.CannedListType
	(SmsNotificationService_ResponseStatus)(0),                      // 1: garmin_vivomovehr.SmsNotificationService.ResponseStatus
	(*SmsNotificationService)(nil),                                  // 2: garmin_vivomovehr.SmsNotificationService
	(*SmsNotificationService_SmsSendMessageRequest)(nil),            // 3: garmin_vivomovehr.SmsNotificationService.SmsSendMessageRequest
	(*SmsNotificationService_SmsSendMessageResponse)(nil),           // 4: garmin_vivomovehr.SmsNotificationService.SmsSendMessageResponse
	(*SmsNotificationService_SmsCannedListChangedNotification)(nil), // 5: garmin_vivomovehr.SmsNotificationService.SmsCannedListChangedNotification
	(*SmsNotificationService_SmsCannedListRequest)(nil),             // 6: garmin_vivomovehr.SmsNotificationService.SmsCannedListRequest
	(*SmsNotificationService_SmsCannedListResponse)(nil),            // 7: garmin_vivomovehr.SmsNotificationService.SmsCannedListResponse
	(*SmsNotificationService_SmsCannedList)(nil),                    // 8: garmin_vivomovehr.SmsNotificationService.SmsCannedList
}
var file_garmin_gdi_sms_notification_proto_depIdxs = []int32{
	3,  // 0: garmin_vivomovehr.SmsNotificationService.sms_send_message_request:type_name -> garmin_vivomovehr.SmsNotificationService.SmsSendMessageRequest
	4,  // 1: garmin_vivomovehr.SmsNotificationService.sms_send_message_response:type_name -> garmin_vivomovehr.SmsNotificationService.SmsSendMessageResponse
	5,  // 2: garmin_vivomovehr.SmsNotificationService.sms_canned_list_changed_notification:type_name -> garmin_vivomovehr.SmsNotificationService.SmsCannedListChangedNotification
	6,  // 3: garmin_vivomovehr.SmsNotificationService.sms_canned_list_request:type_name -> garmin_vivomovehr.SmsNotificationService.SmsCannedListRequest
	7,  // 4: garmin_vivomovehr.SmsNotificationService.sms_canned_list_response:type_name -> garmin_vivomovehr.SmsNotificationService.SmsCannedListResponse
	1,  // 5: garmin_vivomovehr.SmsNotificationService.SmsSendMessageResponse.status:type_name -> garmin_vivomovehr.SmsNotificationService.ResponseStatus
	0,  // 6: garmin_vivomovehr.SmsNotificationService.SmsCannedListChangedNotification.changed_type:type_name -> garmin_vivomovehr.SmsNotificationService.CannedListType
	0,  // 7: garmin_vivomovehr.SmsNotificationService.SmsCannedListRequest.requested_types:type_name -> garmin_vivomovehr.SmsNotificationService.CannedListType
	1,  // 8: garmin_vivomovehr.SmsNotificationService.SmsCannedListResponse.status:type_name -> garmin_vivomovehr.SmsNotificationService.ResponseStatus
	8,  // 9: garmin_vivomovehr.SmsNotificationService.SmsCannedListResponse.lists:type_name -> garmin_vivomovehr.SmsNotificationService.SmsCannedList
	0,  // 10: garmin_vivomovehr.SmsNotificationService.SmsCannedList.type:type_name -> garmin_vivomovehr.SmsNotificationService.CannedListType
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_garmin_gdi_sms_notification_proto_init() }
func file_garmin_gdi_sms_notification_proto_init() {
	if File_garmin_gdi_sms_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_sms_notification_proto_rawDesc), len(file_garmin_gdi_sms_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_sms_notification_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_sms_notification_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_sms_notification_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_sms_notification_proto_msgTypes,
	}.Build()
	File_garmin_gdi_sms_notification_proto = out.File
	file_garmin_gdi_sms_notification_proto_goTypes = nil
	file_garmin_gdi_sms_notification_proto_depIdxs = nil
}
