// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_data_transfer_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataTransferService_Status int32

const (
	DataTransferService_UNKNOWN        DataTransferService_Status = 0
	DataTransferService_SUCCESS        DataTransferService_Status = 1
	DataTransferService_INVALID_ID     DataTransferService_Status = 2
	DataTransferService_INVALID_OFFSET DataTransferService_Status = 3
)

// Enum value maps for DataTransferService_Status.
var (
	DataTransferService_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "INVALID_ID",
		3: "INVALID_OFFSET",
	}
	DataTransferService_Status_value = map[string]int32{
		"UNKNOWN":        0,
		"SUCCESS":        1,
		"INVALID_ID":     2,
		"INVALID_OFFSET": 3,
	}
)

func (x DataTransferService_Status) Enum() *DataTransferService_Status {
	p := new(DataTransferService_Status)
	*p = x
	return p
}

func (x DataTransferService_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DataTransferService_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_data_transfer_service_proto_enumTypes[0].Descriptor()
}

func (DataTransferService_Status) Type() protoreflect.EnumType {
	return &file_garmin_gdi_data_transfer_service_proto_enumTypes[0]
}

func (x DataTransferService_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DataTransferService_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DataTransferService_Status(num)
	return nil
}

// Deprecated: Use DataTransferService_Status.Descriptor instead.
func (DataTransferService_Status) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_data_transfer_service_proto_rawDescGZIP(), []int{0, 0}
}

type DataTransferService struct {
	state                protoimpl.MessageState                    `protogen:"open.v1"`
	DataDownloadRequest  *DataTransferService_DataDownloadRequest  `protobuf:"bytes,1,opt,name=dataDownloadRequest" json:"dataDownloadRequest,omitempty"`
	DataDownloadResponse *DataTransferService_DataDownloadResponse `protobuf:"bytes,2,opt,name=dataDownloadResponse" json:"dataDownloadResponse,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DataTransferService) Reset() {
	*x = DataTransferService{}
	mi := &file_garmin_gdi_data_transfer_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTransferService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransferService) ProtoMessage() {}

func (x *DataTransferService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_data_transfer_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransferService.ProtoReflect.Descriptor instead.
func (*DataTransferService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_data_transfer_service_proto_rawDescGZIP(), []int{0}
}

func (x *DataTransferService) GetDataDownloadRequest() *DataTransferService_DataDownloadRequest {
	if x != nil {
		return x.DataDownloadRequest
	}
	return nil
}

func (x *DataTransferService) GetDataDownloadResponse() *DataTransferService_DataDownloadResponse {
	if x != nil {
		return x.DataDownloadResponse
	}
	return nil
}

type DataTransferService_DataDownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *uint32                `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Offset        *uint32                `protobuf:"varint,2,req,name=offset" json:"offset,omitempty"`
	MaxChunkSize  *uint32                `protobuf:"varint,3,opt,name=maxChunkSize" json:"maxChunkSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTransferService_DataDownloadRequest) Reset() {
	*x = DataTransferService_DataDownloadRequest{}
	mi := &file_garmin_gdi_data_transfer_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTransferService_DataDownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransferService_DataDownloadRequest) ProtoMessage() {}

func (x *DataTransferService_DataDownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_data_transfer_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransferService_DataDownloadRequest.ProtoReflect.Descriptor instead.
func (*DataTransferService_DataDownloadRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_data_transfer_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DataTransferService_DataDownloadRequest) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DataTransferService_DataDownloadRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *DataTransferService_DataDownloadRequest) GetMaxChunkSize() uint32 {
	if x != nil && x.MaxChunkSize != nil {
		return *x.MaxChunkSize
	}
	return 0
}

type DataTransferService_DataDownloadResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        *DataTransferService_Status `protobuf:"varint,1,req,name=status,enum=garmin_vivomovehr.DataTransferService_Status" json:"status,omitempty"`
	Id            *uint32                     `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Offset        *uint32                     `protobuf:"varint,3,req,name=offset" json:"offset,omitempty"`
	Payload       []byte                      `protobuf:"bytes,4,opt,name=payload" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataTransferService_DataDownloadResponse) Reset() {
	*x = DataTransferService_DataDownloadResponse{}
	mi := &file_garmin_gdi_data_transfer_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataTransferService_DataDownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataTransferService_DataDownloadResponse) ProtoMessage() {}

func (x *DataTransferService_DataDownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_data_transfer_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataTransferService_DataDownloadResponse.ProtoReflect.Descriptor instead.
func (*DataTransferService_DataDownloadResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_data_transfer_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DataTransferService_DataDownloadResponse) GetStatus() DataTransferService_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return DataTransferService_UNKNOWN
}

func (x *DataTransferService_DataDownloadResponse) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *DataTransferService_DataDownloadResponse) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *DataTransferService_DataDownloadResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_garmin_gdi_data_transfer_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_data_transfer_service_proto_rawDesc = "" +
	"\n" +
	"&garmin/gdi_data_transfer_service.proto\x12\x11garmin_vivomovehr\"\xc1\x04\n" +
	"\x13DataTransferService\x12l\n" +
	"\x13dataDownloadRequest\x18\x01 \x01(\v2:.garmin_vivomovehr.DataTransferService.DataDownloadRequestR\x13dataDownloadRequest\x12o\n" +
	"\x14dataDownloadResponse\x18\x02 \x01(\v2;.garmin_vivomovehr.DataTransferService.DataDownloadResponseR\x14dataDownloadResponse\x1aa\n" +
	"\x13DataDownloadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x02(\rR\x02id\x12\x16\n" +
	"\x06offset\x18\x02 \x02(\rR\x06offset\x12\"\n" +
	"\fmaxChunkSize\x18\x03 \x01(\rR\fmaxChunkSize\x1a\x9f\x01\n" +
	"\x14DataDownloadResponse\x12E\n" +
	"\x06status\x18\x01 \x02(\x0e2-.garmin_vivomovehr.DataTransferService.StatusR\x06status\x12\x0e\n" +
	"\x02id\x18\x02 \x02(\rR\x02id\x12\x16\n" +
	"\x06offset\x18\x03 \x02(\rR\x06offset\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"F\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\x0e\n" +
	"\n" +
	"INVALID_ID\x10\x02\x12\x12\n" +
	"\x0eINVALID_OFFSET\x10\x03BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_data_transfer_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_data_transfer_service_proto_rawDescData []byte
)

func file_garmin_gdi_data_transfer_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_data_transfer_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_data_transfer_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_data_transfer_service_proto_rawDesc), len(file_garmin_gdi_data_transfer_service_proto_rawDesc)))
	})
	return file_garmin_gdi_data_transfer_service_proto_rawDescData
}

var file_garmin_gdi_data_transfer_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_garmin_gdi_data_transfer_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_garmin_gdi_data_transfer_service_proto_goTypes = []any{
	(DataTransferService_Status)(0),                  // 0: garmin_vivomovehr.DataTransferService.Status
	(*DataTransferService)(nil),                      // 1: garmin_vivomovehr.DataTransferService
	(*DataTransferService_DataDownloadRequest)(nil),  // 2: garmin_vivomovehr.DataTransferService.DataDownloadRequest
	(*DataTransferService_DataDownloadResponse)(nil), // 3: garmin_vivomovehr.DataTransferService.DataDownloadResponse
}
var file_garmin_gdi_data_transfer_service_proto_depIdxs = []int32{
	2, // 0: garmin_vivomovehr.DataTransferService.dataDownloadRequest:type_name -> garmin_vivomovehr.DataTransferService.DataDownloadRequest
	3, // 1: garmin_vivomovehr.DataTransferService.dataDownloadResponse:type_name -> garmin_vivomovehr.DataTransferService.DataDownloadResponse
	0, // 2: garmin_vivomovehr.DataTransferService.DataDownloadResponse.status:type_name -> garmin_vivomovehr.DataTransferService.Status
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_garmin_gdi_data_transfer_service_proto_init() }
func file_garmin_gdi_data_transfer_service_proto_init() {
	if File_garmin_gdi_data_transfer_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_data_transfer_service_proto_rawDesc), len(file_garmin_gdi_data_transfer_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_data_transfer_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_data_transfer_service_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_data_transfer_service_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_data_transfer_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_data_transfer_service_proto = out.File
	file_garmin_gdi_data_transfer_service_proto_goTypes = nil
	file_garmin_gdi_data_transfer_service_proto_depIdxs = nil
}
