// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_ecg_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EcgService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileTransfer  *EcgFileTransfer       `protobuf:"bytes,1,opt,name=file_transfer,json=fileTransfer" json:"file_transfer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgService) Reset() {
	*x = EcgService{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgService) ProtoMessage() {}

func (x *EcgService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgService.ProtoReflect.Descriptor instead.
func (*EcgService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{0}
}

func (x *EcgService) GetFileTransfer() *EcgFileTransfer {
	if x != nil {
		return x.FileTransfer
	}
	return nil
}

type EcgFileTransfer struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	InitRequest          *EcgInitRequest        `protobuf:"bytes,3,opt,name=init_request,json=initRequest" json:"init_request,omitempty"`
	InitResponse         *EcgInitResponse       `protobuf:"bytes,4,opt,name=init_response,json=initResponse" json:"init_response,omitempty"`
	TransferStartReq     *EcgTransferStartReq   `protobuf:"bytes,5,opt,name=transfer_start_req,json=transferStartReq" json:"transfer_start_req,omitempty"`
	TransferStartAck     *EcgTransferStartAck   `protobuf:"bytes,6,opt,name=transfer_start_ack,json=transferStartAck" json:"transfer_start_ack,omitempty"`
	EcgFile              *EcgFile               `protobuf:"bytes,7,opt,name=ecg_file,json=ecgFile" json:"ecg_file,omitempty"`
	TransferFinishNotify *string                `protobuf:"bytes,8,opt,name=transfer_finish_notify,json=transferFinishNotify" json:"transfer_finish_notify,omitempty"` // ""
	TransferFinishAck    *string                `protobuf:"bytes,9,opt,name=transfer_finish_ack,json=transferFinishAck" json:"transfer_finish_ack,omitempty"`          // ""
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EcgFileTransfer) Reset() {
	*x = EcgFileTransfer{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgFileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgFileTransfer) ProtoMessage() {}

func (x *EcgFileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgFileTransfer.ProtoReflect.Descriptor instead.
func (*EcgFileTransfer) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{1}
}

func (x *EcgFileTransfer) GetInitRequest() *EcgInitRequest {
	if x != nil {
		return x.InitRequest
	}
	return nil
}

func (x *EcgFileTransfer) GetInitResponse() *EcgInitResponse {
	if x != nil {
		return x.InitResponse
	}
	return nil
}

func (x *EcgFileTransfer) GetTransferStartReq() *EcgTransferStartReq {
	if x != nil {
		return x.TransferStartReq
	}
	return nil
}

func (x *EcgFileTransfer) GetTransferStartAck() *EcgTransferStartAck {
	if x != nil {
		return x.TransferStartAck
	}
	return nil
}

func (x *EcgFileTransfer) GetEcgFile() *EcgFile {
	if x != nil {
		return x.EcgFile
	}
	return nil
}

func (x *EcgFileTransfer) GetTransferFinishNotify() string {
	if x != nil && x.TransferFinishNotify != nil {
		return *x.TransferFinishNotify
	}
	return ""
}

func (x *EcgFileTransfer) GetTransferFinishAck() string {
	if x != nil && x.TransferFinishAck != nil {
		return *x.TransferFinishAck
	}
	return ""
}

type EcgInitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *string                `protobuf:"bytes,1,opt,name=unk1" json:"unk1,omitempty"` // uuid
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgInitRequest) Reset() {
	*x = EcgInitRequest{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgInitRequest) ProtoMessage() {}

func (x *EcgInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgInitRequest.ProtoReflect.Descriptor instead.
func (*EcgInitRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{2}
}

func (x *EcgInitRequest) GetUnk1() string {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return ""
}

type EcgInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *uint32                `protobuf:"varint,1,opt,name=unk1" json:"unk1,omitempty"` // 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgInitResponse) Reset() {
	*x = EcgInitResponse{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgInitResponse) ProtoMessage() {}

func (x *EcgInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgInitResponse.ProtoReflect.Descriptor instead.
func (*EcgInitResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{3}
}

func (x *EcgInitResponse) GetUnk1() uint32 {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return 0
}

type EcgTransferStartReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk1          *string                `protobuf:"bytes,1,opt,name=unk1" json:"unk1,omitempty"` // ""
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgTransferStartReq) Reset() {
	*x = EcgTransferStartReq{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgTransferStartReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgTransferStartReq) ProtoMessage() {}

func (x *EcgTransferStartReq) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgTransferStartReq.ProtoReflect.Descriptor instead.
func (*EcgTransferStartReq) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{4}
}

func (x *EcgTransferStartReq) GetUnk1() string {
	if x != nil && x.Unk1 != nil {
		return *x.Unk1
	}
	return ""
}

type EcgTransferStartAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgTransferStartAck) Reset() {
	*x = EcgTransferStartAck{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgTransferStartAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgTransferStartAck) ProtoMessage() {}

func (x *EcgTransferStartAck) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgTransferStartAck.ProtoReflect.Descriptor instead.
func (*EcgTransferStartAck) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{5}
}

func (x *EcgTransferStartAck) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

type EcgFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Unk3          *uint32                `protobuf:"varint,3,opt,name=unk3" json:"unk3,omitempty"` // 0
	Unk4          *uint32                `protobuf:"varint,4,opt,name=unk4" json:"unk4,omitempty"` // 1
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EcgFile) Reset() {
	*x = EcgFile{}
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EcgFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcgFile) ProtoMessage() {}

func (x *EcgFile) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_ecg_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcgFile.ProtoReflect.Descriptor instead.
func (*EcgFile) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_ecg_service_proto_rawDescGZIP(), []int{6}
}

func (x *EcgFile) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EcgFile) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EcgFile) GetUnk3() uint32 {
	if x != nil && x.Unk3 != nil {
		return *x.Unk3
	}
	return 0
}

func (x *EcgFile) GetUnk4() uint32 {
	if x != nil && x.Unk4 != nil {
		return *x.Unk4
	}
	return 0
}

var File_garmin_gdi_ecg_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_ecg_service_proto_rawDesc = "" +
	"\n" +
	"\x1cgarmin/gdi_ecg_service.proto\x12\x11garmin_vivomovehr\"U\n" +
	"\n" +
	"EcgService\x12G\n" +
	"\rfile_transfer\x18\x01 \x01(\v2\".garmin_vivomovehr.EcgFileTransferR\ffileTransfer\"\xe9\x03\n" +
	"\x0fEcgFileTransfer\x12D\n" +
	"\finit_request\x18\x03 \x01(\v2!.garmin_vivomovehr.EcgInitRequestR\vinitRequest\x12G\n" +
	"\rinit_response\x18\x04 \x01(\v2\".garmin_vivomovehr.EcgInitResponseR\finitResponse\x12T\n" +
	"\x12transfer_start_req\x18\x05 \x01(\v2&.garmin_vivomovehr.EcgTransferStartReqR\x10transferStartReq\x12T\n" +
	"\x12transfer_start_ack\x18\x06 \x01(\v2&.garmin_vivomovehr.EcgTransferStartAckR\x10transferStartAck\x125\n" +
	"\becg_file\x18\a \x01(\v2\x1a.garmin_vivomovehr.EcgFileR\aecgFile\x124\n" +
	"\x16transfer_finish_notify\x18\b \x01(\tR\x14transferFinishNotify\x12.\n" +
	"\x13transfer_finish_ack\x18\t \x01(\tR\x11transferFinishAck\"$\n" +
	"\x0eEcgInitRequest\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\tR\x04unk1\"%\n" +
	"\x0fEcgInitResponse\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\rR\x04unk1\")\n" +
	"\x13EcgTransferStartReq\x12\x12\n" +
	"\x04unk1\x18\x01 \x01(\tR\x04unk1\")\n" +
	"\x13EcgTransferStartAck\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\"Y\n" +
	"\aEcgFile\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04unk3\x18\x03 \x01(\rR\x04unk3\x12\x12\n" +
	"\x04unk4\x18\x04 \x01(\rR\x04unk4BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_ecg_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_ecg_service_proto_rawDescData []byte
)

func file_garmin_gdi_ecg_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_ecg_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_ecg_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_ecg_service_proto_rawDesc), len(file_garmin_gdi_ecg_service_proto_rawDesc)))
	})
	return file_garmin_gdi_ecg_service_proto_rawDescData
}

var file_garmin_gdi_ecg_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_garmin_gdi_ecg_service_proto_goTypes = []any{
	(*EcgService)(nil),          // 0: garmin_vivomovehr.EcgService
	(*EcgFileTransfer)(nil),     // 1: garmin_vivomovehr.EcgFileTransfer
	(*EcgInitRequest)(nil),      // 2: garmin_vivomovehr.EcgInitRequest
	(*EcgInitResponse)(nil),     // 3: garmin_vivomovehr.EcgInitResponse
	(*EcgTransferStartReq)(nil), // 4: garmin_vivomovehr.EcgTransferStartReq
	(*EcgTransferStartAck)(nil), // 5: garmin_vivomovehr.EcgTransferStartAck
	(*EcgFile)(nil),             // 6: garmin_vivomovehr.EcgFile
}
var file_garmin_gdi_ecg_service_proto_depIdxs = []int32{
	1, // 0: garmin_vivomovehr.EcgService.file_transfer:type_name -> garmin_vivomovehr.EcgFileTransfer
	2, // 1: garmin_vivomovehr.EcgFileTransfer.init_request:type_name -> garmin_vivomovehr.EcgInitRequest
	3, // 2: garmin_vivomovehr.EcgFileTransfer.init_response:type_name -> garmin_vivomovehr.EcgInitResponse
	4, // 3: garmin_vivomovehr.EcgFileTransfer.transfer_start_req:type_name -> garmin_vivomovehr.EcgTransferStartReq
	5, // 4: garmin_vivomovehr.EcgFileTransfer.transfer_start_ack:type_name -> garmin_vivomovehr.EcgTransferStartAck
	6, // 5: garmin_vivomovehr.EcgFileTransfer.ecg_file:type_name -> garmin_vivomovehr.EcgFile
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_garmin_gdi_ecg_service_proto_init() }
func file_garmin_gdi_ecg_service_proto_init() {
	if File_garmin_gdi_ecg_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_ecg_service_proto_rawDesc), len(file_garmin_gdi_ecg_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_ecg_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_ecg_service_proto_depIdxs,
		MessageInfos:      file_garmin_gdi_ecg_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_ecg_service_proto = out.File
	file_garmin_gdi_ecg_service_proto_goTypes = nil
	file_garmin_gdi_ecg_service_proto_depIdxs = nil
}
