// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_authentication_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthenticationService struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OauthRequest  *OAuthRequest          `protobuf:"bytes,1,opt,name=oauthRequest" json:"oauthRequest,omitempty"`
	OauthResponse *OAuthResponse         `protobuf:"bytes,2,opt,name=oauthResponse" json:"oauthResponse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticationService) Reset() {
	*x = AuthenticationService{}
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticationService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticationService) ProtoMessage() {}

func (x *AuthenticationService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticationService.ProtoReflect.Descriptor instead.
func (*AuthenticationService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_authentication_service_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticationService) GetOauthRequest() *OAuthRequest {
	if x != nil {
		return x.OauthRequest
	}
	return nil
}

func (x *AuthenticationService) GetOauthResponse() *OAuthResponse {
	if x != nil {
		return x.OauthResponse
	}
	return nil
}

type OAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthRequest) Reset() {
	*x = OAuthRequest{}
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthRequest) ProtoMessage() {}

func (x *OAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthRequest.ProtoReflect.Descriptor instead.
func (*OAuthRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_authentication_service_proto_rawDescGZIP(), []int{1}
}

type OAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          *OAuthKeys             `protobuf:"bytes,1,opt,name=keys" json:"keys,omitempty"`
	Unk2          *uint32                `protobuf:"varint,2,opt,name=unk2" json:"unk2,omitempty"` // 0
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OAuthResponse) Reset() {
	*x = OAuthResponse{}
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthResponse) ProtoMessage() {}

func (x *OAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthResponse.ProtoReflect.Descriptor instead.
func (*OAuthResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_authentication_service_proto_rawDescGZIP(), []int{2}
}

func (x *OAuthResponse) GetKeys() *OAuthKeys {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *OAuthResponse) GetUnk2() uint32 {
	if x != nil && x.Unk2 != nil {
		return *x.Unk2
	}
	return 0
}

type OAuthKeys struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConsumerKey    *string                `protobuf:"bytes,1,opt,name=consumerKey" json:"consumerKey,omitempty"`
	ConsumerSecret *string                `protobuf:"bytes,2,opt,name=consumerSecret" json:"consumerSecret,omitempty"`
	OauthToken     *string                `protobuf:"bytes,3,opt,name=oauthToken" json:"oauthToken,omitempty"`
	OauthSecret    *string                `protobuf:"bytes,4,opt,name=oauthSecret" json:"oauthSecret,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OAuthKeys) Reset() {
	*x = OAuthKeys{}
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OAuthKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OAuthKeys) ProtoMessage() {}

func (x *OAuthKeys) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_authentication_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OAuthKeys.ProtoReflect.Descriptor instead.
func (*OAuthKeys) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_authentication_service_proto_rawDescGZIP(), []int{3}
}

func (x *OAuthKeys) GetConsumerKey() string {
	if x != nil && x.ConsumerKey != nil {
		return *x.ConsumerKey
	}
	return ""
}

func (x *OAuthKeys) GetConsumerSecret() string {
	if x != nil && x.ConsumerSecret != nil {
		return *x.ConsumerSecret
	}
	return ""
}

func (x *OAuthKeys) GetOauthToken() string {
	if x != nil && x.OauthToken != nil {
		return *x.OauthToken
	}
	return ""
}

func (x *OAuthKeys) GetOauthSecret() string {
	if x != nil && x.OauthSecret != nil {
		return *x.OauthSecret
	}
	return ""
}

var File_garmin_gdi_authentication_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_authentication_service_proto_rawDesc = "" +
	"\n" +
	"'garmin/gdi_authentication_service.proto\x12\x11garmin_vivomovehr\"\xa4\x01\n" +
	"\x15AuthenticationService\x12C\n" +
	"\foauthRequest\x18\x01 \x01(\v2\x1f.garmin_vivomovehr.OAuthRequestR\foauthRequest\x12F\n" +
	"\roauthResponse\x18\x02 \x01(\v2 .garmin_vivomovehr.OAuthResponseR\roauthResponse\"\x0e\n" +
	"\fOAuthRequest\"U\n" +
	"\rOAuthResponse\x120\n" +
	"\x04keys\x18\x01 \x01(\v2\x1c.garmin_vivomovehr.OAuthKeysR\x04keys\x12\x12\n" +
	"\x04unk2\x18\x02 \x01(\rR\x04unk2\"\x97\x01\n" +
	"\tOAuthKeys\x12 \n" +
	"\vconsumerKey\x18\x01 \x01(\tR\vconsumerKey\x12&\n" +
	"\x0econsumerSecret\x18\x02 \x01(\tR\x0econsumerSecret\x12\x1e\n" +
	"\n" +
	"oauthToken\x18\x03 \x01(\tR\n" +
	"oauthToken\x12 \n" +
	"\voauthSecret\x18\x04 \x01(\tR\voauthSecretBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_authentication_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_authentication_service_proto_rawDescData []byte
)

func file_garmin_gdi_authentication_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_authentication_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_authentication_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_authentication_service_proto_rawDesc), len(file_garmin_gdi_authentication_service_proto_rawDesc)))
	})
	return file_garmin_gdi_authentication_service_proto_rawDescData
}

var file_garmin_gdi_authentication_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_garmin_gdi_authentication_service_proto_goTypes = []any{
	(*AuthenticationService)(nil), // 0: garmin_vivomovehr.AuthenticationService
	(*OAuthRequest)(nil),          // 1: garmin_vivomovehr.OAuthRequest
	(*OAuthResponse)(nil),         // 2: garmin_vivomovehr.OAuthResponse
	(*OAuthKeys)(nil),             // 3: garmin_vivomovehr.OAuthKeys
}
var file_garmin_gdi_authentication_service_proto_depIdxs = []int32{
	1, // 0: garmin_vivomovehr.AuthenticationService.oauthRequest:type_name -> garmin_vivomovehr.OAuthRequest
	2, // 1: garmin_vivomovehr.AuthenticationService.oauthResponse:type_name -> garmin_vivomovehr.OAuthResponse
	3, // 2: garmin_vivomovehr.OAuthResponse.keys:type_name -> garmin_vivomovehr.OAuthKeys
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_garmin_gdi_authentication_service_proto_init() }
func file_garmin_gdi_authentication_service_proto_init() {
	if File_garmin_gdi_authentication_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_authentication_service_proto_rawDesc), len(file_garmin_gdi_authentication_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_authentication_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_authentication_service_proto_depIdxs,
		MessageInfos:      file_garmin_gdi_authentication_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_authentication_service_proto = out.File
	file_garmin_gdi_authentication_service_proto_goTypes = nil
	file_garmin_gdi_authentication_service_proto_depIdxs = nil
}
