// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_calendar_service.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CalendarService_CalendarServiceResponse_ResponseStatus int32

const (
	CalendarService_CalendarServiceResponse_UNKNOWN_RESPONSE_STATUS CalendarService_CalendarServiceResponse_ResponseStatus = 0
	CalendarService_CalendarServiceResponse_OK                      CalendarService_CalendarServiceResponse_ResponseStatus = 1
	CalendarService_CalendarServiceResponse_INVALID_DATE_RANGE      CalendarService_CalendarServiceResponse_ResponseStatus = 2
)

// Enum value maps for CalendarService_CalendarServiceResponse_ResponseStatus.
var (
	CalendarService_CalendarServiceResponse_ResponseStatus_name = map[int32]string{
		0: "UNKNOWN_RESPONSE_STATUS",
		1: "OK",
		2: "INVALID_DATE_RANGE",
	}
	CalendarService_CalendarServiceResponse_ResponseStatus_value = map[string]int32{
		"UNKNOWN_RESPONSE_STATUS": 0,
		"OK":                      1,
		"INVALID_DATE_RANGE":      2,
	}
)

func (x CalendarService_CalendarServiceResponse_ResponseStatus) Enum() *CalendarService_CalendarServiceResponse_ResponseStatus {
	p := new(CalendarService_CalendarServiceResponse_ResponseStatus)
	*p = x
	return p
}

func (x CalendarService_CalendarServiceResponse_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CalendarService_CalendarServiceResponse_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_calendar_service_proto_enumTypes[0].Descriptor()
}

func (CalendarService_CalendarServiceResponse_ResponseStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_calendar_service_proto_enumTypes[0]
}

func (x CalendarService_CalendarServiceResponse_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CalendarService_CalendarServiceResponse_ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CalendarService_CalendarServiceResponse_ResponseStatus(num)
	return nil
}

// Deprecated: Use CalendarService_CalendarServiceResponse_ResponseStatus.Descriptor instead.
func (CalendarService_CalendarServiceResponse_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_calendar_service_proto_rawDescGZIP(), []int{0, 1, 0}
}

type CalendarService struct {
	state            protoimpl.MessageState                   `protogen:"open.v1"`
	CalendarRequest  *CalendarService_CalendarServiceRequest  `protobuf:"bytes,1,opt,name=calendar_request,json=calendarRequest" json:"calendar_request,omitempty"`
	CalendarResponse *CalendarService_CalendarServiceResponse `protobuf:"bytes,2,opt,name=calendar_response,json=calendarResponse" json:"calendar_response,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CalendarService) Reset() {
	*x = CalendarService{}
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarService) ProtoMessage() {}

func (x *CalendarService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarService.ProtoReflect.Descriptor instead.
func (*CalendarService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_calendar_service_proto_rawDescGZIP(), []int{0}
}

func (x *CalendarService) GetCalendarRequest() *CalendarService_CalendarServiceRequest {
	if x != nil {
		return x.CalendarRequest
	}
	return nil
}

func (x *CalendarService) GetCalendarResponse() *CalendarService_CalendarServiceResponse {
	if x != nil {
		return x.CalendarResponse
	}
	return nil
}

type CalendarService_CalendarServiceRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Begin                *uint32                `protobuf:"varint,1,opt,name=begin" json:"begin,omitempty"`
	End                  *uint32                `protobuf:"varint,2,opt,name=end" json:"end,omitempty"`
	IncludeOrganizer     *bool                  `protobuf:"varint,3,opt,name=include_organizer,json=includeOrganizer,def=0" json:"include_organizer,omitempty"`
	IncludeTitle         *bool                  `protobuf:"varint,4,opt,name=include_title,json=includeTitle,def=1" json:"include_title,omitempty"`
	IncludeLocation      *bool                  `protobuf:"varint,5,opt,name=include_location,json=includeLocation,def=1" json:"include_location,omitempty"`
	IncludeDescription   *bool                  `protobuf:"varint,6,opt,name=include_description,json=includeDescription,def=0" json:"include_description,omitempty"`
	IncludeStartDate     *bool                  `protobuf:"varint,7,opt,name=include_start_date,json=includeStartDate,def=1" json:"include_start_date,omitempty"`
	IncludeEndDate       *bool                  `protobuf:"varint,8,opt,name=include_end_date,json=includeEndDate,def=0" json:"include_end_date,omitempty"`
	IncludeAllDay        *bool                  `protobuf:"varint,9,opt,name=include_all_day,json=includeAllDay,def=0" json:"include_all_day,omitempty"`
	MaxOrganizerLength   *uint32                `protobuf:"varint,10,opt,name=max_organizer_length,json=maxOrganizerLength" json:"max_organizer_length,omitempty"`
	MaxTitleLength       *uint32                `protobuf:"varint,11,opt,name=max_title_length,json=maxTitleLength" json:"max_title_length,omitempty"`
	MaxLocationLength    *uint32                `protobuf:"varint,12,opt,name=max_location_length,json=maxLocationLength" json:"max_location_length,omitempty"`
	MaxDescriptionLength *uint32                `protobuf:"varint,13,opt,name=max_description_length,json=maxDescriptionLength" json:"max_description_length,omitempty"`
	MaxEvents            *uint32                `protobuf:"varint,14,opt,name=max_events,json=maxEvents" json:"max_events,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

// Default values for CalendarService_CalendarServiceRequest fields.
const (
	Default_CalendarService_CalendarServiceRequest_IncludeOrganizer   = bool(false)
	Default_CalendarService_CalendarServiceRequest_IncludeTitle       = bool(true)
	Default_CalendarService_CalendarServiceRequest_IncludeLocation    = bool(true)
	Default_CalendarService_CalendarServiceRequest_IncludeDescription = bool(false)
	Default_CalendarService_CalendarServiceRequest_IncludeStartDate   = bool(true)
	Default_CalendarService_CalendarServiceRequest_IncludeEndDate     = bool(false)
	Default_CalendarService_CalendarServiceRequest_IncludeAllDay      = bool(false)
)

func (x *CalendarService_CalendarServiceRequest) Reset() {
	*x = CalendarService_CalendarServiceRequest{}
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarService_CalendarServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarService_CalendarServiceRequest) ProtoMessage() {}

func (x *CalendarService_CalendarServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarService_CalendarServiceRequest.ProtoReflect.Descriptor instead.
func (*CalendarService_CalendarServiceRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_calendar_service_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CalendarService_CalendarServiceRequest) GetBegin() uint32 {
	if x != nil && x.Begin != nil {
		return *x.Begin
	}
	return 0
}

func (x *CalendarService_CalendarServiceRequest) GetEnd() uint32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeOrganizer() bool {
	if x != nil && x.IncludeOrganizer != nil {
		return *x.IncludeOrganizer
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeOrganizer
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeTitle() bool {
	if x != nil && x.IncludeTitle != nil {
		return *x.IncludeTitle
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeTitle
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeLocation() bool {
	if x != nil && x.IncludeLocation != nil {
		return *x.IncludeLocation
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeLocation
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeDescription() bool {
	if x != nil && x.IncludeDescription != nil {
		return *x.IncludeDescription
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeDescription
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeStartDate() bool {
	if x != nil && x.IncludeStartDate != nil {
		return *x.IncludeStartDate
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeStartDate
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeEndDate() bool {
	if x != nil && x.IncludeEndDate != nil {
		return *x.IncludeEndDate
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeEndDate
}

func (x *CalendarService_CalendarServiceRequest) GetIncludeAllDay() bool {
	if x != nil && x.IncludeAllDay != nil {
		return *x.IncludeAllDay
	}
	return Default_CalendarService_CalendarServiceRequest_IncludeAllDay
}

func (x *CalendarService_CalendarServiceRequest) GetMaxOrganizerLength() uint32 {
	if x != nil && x.MaxOrganizerLength != nil {
		return *x.MaxOrganizerLength
	}
	return 0
}

func (x *CalendarService_CalendarServiceRequest) GetMaxTitleLength() uint32 {
	if x != nil && x.MaxTitleLength != nil {
		return *x.MaxTitleLength
	}
	return 0
}

func (x *CalendarService_CalendarServiceRequest) GetMaxLocationLength() uint32 {
	if x != nil && x.MaxLocationLength != nil {
		return *x.MaxLocationLength
	}
	return 0
}

func (x *CalendarService_CalendarServiceRequest) GetMaxDescriptionLength() uint32 {
	if x != nil && x.MaxDescriptionLength != nil {
		return *x.MaxDescriptionLength
	}
	return 0
}

func (x *CalendarService_CalendarServiceRequest) GetMaxEvents() uint32 {
	if x != nil && x.MaxEvents != nil {
		return *x.MaxEvents
	}
	return 0
}

type CalendarService_CalendarServiceResponse struct {
	state         protoimpl.MessageState                                  `protogen:"open.v1"`
	Status        *CalendarService_CalendarServiceResponse_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.CalendarService_CalendarServiceResponse_ResponseStatus" json:"status,omitempty"`
	CalendarEvent []*CalendarService_CalendarEvent                        `protobuf:"bytes,2,rep,name=calendar_event,json=calendarEvent" json:"calendar_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalendarService_CalendarServiceResponse) Reset() {
	*x = CalendarService_CalendarServiceResponse{}
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarService_CalendarServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarService_CalendarServiceResponse) ProtoMessage() {}

func (x *CalendarService_CalendarServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarService_CalendarServiceResponse.ProtoReflect.Descriptor instead.
func (*CalendarService_CalendarServiceResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_calendar_service_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CalendarService_CalendarServiceResponse) GetStatus() CalendarService_CalendarServiceResponse_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CalendarService_CalendarServiceResponse_UNKNOWN_RESPONSE_STATUS
}

func (x *CalendarService_CalendarServiceResponse) GetCalendarEvent() []*CalendarService_CalendarEvent {
	if x != nil {
		return x.CalendarEvent
	}
	return nil
}

type CalendarService_CalendarEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Organizer          *string                `protobuf:"bytes,1,opt,name=organizer" json:"organizer,omitempty"`
	Title              *string                `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Location           *string                `protobuf:"bytes,3,opt,name=location,def=" json:"location,omitempty"`
	Description        *string                `protobuf:"bytes,4,opt,name=description,def=" json:"description,omitempty"`
	StartDate          *uint32                `protobuf:"varint,5,opt,name=start_date,json=startDate" json:"start_date,omitempty"`
	EndDate            *uint32                `protobuf:"varint,6,opt,name=end_date,json=endDate" json:"end_date,omitempty"`
	AllDay             *bool                  `protobuf:"varint,7,opt,name=all_day,json=allDay" json:"all_day,omitempty"`
	ReminderTimeInSecs []uint32               `protobuf:"varint,8,rep,name=reminder_time_in_secs,json=reminderTimeInSecs" json:"reminder_time_in_secs,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

// Default values for CalendarService_CalendarEvent fields.
const (
	Default_CalendarService_CalendarEvent_Location    = string("")
	Default_CalendarService_CalendarEvent_Description = string("")
)

func (x *CalendarService_CalendarEvent) Reset() {
	*x = CalendarService_CalendarEvent{}
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalendarService_CalendarEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalendarService_CalendarEvent) ProtoMessage() {}

func (x *CalendarService_CalendarEvent) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_calendar_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalendarService_CalendarEvent.ProtoReflect.Descriptor instead.
func (*CalendarService_CalendarEvent) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_calendar_service_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CalendarService_CalendarEvent) GetOrganizer() string {
	if x != nil && x.Organizer != nil {
		return *x.Organizer
	}
	return ""
}

func (x *CalendarService_CalendarEvent) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *CalendarService_CalendarEvent) GetLocation() string {
	if x != nil && x.Location != nil {
		return *x.Location
	}
	return Default_CalendarService_CalendarEvent_Location
}

func (x *CalendarService_CalendarEvent) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return Default_CalendarService_CalendarEvent_Description
}

func (x *CalendarService_CalendarEvent) GetStartDate() uint32 {
	if x != nil && x.StartDate != nil {
		return *x.StartDate
	}
	return 0
}

func (x *CalendarService_CalendarEvent) GetEndDate() uint32 {
	if x != nil && x.EndDate != nil {
		return *x.EndDate
	}
	return 0
}

func (x *CalendarService_CalendarEvent) GetAllDay() bool {
	if x != nil && x.AllDay != nil {
		return *x.AllDay
	}
	return false
}

func (x *CalendarService_CalendarEvent) GetReminderTimeInSecs() []uint32 {
	if x != nil {
		return x.ReminderTimeInSecs
	}
	return nil
}

var File_garmin_gdi_calendar_service_proto protoreflect.FileDescriptor

const file_garmin_gdi_calendar_service_proto_rawDesc = "" +
	"\n" +
	"!garmin/gdi_calendar_service.proto\x12\x11garmin_vivomovehr\"\x95\v\n" +
	"\x0fCalendarService\x12d\n" +
	"\x10calendar_request\x18\x01 \x01(\v29.garmin_vivomovehr.CalendarService.CalendarServiceRequestR\x0fcalendarRequest\x12g\n" +
	"\x11calendar_response\x18\x02 \x01(\v2:.garmin_vivomovehr.CalendarService.CalendarServiceResponseR\x10calendarResponse\x1a\xfd\x04\n" +
	"\x16CalendarServiceRequest\x12\x14\n" +
	"\x05begin\x18\x01 \x01(\rR\x05begin\x12\x10\n" +
	"\x03end\x18\x02 \x01(\rR\x03end\x122\n" +
	"\x11include_organizer\x18\x03 \x01(\b:\x05falseR\x10includeOrganizer\x12)\n" +
	"\rinclude_title\x18\x04 \x01(\b:\x04trueR\fincludeTitle\x12/\n" +
	"\x10include_location\x18\x05 \x01(\b:\x04trueR\x0fincludeLocation\x126\n" +
	"\x13include_description\x18\x06 \x01(\b:\x05falseR\x12includeDescription\x122\n" +
	"\x12include_start_date\x18\a \x01(\b:\x04trueR\x10includeStartDate\x12/\n" +
	"\x10include_end_date\x18\b \x01(\b:\x05falseR\x0eincludeEndDate\x12-\n" +
	"\x0finclude_all_day\x18\t \x01(\b:\x05falseR\rincludeAllDay\x120\n" +
	"\x14max_organizer_length\x18\n" +
	" \x01(\rR\x12maxOrganizerLength\x12(\n" +
	"\x10max_title_length\x18\v \x01(\rR\x0emaxTitleLength\x12.\n" +
	"\x13max_location_length\x18\f \x01(\rR\x11maxLocationLength\x124\n" +
	"\x16max_description_length\x18\r \x01(\rR\x14maxDescriptionLength\x12\x1d\n" +
	"\n" +
	"max_events\x18\x0e \x01(\rR\tmaxEvents\x1a\xa4\x02\n" +
	"\x17CalendarServiceResponse\x12a\n" +
	"\x06status\x18\x01 \x01(\x0e2I.garmin_vivomovehr.CalendarService.CalendarServiceResponse.ResponseStatusR\x06status\x12W\n" +
	"\x0ecalendar_event\x18\x02 \x03(\v20.garmin_vivomovehr.CalendarService.CalendarEventR\rcalendarEvent\"M\n" +
	"\x0eResponseStatus\x12\x1b\n" +
	"\x17UNKNOWN_RESPONSE_STATUS\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\x16\n" +
	"\x12INVALID_DATE_RANGE\x10\x02\x1a\x8b\x02\n" +
	"\rCalendarEvent\x12\x1c\n" +
	"\torganizer\x18\x01 \x01(\tR\torganizer\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1c\n" +
	"\blocation\x18\x03 \x01(\t:\x00R\blocation\x12\"\n" +
	"\vdescription\x18\x04 \x01(\t:\x00R\vdescription\x12\x1d\n" +
	"\n" +
	"start_date\x18\x05 \x01(\rR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x06 \x01(\rR\aendDate\x12\x17\n" +
	"\aall_day\x18\a \x01(\bR\x06allDay\x121\n" +
	"\x15reminder_time_in_secs\x18\b \x03(\rR\x12reminderTimeInSecsBY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_calendar_service_proto_rawDescOnce sync.Once
	file_garmin_gdi_calendar_service_proto_rawDescData []byte
)

func file_garmin_gdi_calendar_service_proto_rawDescGZIP() []byte {
	file_garmin_gdi_calendar_service_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_calendar_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_calendar_service_proto_rawDesc), len(file_garmin_gdi_calendar_service_proto_rawDesc)))
	})
	return file_garmin_gdi_calendar_service_proto_rawDescData
}

var file_garmin_gdi_calendar_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_garmin_gdi_calendar_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_garmin_gdi_calendar_service_proto_goTypes = []any{
	(CalendarService_CalendarServiceResponse_ResponseStatus)(0), // 0: garmin_vivomovehr.CalendarService.CalendarServiceResponse.ResponseStatus
	(*CalendarService)(nil),                         // 1: garmin_vivomovehr.CalendarService
	(*CalendarService_CalendarServiceRequest)(nil),  // 2: garmin_vivomovehr.CalendarService.CalendarServiceRequest
	(*CalendarService_CalendarServiceResponse)(nil), // 3: garmin_vivomovehr.CalendarService.CalendarServiceResponse
	(*CalendarService_CalendarEvent)(nil),           // 4: garmin_vivomovehr.CalendarService.CalendarEvent
}
var file_garmin_gdi_calendar_service_proto_depIdxs = []int32{
	2, // 0: garmin_vivomovehr.CalendarService.calendar_request:type_name -> garmin_vivomovehr.CalendarService.CalendarServiceRequest
	3, // 1: garmin_vivomovehr.CalendarService.calendar_response:type_name -> garmin_vivomovehr.CalendarService.CalendarServiceResponse
	0, // 2: garmin_vivomovehr.CalendarService.CalendarServiceResponse.status:type_name -> garmin_vivomovehr.CalendarService.CalendarServiceResponse.ResponseStatus
	4, // 3: garmin_vivomovehr.CalendarService.CalendarServiceResponse.calendar_event:type_name -> garmin_vivomovehr.CalendarService.CalendarEvent
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_garmin_gdi_calendar_service_proto_init() }
func file_garmin_gdi_calendar_service_proto_init() {
	if File_garmin_gdi_calendar_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_calendar_service_proto_rawDesc), len(file_garmin_gdi_calendar_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_calendar_service_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_calendar_service_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_calendar_service_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_calendar_service_proto_msgTypes,
	}.Build()
	File_garmin_gdi_calendar_service_proto = out.File
	file_garmin_gdi_calendar_service_proto_goTypes = nil
	file_garmin_gdi_calendar_service_proto_depIdxs = nil
}
