// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: garmin/gdi_core.proto

package garmin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoreService_DataType int32

const (
	CoreService_SIGNIFICANT_LOCATION CoreService_DataType = 0
	CoreService_GENERAL_LOCATION     CoreService_DataType = 1
	CoreService_REALTIME_TRACKING    CoreService_DataType = 2
	CoreService_INREACH_TRACKING     CoreService_DataType = 3
	CoreService_TRACKING_EVENT       CoreService_DataType = 4
)

// Enum value maps for CoreService_DataType.
var (
	CoreService_DataType_name = map[int32]string{
		0: "SIGNIFICANT_LOCATION",
		1: "GENERAL_LOCATION",
		2: "REALTIME_TRACKING",
		3: "INREACH_TRACKING",
		4: "TRACKING_EVENT",
	}
	CoreService_DataType_value = map[string]int32{
		"SIGNIFICANT_LOCATION": 0,
		"GENERAL_LOCATION":     1,
		"REALTIME_TRACKING":    2,
		"INREACH_TRACKING":     3,
		"TRACKING_EVENT":       4,
	}
)

func (x CoreService_DataType) Enum() *CoreService_DataType {
	p := new(CoreService_DataType)
	*p = x
	return p
}

func (x CoreService_DataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreService_DataType) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_core_proto_enumTypes[0].Descriptor()
}

func (CoreService_DataType) Type() protoreflect.EnumType {
	return &file_garmin_gdi_core_proto_enumTypes[0]
}

func (x CoreService_DataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CoreService_DataType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CoreService_DataType(num)
	return nil
}

// Deprecated: Use CoreService_DataType.Descriptor instead.
func (CoreService_DataType) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 0}
}

type CoreService_SyncResponse_ResponseStatus int32

const (
	CoreService_SyncResponse_UNKNOWN_RESPONSE_STATUS CoreService_SyncResponse_ResponseStatus = 0
	CoreService_SyncResponse_OK                      CoreService_SyncResponse_ResponseStatus = 1
)

// Enum value maps for CoreService_SyncResponse_ResponseStatus.
var (
	CoreService_SyncResponse_ResponseStatus_name = map[int32]string{
		0: "UNKNOWN_RESPONSE_STATUS",
		1: "OK",
	}
	CoreService_SyncResponse_ResponseStatus_value = map[string]int32{
		"UNKNOWN_RESPONSE_STATUS": 0,
		"OK":                      1,
	}
)

func (x CoreService_SyncResponse_ResponseStatus) Enum() *CoreService_SyncResponse_ResponseStatus {
	p := new(CoreService_SyncResponse_ResponseStatus)
	*p = x
	return p
}

func (x CoreService_SyncResponse_ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreService_SyncResponse_ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_core_proto_enumTypes[1].Descriptor()
}

func (CoreService_SyncResponse_ResponseStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_core_proto_enumTypes[1]
}

func (x CoreService_SyncResponse_ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CoreService_SyncResponse_ResponseStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CoreService_SyncResponse_ResponseStatus(num)
	return nil
}

// Deprecated: Use CoreService_SyncResponse_ResponseStatus.Descriptor instead.
func (CoreService_SyncResponse_ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 1, 0}
}

type CoreService_GetLocationRequest_RequestType int32

const (
	CoreService_GetLocationRequest_STANDARD  CoreService_GetLocationRequest_RequestType = 0
	CoreService_GetLocationRequest_EMERGENCY CoreService_GetLocationRequest_RequestType = 1
)

// Enum value maps for CoreService_GetLocationRequest_RequestType.
var (
	CoreService_GetLocationRequest_RequestType_name = map[int32]string{
		0: "STANDARD",
		1: "EMERGENCY",
	}
	CoreService_GetLocationRequest_RequestType_value = map[string]int32{
		"STANDARD":  0,
		"EMERGENCY": 1,
	}
)

func (x CoreService_GetLocationRequest_RequestType) Enum() *CoreService_GetLocationRequest_RequestType {
	p := new(CoreService_GetLocationRequest_RequestType)
	*p = x
	return p
}

func (x CoreService_GetLocationRequest_RequestType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreService_GetLocationRequest_RequestType) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_core_proto_enumTypes[2].Descriptor()
}

func (CoreService_GetLocationRequest_RequestType) Type() protoreflect.EnumType {
	return &file_garmin_gdi_core_proto_enumTypes[2]
}

func (x CoreService_GetLocationRequest_RequestType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CoreService_GetLocationRequest_RequestType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CoreService_GetLocationRequest_RequestType(num)
	return nil
}

// Deprecated: Use CoreService_GetLocationRequest_RequestType.Descriptor instead.
func (CoreService_GetLocationRequest_RequestType) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 2, 0}
}

type CoreService_GetLocationResponse_Status int32

const (
	CoreService_GetLocationResponse_OK                            CoreService_GetLocationResponse_Status = 1
	CoreService_GetLocationResponse_NO_VALID_LOCATION             CoreService_GetLocationResponse_Status = 2
	CoreService_GetLocationResponse_LOCATION_SERVICES_UNAVAILABLE CoreService_GetLocationResponse_Status = 3
	CoreService_GetLocationResponse_LOCATION_SERVICES_DISABLED    CoreService_GetLocationResponse_Status = 4
	CoreService_GetLocationResponse_TRY_AGAIN_LATER               CoreService_GetLocationResponse_Status = 5
)

// Enum value maps for CoreService_GetLocationResponse_Status.
var (
	CoreService_GetLocationResponse_Status_name = map[int32]string{
		1: "OK",
		2: "NO_VALID_LOCATION",
		3: "LOCATION_SERVICES_UNAVAILABLE",
		4: "LOCATION_SERVICES_DISABLED",
		5: "TRY_AGAIN_LATER",
	}
	CoreService_GetLocationResponse_Status_value = map[string]int32{
		"OK":                            1,
		"NO_VALID_LOCATION":             2,
		"LOCATION_SERVICES_UNAVAILABLE": 3,
		"LOCATION_SERVICES_DISABLED":    4,
		"TRY_AGAIN_LATER":               5,
	}
)

func (x CoreService_GetLocationResponse_Status) Enum() *CoreService_GetLocationResponse_Status {
	p := new(CoreService_GetLocationResponse_Status)
	*p = x
	return p
}

func (x CoreService_GetLocationResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreService_GetLocationResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_core_proto_enumTypes[3].Descriptor()
}

func (CoreService_GetLocationResponse_Status) Type() protoreflect.EnumType {
	return &file_garmin_gdi_core_proto_enumTypes[3]
}

func (x CoreService_GetLocationResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CoreService_GetLocationResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CoreService_GetLocationResponse_Status(num)
	return nil
}

// Deprecated: Use CoreService_GetLocationResponse_Status.Descriptor instead.
func (CoreService_GetLocationResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 3, 0}
}

type CoreService_LocationUpdatedSetEnabledResponse_Status int32

const (
	CoreService_LocationUpdatedSetEnabledResponse_OK          CoreService_LocationUpdatedSetEnabledResponse_Status = 1
	CoreService_LocationUpdatedSetEnabledResponse_UNAVAILABLE CoreService_LocationUpdatedSetEnabledResponse_Status = 2
	CoreService_LocationUpdatedSetEnabledResponse_UNKNOWN3    CoreService_LocationUpdatedSetEnabledResponse_Status = 3
	CoreService_LocationUpdatedSetEnabledResponse_UNKNOWN4    CoreService_LocationUpdatedSetEnabledResponse_Status = 4
)

// Enum value maps for CoreService_LocationUpdatedSetEnabledResponse_Status.
var (
	CoreService_LocationUpdatedSetEnabledResponse_Status_name = map[int32]string{
		1: "OK",
		2: "UNAVAILABLE",
		3: "UNKNOWN3",
		4: "UNKNOWN4",
	}
	CoreService_LocationUpdatedSetEnabledResponse_Status_value = map[string]int32{
		"OK":          1,
		"UNAVAILABLE": 2,
		"UNKNOWN3":    3,
		"UNKNOWN4":    4,
	}
)

func (x CoreService_LocationUpdatedSetEnabledResponse_Status) Enum() *CoreService_LocationUpdatedSetEnabledResponse_Status {
	p := new(CoreService_LocationUpdatedSetEnabledResponse_Status)
	*p = x
	return p
}

func (x CoreService_LocationUpdatedSetEnabledResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreService_LocationUpdatedSetEnabledResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_core_proto_enumTypes[4].Descriptor()
}

func (CoreService_LocationUpdatedSetEnabledResponse_Status) Type() protoreflect.EnumType {
	return &file_garmin_gdi_core_proto_enumTypes[4]
}

func (x CoreService_LocationUpdatedSetEnabledResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CoreService_LocationUpdatedSetEnabledResponse_Status) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CoreService_LocationUpdatedSetEnabledResponse_Status(num)
	return nil
}

// Deprecated: Use CoreService_LocationUpdatedSetEnabledResponse_Status.Descriptor instead.
func (CoreService_LocationUpdatedSetEnabledResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 6, 0}
}

type CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus int32

const (
	CoreService_LocationUpdatedSetEnabledResponse_Requested_OK CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus = 1
	CoreService_LocationUpdatedSetEnabledResponse_Requested_KO CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus = 2
)

// Enum value maps for CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus.
var (
	CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus_name = map[int32]string{
		1: "OK",
		2: "KO",
	}
	CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus_value = map[string]int32{
		"OK": 1,
		"KO": 2,
	}
)

func (x CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) Enum() *CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus {
	p := new(CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus)
	*p = x
	return p
}

func (x CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_garmin_gdi_core_proto_enumTypes[5].Descriptor()
}

func (CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) Type() protoreflect.EnumType {
	return &file_garmin_gdi_core_proto_enumTypes[5]
}

func (x CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus(num)
	return nil
}

// Deprecated: Use CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus.Descriptor instead.
func (CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus) EnumDescriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 6, 0, 0}
}

type CoreService struct {
	state                             protoimpl.MessageState                         `protogen:"open.v1"`
	SyncRequest                       *CoreService_SyncRequest                       `protobuf:"bytes,1,opt,name=sync_request,json=syncRequest" json:"sync_request,omitempty"`
	SyncResponse                      *CoreService_SyncResponse                      `protobuf:"bytes,2,opt,name=sync_response,json=syncResponse" json:"sync_response,omitempty"`
	GetLocationRequest                *CoreService_GetLocationRequest                `protobuf:"bytes,3,opt,name=get_location_request,json=getLocationRequest" json:"get_location_request,omitempty"`
	GetLocationResponse               *CoreService_GetLocationResponse               `protobuf:"bytes,4,opt,name=get_location_response,json=getLocationResponse" json:"get_location_response,omitempty"`
	LocationUpdatedSetEnabledRequest  *CoreService_LocationUpdatedSetEnabledRequest  `protobuf:"bytes,5,opt,name=location_updated_set_enabled_request,json=locationUpdatedSetEnabledRequest" json:"location_updated_set_enabled_request,omitempty"`
	LocationUpdatedSetEnabledResponse *CoreService_LocationUpdatedSetEnabledResponse `protobuf:"bytes,6,opt,name=location_updated_set_enabled_response,json=locationUpdatedSetEnabledResponse" json:"location_updated_set_enabled_response,omitempty"`
	LocationUpdatedNotification       *CoreService_LocationUpdatedNotification       `protobuf:"bytes,7,opt,name=location_updated_notification,json=locationUpdatedNotification" json:"location_updated_notification,omitempty"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *CoreService) Reset() {
	*x = CoreService{}
	mi := &file_garmin_gdi_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService) ProtoMessage() {}

func (x *CoreService) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService.ProtoReflect.Descriptor instead.
func (*CoreService) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0}
}

func (x *CoreService) GetSyncRequest() *CoreService_SyncRequest {
	if x != nil {
		return x.SyncRequest
	}
	return nil
}

func (x *CoreService) GetSyncResponse() *CoreService_SyncResponse {
	if x != nil {
		return x.SyncResponse
	}
	return nil
}

func (x *CoreService) GetGetLocationRequest() *CoreService_GetLocationRequest {
	if x != nil {
		return x.GetLocationRequest
	}
	return nil
}

func (x *CoreService) GetGetLocationResponse() *CoreService_GetLocationResponse {
	if x != nil {
		return x.GetLocationResponse
	}
	return nil
}

func (x *CoreService) GetLocationUpdatedSetEnabledRequest() *CoreService_LocationUpdatedSetEnabledRequest {
	if x != nil {
		return x.LocationUpdatedSetEnabledRequest
	}
	return nil
}

func (x *CoreService) GetLocationUpdatedSetEnabledResponse() *CoreService_LocationUpdatedSetEnabledResponse {
	if x != nil {
		return x.LocationUpdatedSetEnabledResponse
	}
	return nil
}

func (x *CoreService) GetLocationUpdatedNotification() *CoreService_LocationUpdatedNotification {
	if x != nil {
		return x.LocationUpdatedNotification
	}
	return nil
}

type CoreService_SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_SyncRequest) Reset() {
	*x = CoreService_SyncRequest{}
	mi := &file_garmin_gdi_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_SyncRequest) ProtoMessage() {}

func (x *CoreService_SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_SyncRequest.ProtoReflect.Descriptor instead.
func (*CoreService_SyncRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 0}
}

type CoreService_SyncResponse struct {
	state         protoimpl.MessageState                   `protogen:"open.v1"`
	Status        *CoreService_SyncResponse_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.CoreService_SyncResponse_ResponseStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_SyncResponse) Reset() {
	*x = CoreService_SyncResponse{}
	mi := &file_garmin_gdi_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_SyncResponse) ProtoMessage() {}

func (x *CoreService_SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_SyncResponse.ProtoReflect.Descriptor instead.
func (*CoreService_SyncResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 1}
}

func (x *CoreService_SyncResponse) GetStatus() CoreService_SyncResponse_ResponseStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CoreService_SyncResponse_UNKNOWN_RESPONSE_STATUS
}

type CoreService_GetLocationRequest struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	RequestType   *CoreService_GetLocationRequest_RequestType `protobuf:"varint,1,opt,name=request_type,json=requestType,enum=garmin_vivomovehr.CoreService_GetLocationRequest_RequestType" json:"request_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_GetLocationRequest) Reset() {
	*x = CoreService_GetLocationRequest{}
	mi := &file_garmin_gdi_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_GetLocationRequest) ProtoMessage() {}

func (x *CoreService_GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_GetLocationRequest.ProtoReflect.Descriptor instead.
func (*CoreService_GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 2}
}

func (x *CoreService_GetLocationRequest) GetRequestType() CoreService_GetLocationRequest_RequestType {
	if x != nil && x.RequestType != nil {
		return *x.RequestType
	}
	return CoreService_GetLocationRequest_STANDARD
}

type CoreService_GetLocationResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Status        *CoreService_GetLocationResponse_Status `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.CoreService_GetLocationResponse_Status" json:"status,omitempty"`
	LocationData  *CoreService_LocationData               `protobuf:"bytes,2,opt,name=location_data,json=locationData" json:"location_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_GetLocationResponse) Reset() {
	*x = CoreService_GetLocationResponse{}
	mi := &file_garmin_gdi_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_GetLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_GetLocationResponse) ProtoMessage() {}

func (x *CoreService_GetLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_GetLocationResponse.ProtoReflect.Descriptor instead.
func (*CoreService_GetLocationResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 3}
}

func (x *CoreService_GetLocationResponse) GetStatus() CoreService_GetLocationResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CoreService_GetLocationResponse_OK
}

func (x *CoreService_GetLocationResponse) GetLocationData() *CoreService_LocationData {
	if x != nil {
		return x.LocationData
	}
	return nil
}

type CoreService_LocationUpdatedSetEnabledRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled" json:"enabled,omitempty"`
	Requests      []*CoreService_Request `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_LocationUpdatedSetEnabledRequest) Reset() {
	*x = CoreService_LocationUpdatedSetEnabledRequest{}
	mi := &file_garmin_gdi_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_LocationUpdatedSetEnabledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_LocationUpdatedSetEnabledRequest) ProtoMessage() {}

func (x *CoreService_LocationUpdatedSetEnabledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_LocationUpdatedSetEnabledRequest.ProtoReflect.Descriptor instead.
func (*CoreService_LocationUpdatedSetEnabledRequest) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 4}
}

func (x *CoreService_LocationUpdatedSetEnabledRequest) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *CoreService_LocationUpdatedSetEnabledRequest) GetRequests() []*CoreService_Request {
	if x != nil {
		return x.Requests
	}
	return nil
}

type CoreService_Request struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Requested          *CoreService_DataType  `protobuf:"varint,1,opt,name=requested,enum=garmin_vivomovehr.CoreService_DataType" json:"requested,omitempty"`
	MinUpdateThreshold *float32               `protobuf:"fixed32,2,opt,name=min_update_threshold,json=minUpdateThreshold" json:"min_update_threshold,omitempty"`
	DistanceThreshold  *float32               `protobuf:"fixed32,3,opt,name=distance_threshold,json=distanceThreshold" json:"distance_threshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CoreService_Request) Reset() {
	*x = CoreService_Request{}
	mi := &file_garmin_gdi_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_Request) ProtoMessage() {}

func (x *CoreService_Request) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_Request.ProtoReflect.Descriptor instead.
func (*CoreService_Request) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 5}
}

func (x *CoreService_Request) GetRequested() CoreService_DataType {
	if x != nil && x.Requested != nil {
		return *x.Requested
	}
	return CoreService_SIGNIFICANT_LOCATION
}

func (x *CoreService_Request) GetMinUpdateThreshold() float32 {
	if x != nil && x.MinUpdateThreshold != nil {
		return *x.MinUpdateThreshold
	}
	return 0
}

func (x *CoreService_Request) GetDistanceThreshold() float32 {
	if x != nil && x.DistanceThreshold != nil {
		return *x.DistanceThreshold
	}
	return 0
}

type CoreService_LocationUpdatedSetEnabledResponse struct {
	state         protoimpl.MessageState                                     `protogen:"open.v1"`
	Status        *CoreService_LocationUpdatedSetEnabledResponse_Status      `protobuf:"varint,1,opt,name=status,enum=garmin_vivomovehr.CoreService_LocationUpdatedSetEnabledResponse_Status" json:"status,omitempty"`
	Requests      []*CoreService_LocationUpdatedSetEnabledResponse_Requested `protobuf:"bytes,2,rep,name=requests" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_LocationUpdatedSetEnabledResponse) Reset() {
	*x = CoreService_LocationUpdatedSetEnabledResponse{}
	mi := &file_garmin_gdi_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_LocationUpdatedSetEnabledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_LocationUpdatedSetEnabledResponse) ProtoMessage() {}

func (x *CoreService_LocationUpdatedSetEnabledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_LocationUpdatedSetEnabledResponse.ProtoReflect.Descriptor instead.
func (*CoreService_LocationUpdatedSetEnabledResponse) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 6}
}

func (x *CoreService_LocationUpdatedSetEnabledResponse) GetStatus() CoreService_LocationUpdatedSetEnabledResponse_Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CoreService_LocationUpdatedSetEnabledResponse_OK
}

func (x *CoreService_LocationUpdatedSetEnabledResponse) GetRequests() []*CoreService_LocationUpdatedSetEnabledResponse_Requested {
	if x != nil {
		return x.Requests
	}
	return nil
}

type CoreService_LocationUpdatedNotification struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	LocationData  []*CoreService_LocationData `protobuf:"bytes,1,rep,name=location_data,json=locationData" json:"location_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_LocationUpdatedNotification) Reset() {
	*x = CoreService_LocationUpdatedNotification{}
	mi := &file_garmin_gdi_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_LocationUpdatedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_LocationUpdatedNotification) ProtoMessage() {}

func (x *CoreService_LocationUpdatedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_LocationUpdatedNotification.ProtoReflect.Descriptor instead.
func (*CoreService_LocationUpdatedNotification) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 7}
}

func (x *CoreService_LocationUpdatedNotification) GetLocationData() []*CoreService_LocationData {
	if x != nil {
		return x.LocationData
	}
	return nil
}

type CoreService_LocationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *CoreService_LatLon    `protobuf:"bytes,1,req,name=position" json:"position,omitempty"`
	Altitude      *float32               `protobuf:"fixed32,2,req,name=altitude" json:"altitude,omitempty"`
	Timestamp     *uint32                `protobuf:"varint,3,req,name=timestamp" json:"timestamp,omitempty"`
	HAccuracy     *float32               `protobuf:"fixed32,4,req,name=h_accuracy,json=hAccuracy" json:"h_accuracy,omitempty"`
	VAccuracy     *float32               `protobuf:"fixed32,5,req,name=v_accuracy,json=vAccuracy" json:"v_accuracy,omitempty"`
	PositionType  *CoreService_DataType  `protobuf:"varint,6,req,name=position_type,json=positionType,enum=garmin_vivomovehr.CoreService_DataType" json:"position_type,omitempty"`
	Bearing       *float32               `protobuf:"fixed32,9,req,name=bearing" json:"bearing,omitempty"`
	Speed         *float32               `protobuf:"fixed32,10,req,name=speed" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_LocationData) Reset() {
	*x = CoreService_LocationData{}
	mi := &file_garmin_gdi_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_LocationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_LocationData) ProtoMessage() {}

func (x *CoreService_LocationData) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_LocationData.ProtoReflect.Descriptor instead.
func (*CoreService_LocationData) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 8}
}

func (x *CoreService_LocationData) GetPosition() *CoreService_LatLon {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *CoreService_LocationData) GetAltitude() float32 {
	if x != nil && x.Altitude != nil {
		return *x.Altitude
	}
	return 0
}

func (x *CoreService_LocationData) GetTimestamp() uint32 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *CoreService_LocationData) GetHAccuracy() float32 {
	if x != nil && x.HAccuracy != nil {
		return *x.HAccuracy
	}
	return 0
}

func (x *CoreService_LocationData) GetVAccuracy() float32 {
	if x != nil && x.VAccuracy != nil {
		return *x.VAccuracy
	}
	return 0
}

func (x *CoreService_LocationData) GetPositionType() CoreService_DataType {
	if x != nil && x.PositionType != nil {
		return *x.PositionType
	}
	return CoreService_SIGNIFICANT_LOCATION
}

func (x *CoreService_LocationData) GetBearing() float32 {
	if x != nil && x.Bearing != nil {
		return *x.Bearing
	}
	return 0
}

func (x *CoreService_LocationData) GetSpeed() float32 {
	if x != nil && x.Speed != nil {
		return *x.Speed
	}
	return 0
}

type CoreService_LatLon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           *int32                 `protobuf:"zigzag32,1,req,name=lat" json:"lat,omitempty"`
	Lon           *int32                 `protobuf:"zigzag32,2,req,name=lon" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_LatLon) Reset() {
	*x = CoreService_LatLon{}
	mi := &file_garmin_gdi_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_LatLon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_LatLon) ProtoMessage() {}

func (x *CoreService_LatLon) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_LatLon.ProtoReflect.Descriptor instead.
func (*CoreService_LatLon) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 9}
}

func (x *CoreService_LatLon) GetLat() int32 {
	if x != nil && x.Lat != nil {
		return *x.Lat
	}
	return 0
}

func (x *CoreService_LatLon) GetLon() int32 {
	if x != nil && x.Lon != nil {
		return *x.Lon
	}
	return 0
}

type CoreService_LocationUpdatedSetEnabledResponse_Requested struct {
	state         protoimpl.MessageState                                                   `protogen:"open.v1"`
	Requested     *CoreService_DataType                                                    `protobuf:"varint,1,opt,name=requested,enum=garmin_vivomovehr.CoreService_DataType" json:"requested,omitempty"`
	Status        *CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus `protobuf:"varint,2,opt,name=status,enum=garmin_vivomovehr.CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoreService_LocationUpdatedSetEnabledResponse_Requested) Reset() {
	*x = CoreService_LocationUpdatedSetEnabledResponse_Requested{}
	mi := &file_garmin_gdi_core_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoreService_LocationUpdatedSetEnabledResponse_Requested) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoreService_LocationUpdatedSetEnabledResponse_Requested) ProtoMessage() {}

func (x *CoreService_LocationUpdatedSetEnabledResponse_Requested) ProtoReflect() protoreflect.Message {
	mi := &file_garmin_gdi_core_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoreService_LocationUpdatedSetEnabledResponse_Requested.ProtoReflect.Descriptor instead.
func (*CoreService_LocationUpdatedSetEnabledResponse_Requested) Descriptor() ([]byte, []int) {
	return file_garmin_gdi_core_proto_rawDescGZIP(), []int{0, 6, 0}
}

func (x *CoreService_LocationUpdatedSetEnabledResponse_Requested) GetRequested() CoreService_DataType {
	if x != nil && x.Requested != nil {
		return *x.Requested
	}
	return CoreService_SIGNIFICANT_LOCATION
}

func (x *CoreService_LocationUpdatedSetEnabledResponse_Requested) GetStatus() CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return CoreService_LocationUpdatedSetEnabledResponse_Requested_OK
}

var File_garmin_gdi_core_proto protoreflect.FileDescriptor

const file_garmin_gdi_core_proto_rawDesc = "" +
	"\n" +
	"\x15garmin/gdi_core.proto\x12\x11garmin_vivomovehr\"\xe7\x16\n" +
	"\vCoreService\x12M\n" +
	"\fsync_request\x18\x01 \x01(\v2*.garmin_vivomovehr.CoreService.SyncRequestR\vsyncRequest\x12P\n" +
	"\rsync_response\x18\x02 \x01(\v2+.garmin_vivomovehr.CoreService.SyncResponseR\fsyncResponse\x12c\n" +
	"\x14get_location_request\x18\x03 \x01(\v21.garmin_vivomovehr.CoreService.GetLocationRequestR\x12getLocationRequest\x12f\n" +
	"\x15get_location_response\x18\x04 \x01(\v22.garmin_vivomovehr.CoreService.GetLocationResponseR\x13getLocationResponse\x12\x8f\x01\n" +
	"$location_updated_set_enabled_request\x18\x05 \x01(\v2?.garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledRequestR locationUpdatedSetEnabledRequest\x12\x92\x01\n" +
	"%location_updated_set_enabled_response\x18\x06 \x01(\v2@.garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponseR!locationUpdatedSetEnabledResponse\x12~\n" +
	"\x1dlocation_updated_notification\x18\a \x01(\v2:.garmin_vivomovehr.CoreService.LocationUpdatedNotificationR\x1blocationUpdatedNotification\x1a\r\n" +
	"\vSyncRequest\x1a\x99\x01\n" +
	"\fSyncResponse\x12R\n" +
	"\x06status\x18\x01 \x01(\x0e2:.garmin_vivomovehr.CoreService.SyncResponse.ResponseStatusR\x06status\"5\n" +
	"\x0eResponseStatus\x12\x1b\n" +
	"\x17UNKNOWN_RESPONSE_STATUS\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x1a\xa2\x01\n" +
	"\x12GetLocationRequest\x12`\n" +
	"\frequest_type\x18\x01 \x01(\x0e2=.garmin_vivomovehr.CoreService.GetLocationRequest.RequestTypeR\vrequestType\"*\n" +
	"\vRequestType\x12\f\n" +
	"\bSTANDARD\x10\x00\x12\r\n" +
	"\tEMERGENCY\x10\x01\x1a\xbb\x02\n" +
	"\x13GetLocationResponse\x12Q\n" +
	"\x06status\x18\x01 \x01(\x0e29.garmin_vivomovehr.CoreService.GetLocationResponse.StatusR\x06status\x12P\n" +
	"\rlocation_data\x18\x02 \x01(\v2+.garmin_vivomovehr.CoreService.LocationDataR\flocationData\"\x7f\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x01\x12\x15\n" +
	"\x11NO_VALID_LOCATION\x10\x02\x12!\n" +
	"\x1dLOCATION_SERVICES_UNAVAILABLE\x10\x03\x12\x1e\n" +
	"\x1aLOCATION_SERVICES_DISABLED\x10\x04\x12\x13\n" +
	"\x0fTRY_AGAIN_LATER\x10\x05\x1a\x80\x01\n" +
	" LocationUpdatedSetEnabledRequest\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12B\n" +
	"\brequests\x18\x02 \x03(\v2&.garmin_vivomovehr.CoreService.RequestR\brequests\x1a\xb1\x01\n" +
	"\aRequest\x12E\n" +
	"\trequested\x18\x01 \x01(\x0e2'.garmin_vivomovehr.CoreService.DataTypeR\trequested\x120\n" +
	"\x14min_update_threshold\x18\x02 \x01(\x02R\x12minUpdateThreshold\x12-\n" +
	"\x12distance_threshold\x18\x03 \x01(\x02R\x11distanceThreshold\x1a\x97\x04\n" +
	"!LocationUpdatedSetEnabledResponse\x12_\n" +
	"\x06status\x18\x01 \x01(\x0e2G.garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.StatusR\x06status\x12f\n" +
	"\brequests\x18\x02 \x03(\v2J.garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.RequestedR\brequests\x1a\xe9\x01\n" +
	"\tRequested\x12E\n" +
	"\trequested\x18\x01 \x01(\x0e2'.garmin_vivomovehr.CoreService.DataTypeR\trequested\x12r\n" +
	"\x06status\x18\x02 \x01(\x0e2Z.garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested.RequestedStatusR\x06status\"!\n" +
	"\x0fRequestedStatus\x12\x06\n" +
	"\x02OK\x10\x01\x12\x06\n" +
	"\x02KO\x10\x02\"=\n" +
	"\x06Status\x12\x06\n" +
	"\x02OK\x10\x01\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x02\x12\f\n" +
	"\bUNKNOWN3\x10\x03\x12\f\n" +
	"\bUNKNOWN4\x10\x04\x1ao\n" +
	"\x1bLocationUpdatedNotification\x12P\n" +
	"\rlocation_data\x18\x01 \x03(\v2+.garmin_vivomovehr.CoreService.LocationDataR\flocationData\x1a\xc7\x02\n" +
	"\fLocationData\x12A\n" +
	"\bposition\x18\x01 \x02(\v2%.garmin_vivomovehr.CoreService.LatLonR\bposition\x12\x1a\n" +
	"\baltitude\x18\x02 \x02(\x02R\baltitude\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x02(\rR\ttimestamp\x12\x1d\n" +
	"\n" +
	"h_accuracy\x18\x04 \x02(\x02R\thAccuracy\x12\x1d\n" +
	"\n" +
	"v_accuracy\x18\x05 \x02(\x02R\tvAccuracy\x12L\n" +
	"\rposition_type\x18\x06 \x02(\x0e2'.garmin_vivomovehr.CoreService.DataTypeR\fpositionType\x12\x18\n" +
	"\abearing\x18\t \x02(\x02R\abearing\x12\x14\n" +
	"\x05speed\x18\n" +
	" \x02(\x02R\x05speed\x1a,\n" +
	"\x06LatLon\x12\x10\n" +
	"\x03lat\x18\x01 \x02(\x11R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x02(\x11R\x03lon\"{\n" +
	"\bDataType\x12\x18\n" +
	"\x14SIGNIFICANT_LOCATION\x10\x00\x12\x14\n" +
	"\x10GENERAL_LOCATION\x10\x01\x12\x15\n" +
	"\x11REALTIME_TRACKING\x10\x02\x12\x14\n" +
	"\x10INREACH_TRACKING\x10\x03\x12\x12\n" +
	"\x0eTRACKING_EVENT\x10\x04BY\n" +
	"1nodomain.freeyourgadget.gadgetbridge.proto.garminZ$pulse/backend/internal/gproto/garmin"

var (
	file_garmin_gdi_core_proto_rawDescOnce sync.Once
	file_garmin_gdi_core_proto_rawDescData []byte
)

func file_garmin_gdi_core_proto_rawDescGZIP() []byte {
	file_garmin_gdi_core_proto_rawDescOnce.Do(func() {
		file_garmin_gdi_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garmin_gdi_core_proto_rawDesc), len(file_garmin_gdi_core_proto_rawDesc)))
	})
	return file_garmin_gdi_core_proto_rawDescData
}

var file_garmin_gdi_core_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_garmin_gdi_core_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_garmin_gdi_core_proto_goTypes = []any{
	(CoreService_DataType)(0),                                                    // 0: garmin_vivomovehr.CoreService.DataType
	(CoreService_SyncResponse_ResponseStatus)(0),                                 // 1: garmin_vivomovehr.CoreService.SyncResponse.ResponseStatus
	(CoreService_GetLocationRequest_RequestType)(0),                              // 2: garmin_vivomovehr.CoreService.GetLocationRequest.RequestType
	(CoreService_GetLocationResponse_Status)(0),                                  // 3: garmin_vivomovehr.CoreService.GetLocationResponse.Status
	(CoreService_LocationUpdatedSetEnabledResponse_Status)(0),                    // 4: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Status
	(CoreService_LocationUpdatedSetEnabledResponse_Requested_RequestedStatus)(0), // 5: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested.RequestedStatus
	(*CoreService)(nil),                                                          // 6: garmin_vivomovehr.CoreService
	(*CoreService_SyncRequest)(nil),                                              // 7: garmin_vivomovehr.CoreService.SyncRequest
	(*CoreService_SyncResponse)(nil),                                             // 8: garmin_vivomovehr.CoreService.SyncResponse
	(*CoreService_GetLocationRequest)(nil),                                       // 9: garmin_vivomovehr.CoreService.GetLocationRequest
	(*CoreService_GetLocationResponse)(nil),                                      // 10: garmin_vivomovehr.CoreService.GetLocationResponse
	(*CoreService_LocationUpdatedSetEnabledRequest)(nil),                         // 11: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledRequest
	(*CoreService_Request)(nil),                                                  // 12: garmin_vivomovehr.CoreService.Request
	(*CoreService_LocationUpdatedSetEnabledResponse)(nil),                        // 13: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse
	(*CoreService_LocationUpdatedNotification)(nil),                              // 14: garmin_vivomovehr.CoreService.LocationUpdatedNotification
	(*CoreService_LocationData)(nil),                                             // 15: garmin_vivomovehr.CoreService.LocationData
	(*CoreService_LatLon)(nil),                                                   // 16: garmin_vivomovehr.CoreService.LatLon
	(*CoreService_LocationUpdatedSetEnabledResponse_Requested)(nil),              // 17: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested
}
var file_garmin_gdi_core_proto_depIdxs = []int32{
	7,  // 0: garmin_vivomovehr.CoreService.sync_request:type_name -> garmin_vivomovehr.CoreService.SyncRequest
	8,  // 1: garmin_vivomovehr.CoreService.sync_response:type_name -> garmin_vivomovehr.CoreService.SyncResponse
	9,  // 2: garmin_vivomovehr.CoreService.get_location_request:type_name -> garmin_vivomovehr.CoreService.GetLocationRequest
	10, // 3: garmin_vivomovehr.CoreService.get_location_response:type_name -> garmin_vivomovehr.CoreService.GetLocationResponse
	11, // 4: garmin_vivomovehr.CoreService.location_updated_set_enabled_request:type_name -> garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledRequest
	13, // 5: garmin_vivomovehr.CoreService.location_updated_set_enabled_response:type_name -> garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse
	14, // 6: garmin_vivomovehr.CoreService.location_updated_notification:type_name -> garmin_vivomovehr.CoreService.LocationUpdatedNotification
	1,  // 7: garmin_vivomovehr.CoreService.SyncResponse.status:type_name -> garmin_vivomovehr.CoreService.SyncResponse.ResponseStatus
	2,  // 8: garmin_vivomovehr.CoreService.GetLocationRequest.request_type:type_name -> garmin_vivomovehr.CoreService.GetLocationRequest.RequestType
	3,  // 9: garmin_vivomovehr.CoreService.GetLocationResponse.status:type_name -> garmin_vivomovehr.CoreService.GetLocationResponse.Status
	15, // 10: garmin_vivomovehr.CoreService.GetLocationResponse.location_data:type_name -> garmin_vivomovehr.CoreService.LocationData
	12, // 11: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledRequest.requests:type_name -> garmin_vivomovehr.CoreService.Request
	0,  // 12: garmin_vivomovehr.CoreService.Request.requested:type_name -> garmin_vivomovehr.CoreService.DataType
	4,  // 13: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.status:type_name -> garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Status
	17, // 14: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.requests:type_name -> garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested
	15, // 15: garmin_vivomovehr.CoreService.LocationUpdatedNotification.location_data:type_name -> garmin_vivomovehr.CoreService.LocationData
	16, // 16: garmin_vivomovehr.CoreService.LocationData.position:type_name -> garmin_vivomovehr.CoreService.LatLon
	0,  // 17: garmin_vivomovehr.CoreService.LocationData.position_type:type_name -> garmin_vivomovehr.CoreService.DataType
	0,  // 18: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested.requested:type_name -> garmin_vivomovehr.CoreService.DataType
	5,  // 19: garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested.status:type_name -> garmin_vivomovehr.CoreService.LocationUpdatedSetEnabledResponse.Requested.RequestedStatus
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_garmin_gdi_core_proto_init() }
func file_garmin_gdi_core_proto_init() {
	if File_garmin_gdi_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garmin_gdi_core_proto_rawDesc), len(file_garmin_gdi_core_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_garmin_gdi_core_proto_goTypes,
		DependencyIndexes: file_garmin_gdi_core_proto_depIdxs,
		EnumInfos:         file_garmin_gdi_core_proto_enumTypes,
		MessageInfos:      file_garmin_gdi_core_proto_msgTypes,
	}.Build()
	File_garmin_gdi_core_proto = out.File
	file_garmin_gdi_core_proto_goTypes = nil
	file_garmin_gdi_core_proto_depIdxs = nil
}
